### ISSUE TITLE
Starred messages don't shown in Starred box

### ISSUE THREAD

**Issue by DmitryLoki** [Foundry376/Mailspring#100]
##### Are there any related issues?

Nope

##### What operating system are you using?
Ubuntu 16.10

##### What version of Mailspring are you using?
1.0.2-4eab

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?
When I star a single message it shows in Starred box, but when I star a thread with multiply messages it doesn't. 

There are two starred (clicked on star || pressed 's') messages in my inbox.
![screenshot from 2017-10-09 19-40-23](https://user-images.githubusercontent.com/1115774/31367134-0a665718-ad2a-11e7-8ea8-f76786fcd011.png)

Here is only one of them in Starred box
![screenshot from 2017-10-09 19-40-06](https://user-images.githubusercontent.com/1115774/31367130-082255a6-ad2a-11e7-82a3-15a489eac78a.png)

I didn't have this bug in Nylas before.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yeap :)

**Comment by neddy70** [comment]
I can confirm that I have the same issue. Starred emails with more that one email in the conversation are not visible in the 'Starred' label in Mailspring. However when I log into Gmail the conversations are in the 'Starred' label.

**What operating system are you using?**

MacOS 10.13

**What version of Mailspring are you using?**

Version 1.0.3 (1.0.3)

--

**Do you have any third-party plugins installed? If so, which ones?**

No

**Is the issue related to a specific email provider (Gmail, Exchange, etc.)?**

Gmail

**Comment by nul0m** [comment]
+1, Ubuntu 16.04.3

**Comment by bengotow** [comment]
Hey @neddy70 wow thank you so much for figuring that out — I was able to reproduce this by starring a bunch of emails in the same thread.

I'm working on a patch for this and I'll get if fixed for the next release. The reason this is happening is because Mailspring thinks "starred" is a boolean value and is making a SQLIte query `WHERE starred = 1`. The new C++ sync engine does some reference counting and the starred field is actually an `int`, where the value is the number of starred messages. The reference counting approach makes it much faster to keep threads in sync with the messages they're composed of, but means that the correct query for starred is actually `WHERE starred != 0`.

Thanks again—
