### ISSUE TITLE
Tracking Location [Feature Request]

### ISSUE THREAD

**Issue by juanbermudez** [Foundry376/Mailspring#1022]
It would be amazing to have the read/click notifications for email include the location for those activities. 

Thanks!!

**Comment by bengotow** [comment]
Hey thanks for reporting this! We'd actually really like to do this, but it's not feasible these days because many email providers like Gmail re-write and proxy tracking pixel requests through their own servers so you can't geolocate people who are using Gmail.com. (It's actually great for user privacy / the internet at large, but a bummer for Mailspring.) I think we could provide the feature, but it'd probably be inaccurate a frustrating amount of the time!

**Comment by juanbermudez** [comment]
That makes complete sense. It would definitely end up showing some wrong locations.

Thought it would be interesting to get your thoughts on it. 

BTW, great job with the product, I was a long time Nylas Mail user and I love Mailspring.

**Comment by sheatsb** [comment]
If the underlying tech would allow for it, I would sincerely ***NOT*** want this feature at all - it's a violation of privacy for the end user already, and egregiously so including location.

**Comment by CodeMouse92** [comment]
I agree that this would bring up some major privacy/ethical concerns, in addition to being highly inaccurate.
