### ISSUE TITLE
spell check does not work

### ISSUE THREAD

**Issue by lrdegeest** [Foundry376/Mailspring#1034]
##### Are there any related issues?

Not sure. 

##### What operating system are you using?

MacOS High Sierra 10.13.6

##### What version of Mailspring are you using?

1.4.2

--

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Unclear

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes

Just downloaded Mailspring for mac. Spellcheck does not work:

<img width="636" alt="screen shot 2018-08-19 at 7 33 33 pm" src="https://user-images.githubusercontent.com/10857097/44314415-e5eb2a80-a3e6-11e8-96a6-031a38ea83d5.png">

even though spellcheck is turned on:

<img width="381" alt="screen shot 2018-08-19 at 7 33 45 pm" src="https://user-images.githubusercontent.com/10857097/44314422-fb605480-a3e6-11e8-9422-420a58eaf0cb.png">

Am I missing something?

**Comment by bengotow** [comment]
Hmm interesting—this is working for me on macOS... could you see if there's anything different in the Keyboard panel of System Preferences? Also, do you know if you have your keyboard set to US English or another locale? I switched the "Default spellcheck language" to Spanish and it started spellchecking in Spanish for me... not sure what else could be going on!

<img width="780" alt="image" src="https://user-images.githubusercontent.com/1037212/45644596-f25cb480-ba72-11e8-9337-15586fc7afe7.png">

**Comment by lrdegeest** [comment]
Sorry, my settings are in order but spell check still does not work. MacOS High Sierra 10.13.6

**Comment by texelate** [comment]
I have the exact same problem. I am using Mojave 10.14.

**Comment by liamdevine82** [comment]
I am also having the same issue using High Sierra 10.13.6

There is not red dotted line beneath misspelled words

**Comment by bengotow** [comment]
Hey folks—any chance you've been using Mailspring with an "interface zoom" setting < 1? In #1140 we found that the red squiggles were getting rounded-down out of existence if you choose anything less than one, so there was no highlighting of misspelled words. Hopefully that's the issue here as well—will be fixed in the next release!

<img width="471" alt="image" src="https://user-images.githubusercontent.com/1037212/47968446-0eb2b180-e01f-11e8-8bce-53b524c59f29.png">

**Comment by Jeredann** [comment]
Windows 11 - spell check is not working for me either. I am a new user. It is turned on in settings. no sign of it when composing email.

**Comment by koshibb** [comment]
Same boat here. I am greater than 1 scaling (and have tried 1 exactly) and no red squigglies come up at all.

**Comment by Jeredann** [comment]
Thanks for the update.That was an awhile ago. I decided to sell the MS computer and get a MAC mini. I was tired of the spell checker not working and was damned if I was going to pay MS for the basic functionality of word. LOLah well - like the miniOn Jan 27, 2026, at 12:40 AM, Ben Gotow ***@***.***> wrote:﻿bengotow left a comment (Foundry376/Mailspring#1034)
Hey @lrdegeest (and @Jeredann, @texelate, @liamdevine82, @koshibb),
Thanks for reporting this issue—I know it's been frustrating to have spellcheck not working properly across these platforms.
There's been significant work on Mailspring since these reports, and we've addressed the underlying spellcheck issue by completely replacing the custom Slate spellcheck plugin with native browser spellcheck. The old implementation was causing the red squiggles to disappear, and the new approach uses the DOM spellcheck attribute with intelligent typing-debounce for better performance. This fix resolves spellcheck issues on both Windows and macOS.
See: #2535 (000784f)
We've also fixed a related issue where the spellcheck toggle was interfering with keyboard input during composition: #2578 (1d77743)
If you get a chance, please download the latest version from https://getmailspring.com/download and give spellcheck another try. You should now see the red squiggles appear properly when you misspell words.
Note: We've moved discussions to our community forums at https://community.getmailspring.com, but feel free to reply here as well.
