### ISSUE TITLE
Why Gmail authentication is done using internet browser window and not within the desktop app itself (unlike other authentications)?

### ISSUE THREAD

**Issue by vijayakumar-s** [Foundry376/Mailspring#1047]
##### Are there any related issues?

...

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

1.4.2

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Gmail 

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by kirbyfan64** [comment]
I *think* this is partly because you're probably signed in to your Google account in your web browser already, so you won't have to sign in twice.

**Comment by gyunaev** [comment]
Because authentication with GMail (and Google services in general) is not as simple as passing username-password. There is two factor authentication for those who set it up, or for everyone if Google decides "something is wrong". They also sometimes ask follow-up information.

None of this should apply, however, if you add Gmail as as POP3 account.

**Comment by bengotow** [comment]
Hey! Yep—@kirbyfan64 nailed it. The very first versions of Mailspring did authentication in a window within the Mailspring application, but almost everyone is already signed in within their browser so doing it there makes the process smoother. (Avoid needing two-factor auth, etc.) When we had it in the app, you also couldn't access your password managers like 1Password or LastPass, which was a huge pain.

Hope that helps!

**Comment by maaku** [comment]
FWIW this is not convenient for all users. I've been pulling my hair out over this the last few days, not understanding that Mailspring was not acting like other apps. I do NOT stay logged into my Google account on my browser, because I value my privacy. That's a big part of why I use a rich mail client and not the gmail web interface.

However when I log out of google on my browser, it also makes Mailspring unable to connect to my email. I have been unable to add IMAP access since the authorization mechanism used by mailspring is out of date and blocked by Google. So alas, I'm ditching Mailspring despite initially liking it a lot.

**Comment by refi64** [comment]
That sounds like a big somewhere, it shouldn't be like that? That being said 
> I have been unable to add IMAP access since the authorization mechanism used by mailspring is out of date and blocked by Google. 
You need to create an app password for this, then manual IMAP will work.
