### ISSUE TITLE
Image at Signatures can't shown

### ISSUE THREAD

**Issue by emper0r** [Foundry376/Mailspring#105]
Hi,

Can't see the image at signatures, even I wrote at raw html when save can't be show. 
So if can possible to added as feature or fixed that I'll very apprecieted 

Thanks for your work.

**Comment by PrzemekSkw** [comment]
I have image in my signature in gmail, now when i try Mailspring I copy signature from gmail and image is invisible, there's no option to add image..

**Comment by PrzemekSkw** [comment]
@bengotow I add image to my signature with html but I see it only in Mailspring, when i send messege it is invisible.
![zrzut ekranu deepin_wybierz-obszar_20171204105715](https://user-images.githubusercontent.com/25219988/33546622-cd810cba-d8e1-11e7-87dd-76235cc3a72f.png)
I need to put my image on some www server?

**Comment by bengotow** [comment]
Hey folks—yep, the images you add to your signatures need to be available on the web via HTTPS. Some older clients like Thunderbird allow you to put an image in your signature by attaching the image file to emails you send, but this increases the size of every message and isn't supported by Mailspring.

We added a new signature editor in 1.0.10 that makes it really easy to add an image to your signature, and handles uploading it to the web and resizing it. Enjoy!

**Comment by atyshka** [comment]
@bengotow As a feature request, would it be difficult to integrate this upload functionality into the custom html signature type? I have a company required signature that has embedded raw images so I cannot use the default mailspring templates

**Comment by atyshka** [comment]
For that matter, is it really that big of a deal to embed some small images? My company logos make the signature about 100KB which I would argue is completely negligible. While I understand the reasoning, this is a big inconvenience and inline images are supported in major email clients like Outlook and Apple mail. Without some solution I am unable to use Mailspring for now.

**Comment by vanquang9387** [comment]
I got same issue with version 1.7.2 on Windows 10.

**Comment by carvajalluis** [comment]
this is breaking  use case for marketing  email signatures. many companies provide email signatures with tracking images   and  links to social networks. I don't know how are you forced to remove  the users hability to store any signature locally they want. should I be copy and pasting my signature manually on every email ?

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

The conversation after this issue was closed appears to be related to an issue we've already migrated to Discourse:

https://community.getmailspring.com/t/using-images-for-full-signature/769

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team
