### ISSUE TITLE
Can't sign in with Gmail

### ISSUE THREAD

**Issue by desertdisk** [Foundry376/Mailspring#1094]
##### Are there any related issues?

Not that I can find.

##### What operating system are you using?

Debian 9.5 Stretch - Chromebook Linux Beta

##### What version of Mailspring are you using?

1.4.2-f587b7b7

**Bug?**

##### Is this an email sync or connection issue?

Yes

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Yes - Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

After attempting to sign into my Gmail account, the browser redirects to:
http://127.0.0.1:12141/?code=xxx

![image](https://user-images.githubusercontent.com/3484659/46098480-837a0c80-c192-11e8-9ae5-ee91529f3ebb.png)

**Comment by purefan** [comment]
hmm... strange because there's a check to make sure the server did start up, do you have an antivirus or firewall? if so, can you try to disable it just while you set up gmail? (for normal operations that local address isn't used)

**Comment by desertdisk** [comment]
> do you have an antivirus or firewall?

No, I do not. I'm on a Chromebook connected to my home wifi. I was able to get set up using the IMAP configuration, but the Google sign-in never did work.

**Comment by purefan** [comment]
oh ok... then I guess that's the problem, ChromeOS seems to [block calls to 127.0.0.1](https://stackoverflow.com/questions/47525471/chromeos-chrome-cant-reach-127-0-0-18080) I wonder if `localhost` works better.

If you are able/willing to give this a try:
1. git clone mailspring
2. open the file `/app/internal_packages/onboarding//lib/onboarding-helpers.es6`
3. on line 10 you should find `export const LOCAL_REDIRECT_URI = `http://127.0.0.1:${LOCAL_SERVER_PORT}`;`
4. Edit that line so it looks like this: `export const LOCAL_REDIRECT_URI = `http://localhost:${LOCAL_SERVER_PORT}`;`
5. run `npm start`
6. try to add a gmail account again

This is a bit of a shot in the dark, I didn't know that ChromeOS blocks calls like that until I saw this report and googled about it, there's no guarantee that calling `localhost` instead of `127.0.0.1` works, but then it really can't _break it worse_

**Comment by desertdisk** [comment]
Thanks for the walkthrough. I will give that a shot.

**Comment by aia832003** [comment]
@joryhatton or @purefan is there an update on this workaround? Just ran into this last night on my new Pixelbook. Was so excited to run Mailspring and can't get past this. @purefan where would I be implementing this git mailspring command? I don't mind giving this a shot as well.

**Comment by joryhatton** [comment]
> @joryhatton or @purefan is there an update on this workaround? Just ran into this last night on my new Pixelbook. Was so excited to run Mailspring and can't get past this. @purefan where would I be implementing this git mailspring command? I don't mind giving this a shot as well.

I never ended up using the `git clone` strategy. I was able to get it working using IMAP configuration.

**Comment by eliranwong** [comment]
experienced the same issue, but uable to sign in with IMAP, so cannot use Mailspring on my chromebook.  Please advise, I tried to run npm start as advised above, but errors come up.

**Comment by eliranwong** [comment]
Finally, I found a solution, without lowering security level of gmail accounts.

The key is to go through the gmail account verification process through the web browser installed in Crostini instead of Chrome os built-in browser.   Service running INSIDE the container at either 127.0.0.1 or localhost is inaccessible to Chrome os browser, which is outside the container.  However, the service is perfectly accessible with a web browser installed INSIDE the container.

For those who are interested, I put notes and screenshots at: https://github.com/eliranwong/Chrome-OS-Linux/blob/master/gui-apps-linux/Readme.md#trouble-shooting-mailspring-setup
