### ISSUE TITLE
Is Mailspring continuing developed?

### ISSUE THREAD

**Issue by phamhung77** [Foundry376/Mailspring#1096]
A lot of issues posted, but not much answer. There are less and less commits from Insights tab. It gives me a feeling that Mailsping is another Mac-based email client which will be abandoned soon. Hopefully, my feeling is incorrect.

**Comment by purefan** [comment]
Im trying to catch up with the internals but ultimately this depends on @bengotow 
Please keep in mind that he has a life and will come to aid us as soon as he can

My feeling is that there are plenty of people interested in driving this project forward and we just need a little nudge here and there from Ben, then we can snowball it towards helping others and eventually have a self-sustaining dev team

**Comment by phamhung77** [comment]
I totally understand and respect each person's personal life. On the other hand, Mailspring also offers a paid plan. How do you charge a monthly subscription, while there is no update on the product? I also tried to send several requests via support (listed on the website at https://foundry376.zendesk.com/hc/en-us), but never get an answer :)

**Comment by CarlosRebolledoA** [comment]
Hi Miguel, I'm happy to see your support and I hope that Ben can give momentum and development to Mailspring, understanding that he should be meditating on this. He was part of Nylas, he gave continuity to Mailspring and it should not be easy to leave this son. My support for Ben.

I also understand the concern of who we are users. I also have the worry, more if we want to use Mailspring in our work.

Finally, I do not know the required capital, but perhaps joint financing and development options may be generated, such as payment for the pro version, donations and generating a reliable support team because there is interest in it. It all adds up.

A hug

**Comment by purefan** [comment]
Hi Carlos! :) Hopefully we can bring the momentum back, Mailspring is kinda fun to work with :) 

Side note: the last commit from Ben was 10 days ago, so I wouldn't count it as dead yet. Perhaps lack of presence in the issues but not dead in the code :P my opinion though 

Cheers all!

**Comment by 10robinho** [comment]
@purefan Thanks for clarification. I was wondering the same thing, especially after I saw few large issues being ignored to oblivion of issue list.

I'm paying for premium but now I don't understand where this money goes to. That is another point of confusion now.

**Comment by vberruezo** [comment]
> I totally understand and respect each person's personal life. On the other hand, Mailspring also offers a paid plan. How do you charge a monthly subscription, while there is no update on the product? I also tried to send several requests via support (listed on the website at https://foundry376.zendesk.com/hc/en-us), but never get an answer :)

I am in the same situation. Paid user and it has been 2 weeks without response...

**Comment by LightSnowDev** [comment]
I think I might stop the development of my [Material-Spring](https://github.com/LightSnowDev/Material-Spring) theme, since there is no sign of life. Its the same thing as it was with Nylas. Just no communications.  
It seems, that this project is not as Community driven, as it seemed to be at first. The problem is not the lack of fixed issues, but just not telling everybody whats going on.

**Comment by ronisbr** [comment]
Let’s hope that, if the development has stopped, then the full source code can be released. Then the community can take care. Mainspring is way faster than Nylas was, and some concepts are really good. I hope the project continues.

**Comment by purefan** [comment]
The main blocker for development of Mailspring is the complexity of mailsync, that's the only closed source part of Mailspring. Ben has explained why mailsync is closed source and I agree with his decision, perhaps a simpler replacement can be found and Im all for spending time on Mailspring but I do get discouraged when the main actor doesn't show up for weeks and we're left with a "hangry" community desperate for guidance (myself included) . 

I will try to find a replacement for mailsync, I know what it does and I believe there should be an alternative, the other problem is that without Ben PRs will just linger

**Comment by CarlosRebolledoA** [comment]
@purefan for your words we will have to wait. 

@bengotow  I invite you to indicate a date in which you could respond to everyone's concerns, which is no more than the consequence of a real interest in Mailspring and our quality of users, some Pro (myself included). We await your answer, and I hope you are well

**Comment by bengotow** [comment]
Hey folks! Sorry for the delay responding to this—just to address a few concerns here:

- Mailspring definitely isn't dead—I've been working on localizing the whole app into a bunch of languages (on the bengotow/localization branch) and that work hasn't landed yet, so things are looking a little stale on master. The pace of development has definitely slowed a bit though, but that leads me to #2:

- Mailspring pretty much does what I want it to—This year I rebuilt the signature editor, added TouchBar support, redesigned the search bar, expanded the app's menus to include all existing shortcuts, and switched the composer to a new text editor. There are a lot of open issues (and more every week), and lots of legitimate bugs, but Mailspring works properly for the majority of people who download it. (Last I checked several hundred a day!) Many issues (like #277) may never be fixed, either because they're technically challenging (that one actually is because of some old Nylas limitations) or because they're too niche (eg: two votes / comments in a year). In some scenarios I'd accept a pull request, but in other cases the maintenance overhead of adding a bunch of `if` statements and logic for a unique behavior isn't worth it.

- I really appreciate the folks that are paying for Mailspring Pro. It doesn't generate a ton of money, but it means I'll be able to continue contributing for a long time and cover the costs of running the pro features. I'm planning to focus more of future development on pro features—things like a dedicated Mail Merge tool, better template support, etc. (I'm also hoping to add typeahead autocompletion in the composer ala the new Gmail feature.)

- In the next few months, I want to create a public theme gallery and plugin gallery, and allow users to install themes / plugins with a single click. This will probably be a mix of work on the app and on a separate website.

I think there are a couple things I / the Mailspring project could do better, and I'd love to get your thoughts:

- Every so often I tag issues as "[Good First Issue](https://github.com/Foundry376/Mailspring/labels/good%20first%20issue)" and add a bit of context for folks getting started, but Mailspring hasn't seen many contributions. What else could I do to help drive that forward? (I definitely don't want to be the only contributor...). I'd really love for folks to pick up some larger, more interesting projects (anyone want to add an Address Book or a minimal calendar?) but the combination of Node + Electron + existing code makes it a tough project to get started with. I know the old Nylas docs have fallen woefully out of date—maybe it's time to re-invest in internal documentation?

- I definitely need to do a better job of pull requests. There are a handful I've left open because they're functional / nice from a code standpoint but add niche options, and I was hoping that a few more folks would chime in and be interested in the feature. I think of Mailspring as more of a product than a project and I'm generally hesitant to add configuration options, but I definitely want to avoid having things sit there in the future. Maybe the `product-direction` label could tag things that need more user feedback / votes before they're worth including in the product as options?

- Right now there's a ROADMAP.md, but it's a bit old. I definitely need to keep this up-to-date—I'll see if I can revisit it this week and include some things that would be good contributor projects.

- Mailspring's GitHub issues are getting pretty overwhelming—If anyone knows of tools that help identify duplicates, I think it'd probably really help. Now that there are 500+ issues, I think they need to be linked / merged together to give a better overall picture of where problems are?

Also, thanks everyone for all the kind words and your commitment to the project!

**Comment by purefan** [comment]
Man thanks for posting! I just found more motivation to keep looking into Mailspring :) 

- Documentation: Yes, I think its best if we re-document Mailspring, for a new developer who doesn't know about Nylas it must be confusing to see references that lead nowhere ("what is this Nylas thing...?"), broken links are also a big detriment 
- The plug-in system has me very excited! eager to see how that works

I'll do my very best to send a PR this week, I want easier debugging and Im thinking of using winston with a setting to produce a log file, I think that will help us troubleshoot some edge cases (like the multiple replies issue). 

Thanks again Ben!

**Comment by leleobhz** [comment]
@bengotow A thing I consider to use Mailspring as a paid signature is Exchange and Calendar support. Today I have 8 mail accounts, 4 gmail, 2 office365 and 2 exchange accounts. I need this because I represent my customers, but I confess I'm a bit worried because there is any mail client in Linux that does close Outlook does. Thunderbird as example is a great mail client, but Exquila support is a mess and constantly I miss messages and I have issues with folders too. Calendar on thunderbird never worked well with exchange, so I still a bit close with webmails, but use 8 accounts in webmails isnt a easy thing. 

That said, there is a roadmap - even as pro feature - for these 2 features (And supporting Gmail and Office365/Exchange accounts)?

**Comment by akdor1154** [comment]
Having an only partially open-source product certainly demotivates me from contributing to Mailspring.
It gives the first impression that it is a commercially driven product that has been open-sourced for "feel-good" reasons as opposed to fully embracing a traditional community development model. Other aspects of the project (e.g. single lead bottleneck maintainer [please don't see this as a personal insult, I think @bengotow is doing an excellent job, it's more a comment on the scalability of this model]) cement this view.
I am aware this impression is probably false, and that there are legitimate pragmatic reasons for the sync component to remain closed, however the fact remains that anecdotally, this dis-incentivizes me to contribute, and potentially many other potential users/contributors as well.

**Comment by mferretti** [comment]
I have been using mailspring for about a month or so and was thinking about going pro, but I can't get a grasp on what the "pro" features are.
On the other hand, I really do appreciate the client and am looking forward to a calendar (google ?) support!

**Comment by quattroman** [comment]
Hi, I am paying for the ability to uses the "tracking" and "linktracking" applications as and when required.  I have nothiced that on occasions an email, with this modes switched on, loses this ability and hence no tracking is available for this email chain.  I have attached a log file to aid investigation.  For security I have anotated my Gmail account details to read XXXXX@gmail.com and the sent to email addrress to XXXXXX@hotmail.com
[mailspring.txt](https://github.com/Foundry376/Mailspring/files/4984376/mailspring.txt)

**Comment by CodeMouse92** [comment]
For anyone who finds this later: Mailspring development has resumed! To help facilitate this, we have a new Discourse community, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Please join our Discourse at https://community.getmailspring.com

We hope to see you there soon!

- The Mailspring Team
