### ISSUE TITLE
Cutting off the bottom of emails

### ISSUE THREAD

**Issue by EvilJimJafar** [Foundry376/Mailspring#1097]
##### What operating system are you using?

Manjaro Gnome

##### What version of Mailspring are you using?

1.4.2

**Bug?**

Some emails are being cut off.

![selection_058](https://user-images.githubusercontent.com/325261/46116871-b70b7400-c230-11e8-8e79-0ed32473136d.png)

**Comment by LogX7** [comment]
+1 .. i'm getting the same issue, i have to open the email in a new window when this happens
OS : Linux Mint 19 - Cinnamon 3.8.9
Version : 1.5.3-420ce003

i think this is happening because mailspring is setting the height of the email before the email is fully loaded, because this behavior mostly happens with emails filled with images

**Comment by flagrama** [comment]
+1
OS: Arch Linux - Cinnamon 4.0.9
Version: 1.5.5-b7939d38

**Comment by mmnaseri** [comment]
Any updates on this? Same issue on macOS, Arch + KDE Plasma, Arch + GNOME.

**Comment by bengotow** [comment]
Hey folks! This should be fully resolved now, and we've just pushed up a fix for #1762, in which we were chopping off the last line beneath the horizontal scrollbar. Should be set in the next release 👍
