### ISSUE TITLE
Darkside Theme on Custom Window Frame and Right Hand Menu has bad circles

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#1104]
##### Are there any related issues?

Possibly #627 
...

##### What operating system are you using?
Manjaro (`uname -a`: Linux desktop 4.18.9-1-MANJARO #1 SMP PREEMPT Thu Sep 20 04:58:28 UTC 2018 x86_64 GNU/Linux)
...

##### What version of Mailspring are you using?
1.4.2-1
...

--

**Bug?**
![image](https://user-images.githubusercontent.com/25718989/46241470-c1c73400-c3fd-11e8-874b-f94442ab4580.png)
title explains it all
squares until hovered over when it's ovular.
Less is more theme has similar squares but correctly shaped circles.

**Comment by bengotow** [comment]
Ahh good catch! Will get this fixed in the next release.

**Comment by jnylen** [comment]
@bengotow JFYI,
I haven't had this issue for the past releases since like 1.4 something.

As it uses the native linux window buttons. (Maybe some setting?)

**Comment by bengotow** [comment]
Hey! This has been fixed in 1.6.0 which shipped today. The app should auto-update, but you can also get the new version manually from https://getmailspring.com/download. Thanks - enjoy the app.

@jnylen  hmm I think you're right - it might depend on the display settings you've chosen in Preferences > Appearance. I think it only applies to the "right hand menu and custom toolbar" option.
