### ISSUE TITLE
Too many active connections

### ISSUE THREAD

**Issue by jonschr** [Foundry376/Mailspring#1113]
##### What operating system are you using?

MacOS Mojave

##### What version of Mailspring are you using?

1.4.2

--

**Bug?**

##### Is this an email sync or connection issue?

Yes, the specific error message I'm getting is shown below. Unfortunately, it doesn't seem possible to clear this error :(

![screen shot 2018-10-06 at 3 18 27 am](https://user-images.githubusercontent.com/2929672/46569219-44c51e80-c917-11e8-999c-b729067a8e5d.jpg)

![screen shot 2018-10-06 at 3 19 27 am](https://user-images.githubusercontent.com/2929672/46569213-3971f300-c917-11e8-991a-98ee21592267.jpg)

Logs here:

[mailsync-9ce1e60c.log](https://github.com/Foundry376/Mailspring/files/2452840/mailsync-9ce1e60c.log)
[mailsync-57fe9bdb.log](https://github.com/Foundry376/Mailspring/files/2452841/mailsync-57fe9bdb.log)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

It seems to be only my gmail account. There's a Google Apps account that's worked fine throughout.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Seems to come and go a bit, but I've never had an issue synching with another email client in this particular way. Even with this particular issue, I just signed up for your premium version – this is a really, really good client for where it's at right now. The search is very fast, and this is the most attractive app I've seen since Newton folded.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—this is super interesting. Gmail has a connection limit of ~10 IMAP connections per account, and Mailspring uses two (one for background mail sync and one for loading things fast when you interact with the UI and performing actions). 

You could hit this limit if you have lots of apps authorized to access your Gmail account and they're hitting your account from the cloud (ala Mailbox) or if you're running a bunch of other clients at once. (I think some clients are "greedy" during initial sync - it's possible that if you just set up another app it may be hogging the connections to download mail as quickly as possible.) Unfortunately, there's not too much we can do from the app side - if you figure it out definitely let me know what the cause was, and I'll see if we can improve that error!

**Comment by redblueconcepts** [comment]
That's the first place I went as well. I had actually already reauthorized
most of the apps.

I can take a look and give you a list of what's still authorized., And I'll
let you know if I (think) I figure it out.

Could you point me towards that documentation? I'd love to know how long it
times out for.
