### ISSUE TITLE
[Feature Request] Sync immediately after "long jump in time"

### ISSUE THREAD

**Issue by alexozer** [Foundry376/Mailspring#1123]
I'm using mailspring 1.4.2 on Arch Linux.

It would be nice if mailspring would immediately sync if it detects that a long period of time has elapsed. Specifically, if I suspend my laptop for the night and resume it in the morning, mailspring doesn't seem to sync immediately and I have to sync it manually, even though it's more than due to sync. I'm not exactly sure when it currently decides to sync in the background.

**Comment by bengotow** [comment]
Hey! This is interesting—we currently run a JavaScript timer that goes off every 30s to check whether the app is online (in `OnlineStatusStore.es6`), and if it fires "late" (eg, more than 30s has passed since the last invocation), we assume that the app has woken from sleep. That is supposed to trigger `mailsync-bridge.es6::_onOnlineStatusChanged`, which wakes the mailsync processes. I wonder if Linux is working slightly differently and the app is detecting wake-from-sleep but attempting to sync before it has an internet connection, failing, and then waiting 30s or 120s to try again.

I'll check and make sure this actually works on macOS and we can dig in a bit more to what's going on with Linux.

**Comment by alexozer** [comment]
Great thanks! I should also point out that I haven't really had the ability to reproduce this yet, and haven't seen any sync issues since.

**Comment by bengotow** [comment]
Hey folks! This was implemented back in 2018 and it looks like we just forgot to close this. Cheers!
