### ISSUE TITLE
Mails grouped as NIL

### ISSUE THREAD

**Issue by adrianbrosz** [Foundry376/Mailspring#1171]
After latest update (Linux, v1.5.0) email messages without user name in from: field - having only email address are grouped under 'NIL' name what is very uncomfortable, eg:

from: [] axxxxx@gmail.com -> grouped in thread as '[NIL] axxxxx@gmail.com
from: [Adrian Brosz] axxxxx@gmail.com  -> grouped correctly in thread [Adrian Brosz]

**Comment by nfaivre** [comment]
Same issue here, linux version 1.5.0

**Comment by kshaner** [comment]
Same issue here in Windows, also notification center alerts show up as NIL in the sender line.

**Comment by danielmartincraig** [comment]
Same here, on Ubuntu 18.04, mailspring v. 1.5.0.

**Comment by b34rl0rd** [comment]
Same here. Windows 10, mailspring v1.5.0

**Comment by MuTaTeD** [comment]
Facing the same issue since the upgrade to v1.5.0 on Kubuntu 18.04

- Mail Sender is NIL if the sender name is not already in contact or sender name not part of the header
- Mail Recipients are similarly marked NIL 
- Plus emails with no Subject are also marked NIL.

Previously all of them were handled correctly..

Let me know if you need screenshots or more details

**Comment by asitek23** [comment]
Same here, Ubuntu 18.04 with newest version 1.5.0

**Comment by MikeSharkey1** [comment]
Same here, with the latest version that claimed to fix this: 1.5.1 on macOS 10.14

**Comment by adrianbrosz** [comment]
Version 1.5.1 fixed the bug on Linux

**Comment by adrianbrosz** [comment]
Fixed
