### ISSUE TITLE
Attachment-download dialog box has unreadable characters

### ISSUE THREAD

**Issue by ghost** [Foundry376/Mailspring#1205]
![screenshot from 2018-10-31 16-46-58](https://user-images.githubusercontent.com/21981836/47785200-006a4a00-dd2e-11e8-8303-594d59a66a83.png)

Are there any related issues?
No

What operating system are you using?
Ubuntu 18.04

What version of Mailspring are you using?
1.5.1-da141eaf

**Bug?**

Is the issue reproducible with a particular attachment, message, signature, etc?
Yes

**Comment by bengotow** [comment]
Wow this is super interesting... I've never seen this before. It looks like there's an extensive conversation about it over in https://github.com/LightTable/LightTable/issues/2343 but I don't quite understand the resolution there, and it was reported and fixed in Electron (https://github.com/electron/electron/issues/9616), but the version we're using is quite a bit newer than the fix version.

I'll post about this on the Electron Slack and see if we can get some answers - stay tuned!

**Comment by bengotow** [comment]
Hey folks—it's been a few years and this hasn't resurfaced. I believe it's been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.
