### ISSUE TITLE
Sophos Premium version, Mailspring Freezes 

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#1212]
Mailspring 1.5.1 and Windows 10 x64

I have already contacted the support of the antivirus. But he didn't seem to be interested in this problem. 

In the settings of Sophos, I have excluded the folders of Mailsprings but after a while, Mailspring freezes. 

With basic protection, there is no problem. Or with the Free version of Sophos. 

When Premium resident protection is enabled, Mailspring freezes (require to close Mailspring) After a while 
The window always responds, I can expand it or reduce it or close it. 
Mailspring does not respond. Nothing happens when I click on a menu, on a message or a button. 

When the resident Shield of the Premium version is disabled. Mailsprings works normally. 

I think it's a problem that Sophos needs to fix. 
I wanted to give this information to your users.

**Comment by bengotow** [comment]
Hey @franco27 thanks for posting this. The fact that it only happens with the Premium version of the Sophos product defintiely makes it sound like it's an incompatibility. I'll see if we can warn users in the future.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this discussion to Discourse:

https://community.getmailspring.com/t/sophos-premium-version-mailspring-freezes/600/1

Please consider joining that community and continuing the discussion there!

@franco27: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration.

We hope to see you on Discourse soon!

-The Mailspring Team
