### ISSUE TITLE
[Feature] Add Sync GPG/PGP Keys to Mailspring Pro

### ISSUE THREAD

**Issue by asddsaz** [Foundry376/Mailspring#1240]
**Feature**: Add sync GPG/PGP Keys to Mailspring Pro. 
**Why**? I personally, find it annoying to sync and renew PGP keys on all devices. This could take that annoyance away. Of course, for security reasons it should be E2E encrypted.

Note: Part of #25

**Comment by bengotow** [comment]
Hey! I think this is a great idea—we would probably want to investigate whether this could be handled by https://keybase.io/ as well. The E2E encryption (and more critically cloud storage) of keys isn't something I'd want to take on lightly! (We currently don't sync mail accounts or passwords through the cloud because the potential for exploit is so high.)

**Comment by marxistvegan** [comment]
Good idea but can we make this a non-pro feature for those of us that are not part of an organization with a budget please.

**Comment by danieltpye** [comment]
Agreed, @marxistvegan. Basic privacy options shouldn't be paywalled.

**Comment by bengotow** [comment]
Merging into #25 so we can track development of this in one place!
