### ISSUE TITLE
Since last version black mode display email with font black on black background

### ISSUE THREAD

**Issue by Lyptik** [Foundry376/Mailspring#1298]
Win10
Mailspring 1.5.4

Since this version in win10 dark theme, writing in mail is displayed in black (on obviously dark grey font) Not very pratical :)

Have a good day.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—there's actually a new release cooking right now that will fix this. Sorry about the hassle, it turns out Chromium changed the way they interpret the `invert()` CSS filter to mean `invert(0%)` (which does nothing) instead of `invert(100%)`, which caused the text to be black on black. Stay tuned! 30 more minutes or so.

**Comment by bengotow** [comment]
Hey! Just a heads up that the fix for this just shipped a few minutes ago—Mailspring will auto-update soon, and you can also download the new version directly here: https://github.com/Foundry376/Mailspring/releases/tag/1.5.5. Thanks!
