### ISSUE TITLE
Blurry elements & no notifications (Windows)

### ISSUE THREAD

**Issue by Javinator9889** [Foundry376/Mailspring#1336]
I switched from *Linux Mint* to *Windows 10* and I was using **Mailspring** in both of them. At **Linux Mint** I have no issue with blurry elements (only the notification badge but it was corrected with the latest update) but in **Windows 10** I feel that the UI is, in general, blurry (I am using the same computer but different OS).

With the following image I think you will notice what I am referring to:
![Windows blurry](https://user-images.githubusercontent.com/25952165/51739519-effa0f00-2091-11e9-82a6-8e888448deb2.png)

Of course, I tried changing the settings for advanced scaling at **Windows 10**
![scaling settings](https://user-images.githubusercontent.com/25952165/51739572-1e77ea00-2092-11e9-826c-83db5e1a0582.png)

but it is still not working.

*Finally*, I noticed that the **application is not notifying** when there is a new mail. I got a dot at the *notification badge* but there is no properly notification sound and/or pop-up message. Screenshots below:
![notifications settings](https://user-images.githubusercontent.com/25952165/51739676-55e69680-2092-11e9-9a0f-203a546e6362.png)

##### Are there any related issues?

#1119  - at this *issue*, also some blurry elements are
described in text messages (**such as fonts**).

#154 - here, with *Ubuntu 17.10* a similar issue with notifications is also described (**no sound**).

I have not found any more similar issues.

##### What operating system are you using?

![Windows version](https://user-images.githubusercontent.com/25952165/51739881-e58c4500-2092-11e9-855c-a2b6eaf5542a.png)

*Windows 10 1809* (`17763.253`)

##### What version of Mailspring are you using?

![Mailspring version](https://user-images.githubusercontent.com/25952165/51739947-0f456c00-2093-11e9-9fe4-431a6e84864e.png)

`1.5.5-b7939d38`

-----------

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

------------

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Mmmm, probably

**Comment by LightSnowDev** [comment]
What scaling do you have? I noticed, that Ubuntu for example only supports 100 and 200%, which leads to direct pixel scaling. Windows supports for example 125%, which leads to some "blurriness", because the Browser has to approximate pixels.

**Comment by Javinator9889** [comment]
Hi

I reinstalled Windows 10 on my computer and seems like notification problem is solved - maybe any Windows internal configuration was corrputed and/or wrong so it was not working.

I am closing this issue as it looks like there is a particular located problem

Thanks all for your support 😄

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/interface-gets-blurry/89

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team
