### ISSUE TITLE
Bad behavior of mailspring when popup after no subject in mail

### ISSUE THREAD

**Issue by Lyptik** [Foundry376/Mailspring#1349]
Mailspring 1.55b-79 / win10

To reproduce the steps :

- New mail (ctrl+n)
- write your mail without a subject
- Send (ctrl+enter)
-> Mailspring will display a pop up asking "are you sure to send a mail with an empty subject?"

-> You want to follow this wise advise from your masters at mailspring so you hit the escape key to remove the popup and fill the line

-> When hitting escape, mailspring sends the mail !

It's funny because that makes me both laugh and being angry at the same time when it happens :)

Anyway it's easy to reproduce and hopefully fix.

Again thanks for the good work :)

Best

**Comment by bengotow** [comment]
Hey! Thanks for filing this—this sounds super frustrating indeed.

I tried reproducing this and I actually haven't been able to yet. I tried turning undo send on and off, tried triggering the send using ctrl+enter and by clicking the button, etc. Just fired up a Windows VM and tested it on Windows 10 to be sure.

The only thing I've found so far is that if you hold down ctrl+enter it sends, opens the `are you sure?` dialog, and ctrl+enter also confirms that dialog (I think just enter does it actually), so the dialog disappears and it sends. But that doesn't sound quite like what you're running in to.

Anything else that I might be able to try?

**Comment by Lyptik** [comment]
Hello Ben,

Strange, here is a more detailed procedure :
[delayed send is on / default when sending a mail it takes 5 seconds with the pop up at the bottom]
Ctrl+n for a new mail
Enter target adress, write some text, omit writing in subject
Ctrl+enter to send
-> pop up appears
If I click on cancel, behavior is normal indeed
If i click on escape, mail is sent (with the delayed loop/animation at the bottom)

Windows 10 + dark theme + gmail shortcuts enabled
Best,

**Comment by CodeMouse92** [comment]
I just tested it on Mailspring 1.8.0 and Ubuntu 20.04, following the reproduction instructions above, and the bug is no longer observable. It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
