### ISSUE TITLE
[Question] does mailspring support an API for translating message contents ?

### ISSUE THREAD

**Issue by Dark-Passenger** [Foundry376/Mailspring#1353]
##### Are there any related issues?

...

##### What operating system are you using?

...

##### What version of Mailspring are you using?

...

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Gmail
...

**Comment by Dark-Passenger** [comment]
I am trying to build such a plugin using the google translate API but I can't see any way to modify the message panes text.

**Comment by bengotow** [comment]
Hey! Hmm - there's a small API for extensions to add things to the message processing pipeline (which formats the HTML for display) here: https://github.com/Foundry376/Mailspring/blob/master/app/src/flux/stores/message-body-processor.es6#L157. That said, those functions can't currently be async because that method call to `extension.formatMessageBody` is missing an `await`. I think it might also be a bad place to insert a network request since the message would be missing that entire time...

Maybe a good solution would be to create one of those `MessageStore.extensions` which can return your translated text from an existing cache, and add a small button to the message UI (you can add a "header" component which will appear inside the message, like the "phishing warning" plugin does: https://github.com/Foundry376/Mailspring/blob/master/app/internal_packages/phishing-detection/lib/main.jsx#L84). The button could make the translation request, and when the result comes back you could update your local cache and call `MessageBodyProcessor.resetCache()` (`MessageBodyProcessor` is in `require('mailspring-exports')`. That would cause your message processor plugin to get re-run and you could return your translation there synchronously.

Good luck! Sounds like a cool plugin 😄
