### ISSUE TITLE
myip.opendns queries by Mailspring

### ISSUE THREAD

**Issue by sud0woodo** [Foundry376/Mailspring#1357]
Operating System: Ubuntu 18.04 64-bit
Mailspring version: 1.5.5-b7939d38

While monitoring my network traffic I noticed myip.opendns[.]com queries that were polling for my external IP-address every minute or so. I tried to look for the opendns query reason in the code but the available code yielded no results. Can someone shine some light on this? I can't seem to think of a good reason to issue these queries, they do not use my primary DNS server either, these are direct queries to 208.67.222.222

**Comment by sud0woodo** [comment]
So this is probably because it is using the `is-online` library as stated in https://github.com/Foundry376/Mailspring/issues/660

But why every minute or so? Also this seems like a rather privacy unfriendly way, it polls for the external address everytime...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I think the problem is that without hitting an actual website it's not possible to tell with 100% confidence whether the network interface works, since captive networks etc. might also be blocking your access to the web. That said, it's odd that this library uses this particular service. It doesn't seem to look at the returned IP address at all...

Honestly we can probably just cut this out of the project and ping our own server to check that the app is online.

**Comment by sud0woodo** [comment]
Thank you for looking into this and responding promptly!

**Comment by working-name** [comment]
@bengotow But why ping that in the first place? It shouldn't happen until there's a problem connecting to an IMAP server. My pihole blocks captive.g.aaplimg.com and now Mailspring thinks it's offline when in fact it can connect to all configured email servers. This is a rather poorly thought-through process that doesn't seem to provide any benefits but only get in the user's way.

**Comment by bengotow** [comment]
Hey folks! I've gone ahead and removed is-online in favor of retrieving "online / offline" state from Mailspring's internal sync processes. When a sync worker is unable to reach one of your mailservers (IMAP or SMTP), you'll get the toast in the bottom left telling you you're offline, and when it's fixed it'll go away. I think this will be a better long-term solution. 

Right now we do not check whether the app can reach id.getmailspring.com. We might want to do that as well since the pro features fail if we're disconnected from that service, but I know some folks prefer to block that domain and the app otherwise works fine without it, so I think it's best to leave it that way for now.

Will run this through the paces this week but should be shipped soon.
