### ISSUE TITLE
Copy/paste password on setup

### ISSUE THREAD

**Issue by RemiDesgrange** [Foundry376/Mailspring#1371]
##### Are there any related issues?

didn't find

##### What operating system are you using?

macos

##### What version of Mailspring are you using?
1.5.6

--

**Bug?**

##### Is this an email sync or connection issue?

nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?

nope

--

Like a lot of people I use password manager. When installing Mailspring and setup the mailspring account, it is not possible to paste email and password. I can live with no email pasting, but password it really anoying.

Thanks.

**Comment by iammeat** [comment]
I also encountered this issue.  It may not seem like much to the developers, but I use 1Password to manage all my secure information.  Not being able to paste a secure password is a showstopper for me, and to be frank it's a terribly unprofessional thing and a massive oversight not to have for logging in to any frequently used software.  It's enough for me to sideline the app and not even try it.

**Comment by alasher** [comment]
I'm not a dev on this project, just a volunteer looking at issues to tackle. I looked into this a little, it appears related to electron/electron#15219. Also it looks like the Electron v4.0.4 docs [here](https://github.com/electron/electron/blob/v4.0.4/docs/api/webview-tag.md) recommend against using Webview, this could be one reason why.

**Comment by bengotow** [comment]
Hey folks - thanks for reporting this. Man, this Electron `<webview>` component really IS unstable - I swear I fixed this a few months ago, but yep, it looks like it's broken in Electron 4 again.

Technically we use a webview for this Mailspring ID screen and the "upgrade to pro" modal because we don't to allow those pages to run as iframes, since that'd allow them to be embedded on web pages in strange ways. (I know the Stripe widget we use on the billing page actually refuses to run if it's in an iframe). Webview is nicely sandboxed, but unfortunately it keeps breaking.

It looks like we can fix this by forwarding the cut/copy/paste commands down in to the webview and that should (hopefully) be pretty bulletproof. Sorry for the hassle - will get this fixed.

Also thanks for the research @alasher!  I hadn't seen that last link with the Webview warning in it.

**Comment by bengotow** [comment]
Ok... should be fixed in 63f231615878bda2405e61a416069e389edeb6bd. Will ship this ASAP. Thanks guys!

**Comment by bengotow** [comment]
Hey! This has been fixed in 1.6.0 which shipped today. The app should auto-update, but you can also get the new version manually from https://getmailspring.com/download. Thanks - enjoy the app!
