### ISSUE TITLE
[Feature Request] Add More Premium Features

### ISSUE THREAD

**Issue by callaginn** [Foundry376/Mailspring#138]
I've looked at your current Premium Accounts...but don't really see any reason I'd ever upgrade. Here's a few features I believe people would find useful in the premium accounts. As far as I know, no email client does this. Maybe similar to CRM?

# Email Parser / Database
**Parse emails when they're imported or received. Here's a rough idea of what it'd do:**

- Find related email threads and split them into separate conversations
- Allow user to perform auto-formatting with a single click. This would run a script that would identify type sizes, fonts, tables, etc and make guesses as to how to rebuild the email with zero inline styles. User would have the option to change these styles as well. The database would then store the clean code.
- Remove all the duplicate email fluff, such as replies...so that emails will flow like nicely formatted instant messages. If needed, this info could be "re-chained" into a nice fluffy email the next time you reply to it.
- Add images, attachments, etc to the database and remove / relink duplicates.

### Custom Stylesheets
I mentioned this in my previous issue #134, but it might make more sense as a premium feature...especially considering that clean code would be much easier to style.

### API Access
- Mailspring Pro could pull from this database as its main source of "clean" information.
- Allow developers and users to access this API
- Allow users to link directly to stored emails, images, and attachments. User would also have the ability to set up allowed users / passwords for this content.

### Github Integration
Allow Github repos to fire off webhooks at this email database, which would put the commit information in a queu. The user could choose which items in the queu should be packaged into a normal email and when to send that email.

Allow user to select Github issues to be sent as a normal email.

**Comment by bengotow** [comment]
Hey! Thanks for the feedback - this actually sounds a lot like Nylas' core business (nylas.com was the company that developed and open-sourced most of Mailspring as Nylas Mail). They sync and sanitize all the email you receive, expose a super great API for it with webhooks, etc. Most of their customers are large companies that want their products to integrate with customer's email accounts, but their developer API is free up to 10 accounts I think.

Gonna close this since we're primarily targeting non-developers with Mailspring, but I've got a big internal Trello board of feature ideas and I'll copy all this on there! Thanks—

**Comment by callaginn** [comment]
Interesting. I'll definitely have to check that out.

Have you ever considered adding the ability to pull data from the Nylas API into Mailspring? I assume this was previously a feature of Nylas Mail. And if you ever created that functionality yourself...you could pull all that data into your database.
