### ISSUE TITLE
Cannot authenticate with Office365

### ISSUE THREAD

**Issue by paulomanrique** [Foundry376/Mailspring#1384]
Today my university account stopped working, saying it cannot authenticate.

Using Mailspring 1.5.7-2057ca30 on Deepin Linux 15.9.1

Log attached
[119125-21484-1hyqkyv.gxsuk.log](https://github.com/Foundry376/Mailspring/files/2903326/119125-21484-1hyqkyv.gxsuk.log)

**Comment by roycem90** [comment]
same error, i also on deepin

**Comment by bengotow** [comment]
Hey! It looks like the IMAP server is rejecting your password - could you try re-connecting the account to Mailspring (from Preferences > Accounts click "Re-authenticate") and see if that does the trick? If re-entering the password resolves the issue definitely let me know, since that'd imply Mailspring forgot it somehow.

**Comment by duoi** [comment]
I'm getting this same issue as of a few days ago, using Ubuntu 18.04.

**Comment by roycem90** [comment]
@bengotow i am not even able to add the account, so its not some issue about mailspring forgetting the password
