### ISSUE TITLE
MacOS resizing window by clicking on title

### ISSUE THREAD

**Issue by jgardiner68** [Foundry376/Mailspring#1388]
##### What operating system are you using?

MacOS Mojave (10.14.3)

##### What version of Mailspring are you using?

Mailspring 1.5.7 but also affects earlier versions

**Feature Request?**

Most native MacOS apps allow one to resize the window by double-clicking on the Window title (the exact behaviour depends on the MacOS dock settings.

On MacOS, Mailspring ignores this interaction (works fine on Linux's gnome and Windows).  Be great to add it and it makes resizing the window much easier.

##### Does this feature exist in another mail client or tool you use?

Very common for native MacOS apps.

**Comment by bengotow** [comment]
Ahh interesting - I'd never noticed this! On macOS, Mailspring uses a totally custom top bar / window chrome so that it can be completely themed. I think that we essentially need to implement this behavior manually, which is a bit of a bummer. I added a bit of code to implement the default macOS behavior (zoom), but we may want to revisit this and see if Electron provides a way to activate the default double-click logic.

**Comment by bengotow** [comment]
Hey! This has been fixed in 1.6.0 which shipped today. The app should auto-update, but you can also get the new version manually from https://getmailspring.com/download. Thanks - enjoy the app!
