### ISSUE TITLE
Request: Max Width in Messages

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1398]
in fully maximized window-mode, messages have a huge margin. Please allow text to fill the entire window. 

![image](https://user-images.githubusercontent.com/6564280/53597924-38f12780-3b58-11e9-82b4-d0807e7d26fa.png)

**Comment by bengotow** [comment]
Hey! Ahh man, there seem to be two schools of thought around this one. There's been a pull request open to change this for a while, but UX research suggests that reading and writing is more difficult when lines of text are more than 15-20 words [1]. Everything from Dropbox Paper to Google Docs to IAWriter places max-widths on documents.

I've always felt it'd be difficult to compose an email 1800px wide, especially since nobody will be receiving it that way. Right now the app goes into a sort of "distraction-free mode" when you maximize the composer -  the window fills the screen but there text editor is still optimized for ideal line length.

That said, this is actually just a minor CSS change. (There's a max-width on `.composer-centered` and `.composer-action-bar-content` that needs to be removed.) I'll see if we can make this an option in the future.

[1] https://ux.stackexchange.com/questions/108801/what-is-the-best-number-of-paragraph-width-for-readability

**Comment by johnyradio** [comment]
You can satisfy everyone. If someone wants narrow, they are free to resize
their window.

You're forcing one way, instead of empowering user choice.

>

**Comment by bengotow** [comment]
Ahh man I searched for this issue again to add this feature (by merging PR #251), but that comment makes me want to do it less. Hrm guess I'll implement it anyway.

**Comment by johnyradio** [comment]
Thx for your attention to my requests!

**Comment by tom--** [comment]
Schools of thought on the legibility of text at different paragraph widths aren't pertinent when the HTML body of the email is not text. HTML emails are in fact used to send all sorts of different content.

For example, here's a test email typical from an app I use. It has an HTML table of data in the body as well as an attachment. In the other email clients that I tested I can make my window wider and see the table nicely. In Mailspring I have to horizontally scroll because the table doesn't fit the available space.

No need to assume that the HTML content is paragraphs of text. Web browsers don't.

![image](https://user-images.githubusercontent.com/1178722/62465337-a2571100-b75c-11e9-8b35-5aa4f05d3b39.png)

**Comment by johnyradio** [comment]
Web browsers let the user resize the window, and the contents reflow to fit the width. Unless the website designer sets a fixed width-- but that's not a restriction put in place by the web-browser. 

I'm happily using Mailbird now, it works the way i like. Good luck with Mailspring!

**Comment by bengotow** [comment]
Hey folks! I can't remember when this got added, but Mailspring now supports both approaches via this option in Preferences > General, and I've actually had it turned off for months and do quite like the composer and messages going full-width. Guess I've come around :) 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/1037212/79529367-1b1fa400-8032-11ea-9488-59a233994e48.png">
