### ISSUE TITLE
Segfault on custom IMAP

### ISSUE THREAD

**Issue by fakeid30** [Foundry376/Mailspring#141]
##### What operating system are you using?
Arch Linux
...
##### What version of Mailspring are you using?
1.0.3
...

**Bug?**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Custom IMAP
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
- Add zoho custom domain
- See issue 
![screenshot_20171012_200108](https://user-images.githubusercontent.com/26362832/31500550-3277bc86-af57-11e7-9899-56ce22409b56.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—can you try downloading 1.0.4 which was just released? (getmailspring.com/download). It includes a handful of fixes for custom IMAP accounts and I /think/ it'll address this.

If not, would it be possible for you to create a new email account on your custom zoho domain that I could use to test this? We actually made some big improvements in 1.0.3 because someone was able to give me a failing email account.

**Comment by fakeid30** [comment]
@bengotow I invited you to register an email in my domain , and sent the invitation to the email that's displayed in your github. Please confirm if you got it.

**Comment by fakeid30** [comment]
@bengotow I seem to have fixed it with using STARTTLS instead of SSL/TLS , I've never used STARTTLS in any other app except for this. So IDK what's going on.
