### ISSUE TITLE
Leaving MailSpring

### ISSUE THREAD

**Issue by KristerV** [Foundry376/Mailspring#1413]
This is not a bug report, rather I'm giving insight from a customers perspective (wanted to buy, but bugs made me decide otherwise) - thus please close this issue when read.

I've had 4 errors now:
1. Fetching emails failing every day now without retrying
2. Sent email never arriving and also disappeared
3. Sent email goes through, but is received completely empty.
4. Email filters just don't work like they're supposed to

As you can guess these kind of problems make the app unusable (though the app is very comfy).

It seems to me like some important code is either not covered with automatic tests or a critical component is badly written. Either way my suggestion is to.. well - figure out how to raise the quality of this app. I would love to pay for this thing if it actually worked.

**Comment by rbbernardino** [comment]
Hello there!
I just started using it today and tested sending/receiving e-mails and only found one bug, but not as severe as yours:
1. I sent an e-mail with two attachments (1xPDF + 1xDOC = 3MB in total) and it remained on "sending..." message for a couple of minutes.
![](https://filedn.com/lmOQJTFtYV1hIVR608T0lBY/github-cmt-images/sending_forever.png)
2. So I tried closing the app and checking if the e-mail has actually being sent and it did!! :heavy_check_mark: 
3. I did a second test, it happened again, but this time, after a few seconds,  I tried clicking on "sent e-mails" and it quickly synced and updated the list. I expected to be a simple and fast process, but anyway, it's fine for now for me.

@KristerV Just for curiosity, a few questions:
- What e-mail provider were you using? I use g-mail.
- What operating system? I use Linux Mint 19.1 (based on Ubuntu)

I wonder if anyone else had this issue recently...

Just a side note: The last time I have tried it was several months ago (or maybe more than one year) and it improved so much!! At that time I think it didn't sync gmail tags/labels, so I quit or was something else.
But now it seems quite good and I hope they keep up updating, so all those issues get resolved.

Cheers!

**Comment by cpacchierotti** [comment]
Indeed, there are some serious issues.

I cannot use Mailspring because, once every 10 minutes, emails randomly disappear (#304). When it works, it keeps syncing the folders, using constantly 30% of my CPU (#435, this seems the bug experienced also by @rbbernardino).

**Comment by itk-union** [comment]
Near to leaving mailspring as well... need to rely on my email client actually showing the entire content of my inbox and not only parts of it. If someone from Mailspring team ever answered on support tickets, I could work with them on finding solutions. But as users have been and I am being completely ignored by their support, there's not much one can do.

**Comment by Bergg** [comment]
Just FYI I have gone back to geary, which has improved over the time I spent using Nylas and then mailspring. I tried Hiri and would've paid for it but it doesn't work on a zimbra server. So I keep checking every now and then what happens here but I have definitely moved on (or back..).

**Comment by cpacchierotti** [comment]
Same here. #304 and #435 are blocking bugs for me.

**Comment by RorixRebel** [comment]
Seems like syncing won't work for me on any of my accounts. 
the dev console seems to show that an attempt was made but nothing happens.

Sending to mailsync ? {type: "wake-workers"}
Sending to mailsync ? {type: "wake-workers"}
Sending to mailsync ? {type: "wake-workers"}

Guess ill have to go back to a web client. Shame cause the app looked nice.

**Comment by KristerV** [comment]
I've since tried thunderbird and other than the clunky UI it works great. Would love mailspring to be built on top of that instead :D

**Comment by bengotow** [comment]
Hey folks! Thanks for filing this - I think there are a few separate issues being discussed here. Mailspring doesn't support email accounts that use "virtual folders". With a virtual folders setup, the mail provider reports that the same message exists in several folders at once (creating sort of a poor mans Gmail labels feature). This confuses Mailspring and the messages will flicker #304 and it'll sit there re-syncing your mailbox forever #435. I'll probably fix it at some point, but it'll require quite a lot of work and it doesn't apply to any of the top mail providers.

I think we fixed #3 above about a year ago—if you're still seeing messages being sent empty definitely file a new issue!

Re: the sending banner @rbbernardino, Mailspring actually runs some post-send operations to prepare read receipts and link tracking, so if you have those features enabled you'll see the "Sending Message..." banner for a few seconds AFTER the message has been sent. The sound doesn't play until the entire process completes. If you turn off link+open tracking in your emails they'll send faster.

Will look in to the email filters - I don't think I've seen any bug reports there in a while actually, but that code is definitely not the best. I believe it's been mostly left alone since 2015.

At any rate, I appreciate you all trying out the app and I'm sorry it hasn't worked well for you! Honestly it's hard to beat Thunderbird in terms of broad email provider support because they've spent several decades fixing the long tail of provider issues, and that may continue to be your best bet for a while. Other mail clients have taken the approach of only supporting specific providers (Gmail, O365, iCloud, and a few more), and I think that would have been a good route to take Mailspring as well. In the next release, I'm adding some instrumentation so I can tell when sync is not working well for a particular IMAP server, and I think in an upcoming release the app will refuse to connect accounts that are known to cause issues (like the virtual folders scenario.)

**Comment by therecluse26** [comment]
@bengotow which of the top mail providers does this not apply to? It's happened for me on both Gmail and Outlook mailboxes... it's hard to think of two mail providers with a larger market share. It seems like you have enough customers who have left or ready to leave over this to justify your addressing of the issue. There are plenty of other email clients that don't have this problem, many of which are open source... maybe you could gain some insights from how those are handling this?

**Comment by kdekooter** [comment]
@bengotow AFAIK I am not using "virtual folders" (Dovecot IMAP) but I am still suffering from #304.

**Comment by itk-union** [comment]
@bengotow pretty sure my iredmail doesn't use "virtual folders" either, based on and running with Dovecot 2.2.22 with kind of very-standard IMAP options. Anyhow, same for me in regards of #304 . If that helps.

**Comment by drjimmie1976** [comment]
> At any rate, I appreciate you all trying out the app and I'm sorry it hasn't worked well for you! Honestly it's hard to beat Thunderbird in terms of broad email provider support because they've spent several decades fixing the long tail of provider issues, and that may continue to be your best bet for a while. Other mail clients have taken the approach of only supporting specific providers (Gmail, O365, iCloud, and a few more), and I think that would have been a good route to take Mailspring as well. In the next release, I'm adding some instrumentation so I can tell when sync is not working well for a particular IMAP server, and I think in an upcoming release the app will refuse to connect accounts that are known to cause issues (like the virtual folders scenario.)

@bengotow thanks for reply and your work on what looks like a great product. New user, keen to support the project, but the CPU issue #435  is slowing down my machine a lot. Sounds like this isn't an issue with Gmail IMAP, could you confirm? (I'm currently using 3x Gmail IMAP and one other)
