### ISSUE TITLE
How to Select Sync Folders?

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1423]
Currently, mailspring syncs every folder. Including Trash, Spam, and other folders i don't NEED to sync (until i manually open them). 

How to prevent sync on certain folders?

![image](https://user-images.githubusercontent.com/6564280/54556105-61a95780-4975-11e9-8950-5a0e31237d11.png)

**Comment by johnyradio** [comment]
This causes sync to take too long, and consumes my internet bandwidth. Plz allow to select sync folders!

**Comment by bengotow** [comment]
Hey! Yep the app syncs all folders and there's no way to ignore certain folders. It won't sync message bodies in your spam or trash folders though (which typically makes things a bit lighter.) If you're using gmail, you may want to disable folders from IMAP (the UI is shown here: https://superuser.com/questions/509036/) until we add support for selective sync!

**Comment by bengotow** [comment]
Merging in to #888

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/per-account-per-folder-sync-scan-cache-settings/474

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@johnyradio: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
