### ISSUE TITLE
Read receipts have stopped working

### ISSUE THREAD

**Issue by avarayr** [Foundry376/Mailspring#1440]
##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?

1.6.0-10f5c95c

**Bug?**

Read receipts have stopped working. Not working neither on Gmail nor on custom IMAP.
I've looked at the original raw message and it does not contain the read receipt tracker image.
The "eye" icon is next to the sent messages, but it never turns active. 

Tried with and without VPN. 
Mailspring is updated to the latest version.
Read receipts are turned on when sending the message.
**I do have a subscription.**

##### Is this an email sync or connection issue?
Sync, I guess?

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Comment by bengotow** [comment]
Hey! This is super interesting - I'll check this out today and figure out what's going on. There haven't been any changes recently that I can think of that might impact this. 

It's a little tricky to debug because Mailspring actually tells your SMTP server to deliver a copy of the message with the tracking pixel, and then saves a copy into your Sent folder without the tracking pixel (so you can't trigger it yourself by viewing the thread, even in another mail client.), so it's normal not to see the pixel on your own. It looks like there haven't been any errors or issues on the backend, but it's possible that the message has been viewed and the app hasn't synced down the tracking event yet. 

Could you do me a favor and open Mailspring and go to Developer > Show Mailsync Logs in the app's menu? If you look in the mailsync-****.log files in that folder they may contain errors on the `[metadata]` thread which would be super helpful to see. There's one log file for each of your accounts so you may have to look at a few of them.

**Comment by avarayr** [comment]
@bengotow Hi, thanks for getting back to me!
Here's the log of only lines containing [metadata] I filtered out.
[mailsync-a5297e6c.log](https://github.com/Foundry376/Mailspring/files/3023901/mailsync-a5297e6c.log)

**Comment by bengotow** [comment]
Hey! Thank you - this is super interesting. It looks like your account is requesting "deltas" (the stream of open / read tracking events), but the imap hostname (the `ih=` param) is missing from the request. We added that recently to gather a bit of information about what email providers folks were using with Mailspring (there aren't any other metrics collected from the app, but it's useful to know what fraction of users are on a particular service like Gmail). I'm not sure why it's missing, but we can probably handle this on the server and get this fixed ASAP.

**Comment by bengotow** [comment]
Hey @avarayr — I deployed a fix for this about 30 min ago and read receipts, link tracking, etc. should be updating for you again now. Sorry for the hassle! Still investigating why the imap host param wasn't being populated in that request. Cheers!

**Comment by avarayr** [comment]
@bengotow I have just received 500+ notifications in bulk of read receipts.
It works now, thanks haha!

**Comment by Kareninsprint** [comment]
my tracking for read receipts and links is not working properly...no re-installs helped, attaching the mailsync file.
[mailsync-3a081d07.log](https://github.com/Foundry376/Mailspring/files/10726089/mailsync-3a081d07.log)
