### ISSUE TITLE
"Received" header (Helo/Ehlo) with computer name and IP address

### ISSUE THREAD

**Issue by mozhack** [Foundry376/Mailspring#1461]
##### Are there any related issues?

No

##### What operating system are you using?

MacOS

##### What version of Mailspring are you using?

Latest

--

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Not sure

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

Hello,

I noticed that the message is sent with the Receiver header attached. The problem is that is sent with my computer name and IPv6 address.

Is there anyway to change that?

Please check the screenshot.

Thanks

![mailspring](https://user-images.githubusercontent.com/30222128/55767242-f59baa00-5a6f-11e9-8741-4b8aae79cca1.jpg)

**Comment by bengotow** [comment]
Hey! Unfortunately this header is assembled by the SMTP server when Maispring delivers the message. (Mailspring doesn't send your IP, Gmail looks at where the SMTP request came from and adds your external IP address. That's why it's a global address and not 192.168.x.x or 127.0.x.x). We might be able to spoof the computer name, but I'm not sure there's much we can do to remove it. 

Going to go ahead and close this but if anyone knows more about this please do let me know!
