### ISSUE TITLE
"Run With Debug Flags" makes Mailspring crash

### ISSUE THREAD

**Issue by paulgaumer** [Foundry376/Mailspring#1466]
##### Are there any related issues?

Not that I could find

##### What operating system are you using?

macOS Mojave 10.14.4

##### What version of Mailspring are you using?

v1.6.1

--

**Bug?**

##### Is this an email sync or connection issue?

Every time I click on `Developer > Run With Debug Flags`, Mailspring crashes, closes completely and restarts like a new install, asking me to add a new account.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Every time I click on `Developer > Run With Debug Flags`

--

My goal is to create a new theme, but I can't go further due to this behavior.

**Comment by sasokess** [comment]
the exact same thing happened to me when I clicked on "Run With Debug Flags."

If you want to open it again without running through the setup, click on it again and your old window will appear.

**Comment by bengotow** [comment]
Hey folks—I think this was changed a while back and Mailspring looks in a separate location for the email account config / database when it's in developer mode so that you can add accounts for testing that you don't use normally. It's a bit of a pain configuring the app all over again in developer mode, though. Maybe it'd make sense for that account isolation to be a separate option!
