### ISSUE TITLE
Invalid future date displayed for received emails

### ISSUE THREAD

**Issue by skojic** [Foundry376/Mailspring#1472]
##### Are there any related issues?

None, I haven't found anything similar.

...

##### What operating system are you using?

Mac OS Mojave 10.14.4
...

##### What version of Mailspring are you using?

Version 1.6.1 (1.6.1)

--

**Bug?**

G-Suite email account is added, and just from one sender I am receiving emails with future dates, and I cannot even delete them.  But When i get into g-suite web email everything correctly is displayed. I am attaching picture for easier debugging.

![Mailspring-bug](https://user-images.githubusercontent.com/28847453/56571146-9e8fec00-65bc-11e9-8e96-71ba5d1d7e35.jpg)

##### Is this an email sync or connection issue?

I would say that it's more related to syncing

[logs.zip](https://github.com/Foundry376/Mailspring/files/3106906/logs.zip)

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Gmail - G-Suite account
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Nothing that I could think of, mails are ordinary plain text.

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes by default, It's kind of the purpose of the email to have accurate date and time stamps of the messages :)
...

**Comment by skojic** [comment]
Uploading files and images for easier debugging

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this one is pretty interesting... Mailspring displays the timestamps that are encoded in the email, and only uses the date that the message was received by your mail server (Gmail, etc.) as a fallback. That is usually preferable for displaying a conversation because delivery delays, etc. don't cause the messages to appear out of order. That said, if a sender changes their computer time to be way in the future and sends you a message, Mailspring would say it was received in the future rather than using the time it hit the mailserver.

I think in the future we probably want to take the older of the two dates and use that, have not seen it be off by this much before!
