### ISSUE TITLE
Activity shows emails have been read even if they were not delivered

### ISSUE THREAD

**Issue by JKAnderson409** [Foundry376/Mailspring#1494]
##### What operating system are you using?

MacOS Mojave 10.14.4

##### What version of Mailspring are you using?

1.6.1

**Bug?**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Outlook

##### Is the issue reproducible with a particular attachment, message, signature, etc?

To reproduce:

Send emails to a non-existent email address and receive a response from postmaster@outlook.com indicating that the email was not delivered. The activity log shows that the undelivered email has been opened.

**Comment by bengotow** [comment]
Hey @JKAnderson409  - thanks for reporting this! I tried reproducing this by sending a tracked message to a bogus email address at Outlook.com, and I was able to reproduce the issue!

For some reason, when the mail is redirected back to you and displayed in Mailspring, the app doesn't realize that the tracking pixel in the email is one of it's own, and it attempts to load the image essentially triggering it's own open-tracking mechanism. We can almost definitely get this fixed in the next release, so I'll take a look! Thanks for reporting this 🙏

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
