### ISSUE TITLE
Unable to drap and drop attachments into messages

### ISSUE THREAD

**Issue by timdorr** [Foundry376/Mailspring#1534]
##### What operating system are you using?

macOS 10.14.5	

##### What version of Mailspring are you using?

1.6.2 (This bug doesn't exist in prior versions)

**Bug?**

##### Is the issue reproducible with a particular attachment, message, signature, etc?

This happens with any attachment type, including images and non-image files.

Here's a GIF of what I see:

![Jun-19-2019 15-04-18](https://user-images.githubusercontent.com/17882/59793159-dc9b4a80-92a3-11e9-9922-dea9c7bec7a3.gif)

As you can see, the drop overlay remains and the attachment doesn't show up in the document. I can still click around and type behind the overlay. Retrying the drag and drop doesn't remove the overlay or attach the file.

**Comment by paulcosmos** [comment]
Can confirm I'm also having this issue on Mac 10.14.4 since upgrading to 1.6.2 .

**Comment by mkusinski** [comment]
The same on Windows 10. Mailspring 1.6.2

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this—I've been able to narrow this down and it'll be fixed in the next release (tomorrow). In the meantime the trick appears to be to drop the file on the text of the message and not in the whitespace around it. I think we were doing testing with long test messages so this slipped by the review for 1.6.2.

**Comment by timdorr** [comment]
All fixed in 1.6.3. Thanks!
