### ISSUE TITLE
[Feature Request] Grammarly chrome extension from station

### ISSUE THREAD

**Issue by rapatel0** [Foundry376/Mailspring#1540]
**Feature Request?**
The single most used extension in my workflow is grammarly. I would love to have that integrations. Recently "station App published their chrome extension api and have added Grammarly, as a supported extension to their application. StationApp also is an electron application and it stands to reason grammarly would also work if integrated into mailspring. There might also be significant additional improvements by integrating chrome extensions.

https://github.com/getstation/electron-chrome-extension

##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment]
Hey! I definitely agree Grammarly would be nice. electron-chrome-extension looks pretty interesting, I'll take a look and see how they've implemented context security in Electron. This hasn't been possible for a long time because allowing extensions to run in Electron requires patching a bunch of stuff and could give randomly downloaded extension code access to your entire filesystem, etc.

We probably won't add Grammarly support by default because it sends all of your message content to the cloud for processing, but I agree it'd be a super nice plugin to have. Going to merge this in to #1402  but I'll follow up after digging in to electron-chrome-extension a bit more.

**Comment by bengotow** [comment]
Hey folks! I posted about `electron-chrome-extension` in the Electron maintainers slack channel and it sounds like Electron is working on chrome extension support that will offer stronger security isolation than what is provided by that module. (Security and NodeJS isolation is a huge concern because electron-chrome-extension allows third party JavaScript to be downloaded and run on the fly, and JavaScript running in Electron can have much greater access to your system than JavaScript running on a typical web page if it's not sandboxed properly.)

I think we'll revisit this when extension support lands in Electron itself. Stay tuned!

**Comment by bengotow** [comment]
Merging into #1402

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/grammar-check-tool-integration/329

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
