### ISSUE TITLE
No way to open ics file anymore

### ISSUE THREAD

**Issue by Pajn** [Foundry376/Mailspring#1547]
##### Are there any related issues?

There are ics related issues, but I could not find this specific one.

##### What operating system are you using?

Ubuntu 19.04

##### What version of Mailspring are you using?

1.6.2

**Bug?**

As ics files gets parsed and time and date is displayed (which is awesome) I no longer have the option to open the file itself so that it gets imported into my calender.

Previously I double clicked on the "Unknown Attachment" and it got imported.

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes, any ics file that gets parsed with the new event viewer

--

**Feature Request?**

I would like some way to access the ics file and open or maybe downloading it. Maybe the standard attachment viewer should be displayed as well or maybe open and download buttons should be added to the event viewer.

##### Does this feature exist in another mail client or tool you use?

Yes

**Comment by bengotow** [comment]
Hey! Ahh you're totally right. I'll see if we can add this back until the full calendar integration is ready to go. On many platforms (Gmail, iCloud, etc.), receiving the email automatically syncs it to your calendar, but I think that's a provider-specific behavior and not part of a standard. Eventually Mailspring will do it for you, but not until we launch a full calendar.

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Comment by didrip** [comment]
Currently running 1.6.3-134a0e55 (on Windows) and I see no option to download the file.

There is a "download" icon on top right of the `ics` event preview however it opens the default app rather than downloading the actual event. I would like to be able to download the event file because I sometimes need to manually import it in different programs.

*The default app is Windows Calendar but I actually use another one (MineTime). One can change *.ics association in Control Panel > Default Programs > "Associate a file type or protocol with a program"*
