### ISSUE TITLE
Annoying Update Notification

### ISSUE THREAD

**Issue by anieruddha** [Foundry376/Mailspring#1557]
##### What operating system are you using?

Ubuntu 16.04

##### What version of Mailspring are you using?

1.6.2

**Feature Request?**

Please check screenshot. 

![image](https://user-images.githubusercontent.com/4935674/60525414-ea919800-9cb3-11e9-95af-f9655b6c5956.png)

This update notification box is annoying.  There should be way to at-lease close this box.

**Comment by bengotow** [comment]
Hey! Yeah I'm sorry this is so annoying... Honestly my goal as the sole maintainer is to get everyone off of old versions on Linux as quickly as possible, because if you were to email support or file an issue it'd take me manual effort / debugging before I'd realize that you were reporting a bug that was already fixed. 

If you use the Snapcraft release these don't appear (the app autoupdates on it's own!) That may be a good solution.
