### ISSUE TITLE
Opening attachment

### ISSUE THREAD

**Issue by JunnanZ** [Foundry376/Mailspring#156]
##### Are there any related issues?

No
##### What operating system are you using?
Arch Linux
##### What version of Mailspring are you using?
1.0.4

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Double clicking an attachment, e.g., a pdf file, opens it but will halt the mailspring interface unless I close the attachment window.

--

**Feature Request?**
If I choose to download the attachment, it will automatically open the containing folder. I know it's about personal preference, but is there any easy way to prevent this?

##### Does this feature exist in another mail client or tool you use?
I guess so

**Comment by bengotow** [comment]
I think this is an issue with electron and xdg-open. If you’re interested in contributing, dogging in to this would be really helpful!

**Comment by mattlyons0** [comment]
Fairly sure that PR I submitted upstream should fix the interface hang. It can also hang when opening the file manager (with some file managers, nemo for example), this is also fixed in the upstream PR.

I could not verify this however, I am running into a issue when running Mailspring with a custom electron version. I've tried the 1.7.x branch and master. Getting ```/tmp/electron/out/R/electron[11545]: ../../vendor/node/src/async-wrap.cc:399:void node::SetupHooks(const FunctionCallbackInfo<v8::Value> &): Assertion `env->async_hooks_init_function().IsEmpty()' failed.``` where /tmp/electron/out is my custom electron build. Its an error within Node.js so it might be something in the electron repo that is just unreleased (or something wrong with my own dev build).

I have verified that my electron app no longer hangs when calling `electron.shell.showItemInFolder` and `electron.shell.OpenItem` using the build with my PR, so mailspring reasonably shouldn't either.

**Comment by mattlyons0** [comment]
As for the feature request, I agree this is annoying and am writing a PR to make opening the directory configurable

**Comment by bengotow** [comment]
Hey—congrats on the contribution to electron/electron! That upstream change looks good to me.  Would love to pull that in once it's merged into a release. I think it'll take a fair bit of QA to make sure Mailspring runs on Electron 1.8 (usually when they do a major Chromium upgrade a few tiny things break...)

Will take a look at the PR! This is definitely tricky - I think the current "open the folder once, and then not again" thing was an effort to compromise, but it's a bit awkward.
