### ISSUE TITLE
Not possible to navigate sidebar / message list column via hotkeys alone

### ISSUE THREAD

**Issue by ghost** [Foundry376/Mailspring#1560]
Tab as well as Shift+Tab should cycle through the GUI controls. More precisely, it should allow you to easily reach the left sidebar which can apparently only be accessed by using the mouse?????? This is absolutely horrible, and just adding a few hotkeys to quickly switch to a few folders is no excuse. Blaming electron for such difficulties won't help either...

Furthermore, you can not open a draft from the drafts-folder via a hotkey, neither is it possible to jump into an already written one from the inbox. The only thing you *can* do is to define a hotkey for the initial reply, but you cannot access the editor window of that reply later on if you ever leave it.

But it gets better: Even if you're inside the editor window, you can't get out of it. There's a hotkey setting called something like "pop-sheet" in the config-file, which is apparently responsible for that, however it doesn't do anything for me. Neither does the "Open Mail" hotkey when trying to jump into the editor.

Another issue I noticed is that you can't press Alt+<key> to quickly access the drop-down menus below the title bar, which is pretty much a standard functionality in all apps. I don't consider this feature to be essential to the general workflow of Mailspring, but it's still something one would expect.

##### Are there any related issues?
Nope. Unfortunately...

##### What operating system are you using?

Manjaro Linux

##### What version of Mailspring are you using?

Updated today, so the latest one as of July 3rd.

**Bug?**

##### Is this an email sync or connection issue?

Nope, just reasonably unacceptable behaviour. The least thing I expect a a commercially sold mail client to do is to offer hotkey coverage for the most basic tasks.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Doesn't have anything to do with that.

--

##### Does this feature exist in another mail client or tool you used in the past?

Yes. In all of them.

Sorry for coming off kind of rude, I'm just a bit pissed off currently... Don't take it the wrong way. It's still a great mail client and I love the rest of it, but not being able to control the most essential stuff on a keyboard is just annoying. Mailspring is the only modern looking, and properly dark themed mail client I found on Linux, so I really don't want it to be a weak tool for keyboard-ninjas like me ;)

Edit: I'll look into automating the missing behaviour with AutoKey and offer my script here in case it should work. It can probably be ported to Autohotkey on Windows fairly easily, if someone wants to do it.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—this isn't a development priority for the near future but I think we'd definitely accept a pull request improving keyboard navigation of the UI! 

I use the app mostly via the keyboard personally, but I use the search hotkey a lot, up/down arrows to move through mail and the space bar to read the thread + "L" to label and triage messages. There's been a fair bit of community interest in building a "jump bar" that lets you quickly jump to a label or folder, and that'd probably be a nicer experience than implementing keyboard navigation of the sidebar. 

If you're interested in contributing, I think a good start to this would be going through and ensuring that there's a `tabIndex` on all of the interactable controls. That, combined with some CSS that ensures the tab-focused element is outlined, would allow you to navigate all the buttons via tab. I know we specifically turned that off for the composer though, because folks were super annoyed that it tabbed across every button in the toolbar instead of jumping between To/Cc/Bcc/Subject/Body as it does now.

**Comment by ghostrider3333** [comment]
If I understand correctly, a quick-and-dirty fix (not that I would submit it) would be to just re-add the tabIndex to the sidebar controls? Or would there be something else preventing me from tabbing over its controls? If I remember correctly then I couldn't tab anywhere except for the composer, so I guess you took the easy way and just removed *all* tabIndex rules except for the few elements in there?

**Comment by ghostrider3333** [comment]
Actually... A fix should be fairly simply by using this JQuery formula:

document.getElementsByClassName("name")[numberIndicatingSidebarEntry].click()

I can easily traverse through the sidebar nodes that way.

**Comment by ghostrider3333** [comment]
I managed to get somewhat convenient keyboard-navigation on the sidebar by injecting this code in chrome debugger:

`__counterForSidebarFolders = 0;
__nameList = document.getElementsByClassName('name')

document.addEventListener("keydown", event => {
    moveDown = false;
    moveUp = false;

    if (event.ctrlKey && event.shiftKey && event.keyCode == 9) moveUp = true;
    else if (event.ctrlKey && event.keyCode == 9) moveDown = true;

    console.log(moveDown);
    console.log(moveUp);

    //Only change counter if an actual move-event happens
    if (moveDown || moveUp) {
        debugger
        [...document.getElementsByClassName('name')].forEach((item, index) => {
                selectedItem = document.getElementsByClassName("selected item");
                selectedItemIndex = moveDown ? selectedItem.length - 1 : 0;
                
                if (item == selectedItem[selectedItemIndex].getElementsByClassName("name")[0])
                    __counterForSidebarFolders = index;
            }
        )
    }

    //The actual keyboard-navigation
    if(moveUp && __counterForSidebarFolders > -1) {
        __counterForSidebarFolders--
        __nameList[__counterForSidebarFolders].click()
    }
    else if(moveDown && __counterForSidebarFolders < __nameList.length)
    {
        __counterForSidebarFolders++
        __nameList[__counterForSidebarFolders].click()
    }
})
`
Just in case someone else needs a quickfix... I'm currently looking into how to permanently modify the electron package (as I really doubt the code above fullfills the quality standards of Mailspring, so I'll not attempt a pull request ;)

**Comment by ghostrider3333** [comment]
Took me some time, but I figured out the solution was to edit `chrome-extension.js` inside the electron.asar file. I added this code at the buttom:

```
app.on('browser-window-focus', function (event, bWindow) {
  bWindow.webContents.executeJavaScript(`
  __counterForSidebarFolders = 0;
  __nameList = document.getElementsByClassName('name');
  
  document.addEventListener("keydown", event => {
      moveDown = false;
      moveUp = false;
  
      if (event.ctrlKey && event.shiftKey && event.keyCode == 9) moveUp = true;
      else if (event.ctrlKey && event.keyCode == 9) moveDown = true;
  
      console.log(moveDown);
      console.log(moveUp);
  
      //Only change counter if an actual move-event happens
      if (moveDown || moveUp) {
  
          //The below code is necessary to always start navigation at the already selected folder
          [...document.getElementsByClassName('name')].forEach((item, index) => {
                  selectedItem = document.getElementsByClassName("selected item");
                  selectedItemIndex = moveDown ? selectedItem.length - 1 : 0;
                  
                  if (item == selectedItem[selectedItemIndex].getElementsByClassName("name")[0])
                      __counterForSidebarFolders = index;
              }
          )
      }
  
      //The actual keyboard-navigation...
      if(moveUp && __counterForSidebarFolders > -1) {
          __counterForSidebarFolders--;
          __nameList[__counterForSidebarFolders].click();
      }
      else if(moveDown && __counterForSidebarFolders < __nameList.length)
      {
          __counterForSidebarFolders++;
          __nameList[__counterForSidebarFolders].click();
      }
  })  
  `)
```

For convencience I'll add the re-packed electron.asar, just replace it with mine. The location depends on your OS, on linux a simple `whereis mailspring` did the job. On Windows I don't know, but you can check in your Program Files and Application Data folders or follow this guide:

https://www.contextis.com/en/blog/basic-electron-framework-exploitation

[keyboard-navigation-fix.zip](https://github.com/Foundry376/Mailspring/files/3363974/keyboard-navigation-fix.zip)

**Comment by ghostrider3333** [comment]
I wrote a bash file myself, mostly for personal usage but in case Mailspring's `electron.asar` archive in in `/usr/share/mailspring/resources` it should work for you as well:

[mailspring-update-fix.zip](https://github.com/Foundry376/Mailspring/files/3364642/mailspring-update-fix.zip)

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/not-possible-to-navigate-sidebar-message-list-column-via-hotkeys-alone/928

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
