### ISSUE TITLE
Download-Version // Github Version

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#1562]
Hello,
that's actually more of a question, but I'm not sure where else to ask her... If this is not the right place, sorry!

**Here is the question:** How much do the versions of Mailspring available on Github differ from the download version on getmailspring.com?

**Or to put it another way:** with what time interval does the download version correspond to the changelog status on Github?

It seems as if the downloads on getmailspring.com are not up to date.

It would be nice if the version status would be displayed at this point during the download, maybe even in the file name.

Many thanks and many greetings
Timo

**Comment by bengotow** [comment]
Hey! They are the same - the site actually redirects to the latest Github release. Sometimes the changelog includes the notes about the "next release", but github releases and the download site should match. (We actually serve the downloads from GitHub because they host them for free, and it was costing a lot to serve them from S3!)
