### ISSUE TITLE
IMAP-only account

### ISSUE THREAD

**Issue by tom--** [Foundry376/Mailspring#1569]
##### Are there any related issues?

Not that I could find

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

1.6.3-134a0e55

--

**Bug?**

I want to access my local Dovecot IMAP server from Mailspring. It is used only for archives and hence does not involve outgoing mail.

The "Set up Account" wizard requires specs for Outgoing Mail (SMTP) otherwise the "Connect Account" button is disabled so I cannot add the account.

If I add specs for a nonexistent SMTP server, I get a Connection Error and Mailspring refuses to add the account. (The logs show that the IMAP connection is fine and SMTP connection refused, as expected.)

How can I add a connection to the IMAP server?

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes.

**Comment by bengotow** [comment]
Merging in to #1575

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/make-smtp-or-imap-optional-read-only-or-send-only-accounts/134

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
