### ISSUE TITLE
Mailspring doesn't add fully the original message when reply

### ISSUE THREAD

**Issue by Bluewine** [Foundry376/Mailspring#1580]
Ubuntu 19.04
Mailspring ver: 1.6.3-134a0e55

Problem:
When you replay a message with attachments, the original message cited below doesn't include the attached files and the rest of the following messages. The cited message is only a part of the original message.

How to reproduce:
1. Receive any mail with any images in the mail body (attachment) between two paraph.
2. Reply that received message and expand the original message included below (the ··· simbol), using Mailspring.
3. You can see that the original message cited is not fully added below.

This issue occur in every replies with messages containing images in the body of the mail between text (paraph).

**Comment by CodeMouse92** [comment]
Regarding attachments, Mailspring's behavior is fairly in line with other mail clients. The behavior regarding older replies being removed is likely because most clients and services show message history already, thus making full inline history more annoying than anything.

If this is still something you want to see implemented in Mailspring, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com). (This might also be a good candidate for a plugin.)

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
