### ISSUE TITLE
Not possible to use software without registration

### ISSUE THREAD

**Issue by rojaster** [Foundry376/Mailspring#1585]
##### Are there any related issues?
No

...

##### What operating system are you using?
Whatever, It doesn't have a correlation with OS I am using.
...

##### What version of Mailspring are you using?
The latest. I downloaded from the site. 
...

--

**Bug?**

##### Is this an email sync or connection issue?
Nope

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Still No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yeap.

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Yes.
I don't want to create Mailspring account to try the FREE version of your software. it's really bad!
I would appreciate if you could disable the feature that obligates me to create Mailspring account by default. I find it not user-friendly. 
...

**Comment by xylo** [comment]
Yes.  That's definitely a no-go.  I've never seen a mail client that forces users to use a proprietary cloud service.  That's just not trustworthy, independent from what is actually stored in the cloud.

Please remove all dependencies to proprietary services from the core application or move them to optional add-ons.

**Comment by metal450** [comment]
Agreed.  Shame because Mailspring looks really promising, but of all the email clients I've tried, I've never even heard of one like this: demand you sign up for their service just to download e-mails from your *own* service.

**Comment by bengotow** [comment]
Yep! This is true. You're welcome to use whatever email / pass combo you like - there's no verification so it can be fake. We probably should have made it a username / pass instead of an email / pass so folks felt more free to make something up.

Ironically, the registration process has recently really helped the app comply with privacy legislation - since you have an account and everything is associated with it, we can also delete it all for you and there is no trace of your data anywhere.

At any rate, I totally understand your sentiment! Just keep in mind that this sign up flow is optimized for eventual paying pro customers, not folks who will use the app for free and are not interested in the fancy business features. I love that lots of non-paying folks use Mailspring, but you're sort of a guest in a mall. Everyone is welcome but it's designed for shopping and if you're not shopping nobody cares what you think of the stores.

(Sorry if that sounds harsh! 😬  For better or worse, being a stickler about optimizing for the eventual pro conversion (and drip marketing along the way, etc.) pays me enough to continue work on Mailspring, so it's a bit of a win-win I think.) 

Related: #33!

Related: #11

**Comment by metal450** [comment]
>>guests in a mall

I would be happy to pay for the software & support its development, if it were possible to use without requiring it to talk to 3rd party servers (i.e. anything other than the actual mail service I want it to talk to).  Even if there are business features which require a cloud, that doesn't mean it wouldn't be possible to allow users who don't want cloud services to still pay & contribute toward its development.  So I don't really see this as an argument for "logins are needed."  Logins -> business features, but you could still have a non-cloud paid model & avoid this requirement (which I'm absolutely certain turns some perspective users away - i.e. myself being one).

>>We probably should have made it a username / pass instead of an email / pass so folks felt more free to make something up.

That still doesn't address my concerns here.  The issue is that you require an account at all, not that it's via email vs username.

>>the registration process has recently really helped the app comply with privacy legislation - since you have an account and everything is associated with it, we can also delete it all for you and there is no trace of your data anywhere.

...If the app wasn't phoning home, there would be no data to delete in the first place.  The very fact that there even is any data to delete is precisely/exactly my issue :P
