### ISSUE TITLE
Feature request- Provide the geo data of the IP in read receipts

### ISSUE THREAD

**Issue by Stephane-T** [Foundry376/Mailspring#1590]
Hello Mailspring team,

Is it possible to get geographic information of the reader in read receipt ? 

Just to know in which country the reader is situated at the time he's reading the email. This should be easy to make as you get his IP when he load the 1px image.

I don't know if any other mail software does that, but that's definitely a very interesting feature to get.

**Comment by Simon-JB** [comment]
Superhuman used to do that and they got a lot of backlash for it recently :
https://mikeindustries.com/blog/archive/2019/06/superhuman-is-spying-on-you

Personally I find this kind of feature very invasive. Read receipts are already sketchy in their implementation (as 1) it is not clear to the user that they are tracked and what information is collected, 2) it is not possible to prevent it without disabling all images in all messages). Adding localization into the mix...Granted, localization by IP address is not extremely precise, but I see absolutely no good business reason why you would want to check in what country I am in when I read one of your emails.
And as a user, I see no reason to give anyone this information. 

I'd rather they spent their research and development time finding a responsible way to implement read receipts and promote a common standard with other email customers (how about warning the user by default ?) rather than add even more information into the mix, but to each its own I guess :)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - unfortunately(?) the world is trending toward greater privacy concerns and we definitely can't implement something like this. I agree it'd be super cool and feasible from a technical standpoint, but lots of folks regard this feature as sketchy already.
