### ISSUE TITLE
Searching mails using the default settings shows mails on trash as well

### ISSUE THREAD

**Issue by smartins** [Foundry376/Mailspring#1605]
When doing a mail search (3 different Gmail accounts) it shows all emails found including the ones on Trash. This is not how the default search on gmail works as it doesn't show emails on Trash by default.

Any way of doing a search on all mails except the ones on trash? Ideally having this as the default search as searching on trash can be done with in:trash if needed.

Windows 10, version 16.3-134a0e55

**Comment by bengotow** [comment]
Wow you're right about this, I'm not sure how I never noticed. I'll see if we can get this fixed in one of the upcoming releases.

**Comment by bengotow** [comment]
Hey! It turned out that we needed to add support for  NOT queries (eg: "bla NOT in:trash") to the search bar, but I've made that change and also modified the bar so that all queries that do not explicitly mention `in:trash` or `in:spam` are assumed to exclude trash and spam. 

Will ship this this week!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
