### ISSUE TITLE
Reading Option : Auto-Expand All Emails of a Conversation

### ISSUE THREAD

**Issue by Lonniebiz** [Foundry376/Mailspring#1608]
It always confuses me if the emails are not expanded in a multiple reply conversation, so I'd like them to be expanded by default. I see no option for this.

![readingOptions](https://user-images.githubusercontent.com/151919/62791172-4230d980-ba92-11e9-866a-9837d4fb617c.png)

Can this option be added? Thanks in advance.

**Comment by bengotow** [comment]
Hey! This will not likely be an option in the future because it's hard to keep the app's performance smooth when it expands really long conversations. There is a solution though! If you go to Preferences >Keymaps and choose "Edit Custom Shortcuts" at the bottom of the window, it will reveal a `keymap.json` file in the Finder.

If you open that file in a text editor and add a line like this, you can choose any shortcut you'd like for the "Toggle expanded" menu item:

```
{
  "message-list:toggle-expanded": "mod+Y"
}
```

<img width="373" alt="image" src="https://user-images.githubusercontent.com/1037212/66448135-36bc4900-ea16-11e9-8537-039aa1b80fc3.png">


Then pressing Cmd+Y (or your favorite shortcut) will expand the thread you're reading.

**Comment by mickey4322** [comment]
Expand/ collapse conversation does not seem to be appearing on right click (windows version).

**Comment by tukusejssirs** [comment]
@mickey4322, it does not appear on Linux (CentOS) either, but I don’t need the right-click menu as long as I can use a shortcut. :smiley:
