### ISSUE TITLE
Cannot connect to Gmail

### ISSUE THREAD

**Issue by Linyxus** [Foundry376/Mailspring#1616]
##### Are there any related issues?

#614, I think.

##### What operating system are you using?

macOS Mojave, 10.14.6.

##### What version of Mailspring are you using?

1.6.3

--

Gmail OAuth simply does not work for me. I've tried many times. Each time it just says "You are all set!" on the webpage but still displays "Connecting to Google ..." in the application. After some while, it says "An unknown error has occurred (mailsync: null)".

Have any idea? :(

**Comment by Linyxus** [comment]
Suppl: I've tried "Try Again", but all the same.

**Comment by perteraul** [comment]
I have the same issue. In Activity, it says "Caching".

**Comment by vincent-young-1701** [comment]
Same issue trying to connect to my Gmail account for the first time...just hangs on connecting to Google after I've completed Oauth.

**Comment by vincent-young-1701** [comment]
Works now for me.  Assuming the previous public network I was on was at fault.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-connect-to-gmail-from-behind-vpn/421

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
