### ISSUE TITLE
ReplyTo header isn't working when repliying

### ISSUE THREAD

**Issue by Ldiro** [Foundry376/Mailspring#1625]
##### Are there any related issues?

Didn't really find one

##### What operating system are you using?

LinuxMint

##### What version of Mailspring are you using?

1.6.3

--

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

repoducible with every mail

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes

Mailspring does always reply to the From header, not the ReplyTo header.

**Comment by bengotow** [comment]
Hey! Hmm I tried to reproduce this today and it looks like it's working properly for me. The one caveat is that if the ReplyTo is an email address linked to Mailspring (eg: it's "you"), it will choose the other sender. This is so that if you reply to your own email in a conversation with another email, it sends it to the recipient and not to you. Can you verify that you're seeing this happen with external email addresses?

**Comment by Ldiro** [comment]
That is effectly the case, I was testing with one of my account. Thank you for your answer, and keep doing the great job on the soft !
