### ISSUE TITLE
[Feature Request] Select file in explorer, right click, "Send to..." through Mailspring

### ISSUE THREAD

**Issue by JunnanZ** [Foundry376/Mailspring#165]
##### Are there any related issues?

No

##### What operating system are you using?
Arch Linux

##### What version of Mailspring are you using?
1.0.4

--

**Bug?**
In nautilus, if I right click a file and choose "send to" through mailspring, it will open the message composing window in mailspring but there is no attachment there.

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! This would be a great issue for someone looking to contribute on Linux. I'm actually not sure how this works, since the mailto:// protocol doesn't support file attachments. Step one would be digging a bit more into how this works. Depending on that, it might be easy, or might require an upstream patch to Electron.

**Comment by gleachkr** [comment]
For what it's worth, here's the source for send-to in nautilus.

https://github.com/GNOME/nautilus-sendto/blob/master/src/nautilus-sendto.c

It looks like, unless you make a PR on their side, you need to handle a nonstandard `?attach=` parameter in the mailto URI. This has some evident security risks, although there's a simple fix for evolution that people seem mostly happy with:

https://bugzilla.redhat.com/show_bug.cgi?id=733504

**Comment by unholyeyebrows** [comment]
I'd like to see this functionality introduced too. This is a showstopper for me migrating to Mailspring as I share photos often from Shotwell using the "Send to..." feature. Are there any plans to develop this? Thanks, Nick

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

<<LINK>>

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@JunnanZ: if you join and reply to the issue, the moderators can make an effort to reassign your post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
