### ISSUE TITLE
Leaking IP when sending emails

### ISSUE THREAD

**Issue by krevoit** [Foundry376/Mailspring#1650]
##### Are there any related issues?

Not that I can see

##### What operating system are you using?

MacOS Mojave

##### What version of Mailspring are you using?

1.6.3

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

When I send emails, in the email header, instead of sending the email with the server IP, it uses the IP Address from my Mac which is quite irregular.

**Comment by bengotow** [comment]
Hey! Unfortunately this is expected behavior. We don't add the IP address to the headers explicitly - the remote IP is added by your SMTP server. You may not see this with other clients because they're delivering messages through their app's servers (eg: Superhuman, Gmail web app), but all desktop apps (Thunderbird, Mac Mail, etc) will do this. The added header looks like this on Gmail:

```
Received: from Bens-MBP ([2605:a601:a384:9800:6406:b814:c9ab:b989])
        by smtp.gmail.com with ESMTPSA id u69sm65341ywu.93.2019.10.08.14.18.23
        for <ben@foundry376.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 08 Oct 2019 14:18:23 -0700 (PDT)
```

(That is my IPv6 address in parents after the machine name.)
