### ISSUE TITLE
Caching Emails Inefficient Algorithm

### ISSUE THREAD

**Issue by AbuZayn** [Foundry376/Mailspring#1652]
##### Are there any related issues?  N, Similar, but not the same.

...

##### What operating system are you using?  Manjaro Linux

...

##### What version of Mailspring are you using?  1.6.3

...

--

**Bug?**  Not bug really, just significant performance improvement.

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? N

...

##### Is the issue reproducible with a particular attachment, message, signature, etc? N

...

--

**Feature Request?**  Yes

##### Does this feature exist in another mail client or tool you use?  N

-- Feature Issue:
        For accounts with a very large number of emails, caching takes too long and starts with the least important files first, making user wait to access critical emails.

...  Feature Requests:  
         1) When Mailspring caches email accounts from scratch, it should start with primary folders first (Inbox, Sent, Outbox, etc. before moving to subfolders/save folders such as Clients/MyClient or Vendors/Contracts).  And these folders should be cached by newest files first.  It should then move to the most recently touched folders.  As is, caching can start with very old and not important folders, while forcing you to wait to access the emails you need.
        2) When caching emails, you should be able to limit the cache by age  (such as folders touched within last 60 days).  Caching can still add older folders as soon as they are touched and remove them from cache when they are older than specified age.

**Comment by bengotow** [comment]
Hey! 1) above should already be the way Mailspring works, unless your primary folders have localized / international names and lack the IMAP role flag. 2) will definitely be coming at some point - we actually have the sync logic implemented for shallow / partial storage and just need to implement the UI. 

In general though Mailspring builds a more robust cache than clients like Thunderbird because it implements it's own Gmail-style search (eg: "in:inbox has:attachment term-in-body") so it'll always be a bit slower than clients that only fetch message headers.
