### ISSUE TITLE
Crashes Upon Failed Request to Serer

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#166]
##### Are there any related issues?
#90 Might be similar
...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
1.0.4
...

--

**Bug?**

getmailspring.com is accessible, id.getmailspring.com is not (blocked via proxy). From the Inspect Element terminal, a connection error occurs, then it crashes. Connection errors also appear inside the logs. I disabled the antivirus, and it still occurs.

Logs;
[mailsync-265b5044.log](https://github.com/Foundry376/Mailspring/files/1385842/mailsync-265b5044.log)
[mailsync-850a6688.log](https://github.com/Foundry376/Mailspring/files/1385843/mailsync-850a6688.log)
[mailsync-9268bc8f.log](https://github.com/Foundry376/Mailspring/files/1385844/mailsync-9268bc8f.log)
[mailsync-3d270570.log](https://github.com/Foundry376/Mailspring/files/1385845/mailsync-3d270570.log)

##### Do you have any third-party plugins installed? If so, which ones?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No
...

--

**Comment by bengotow** [comment]
Hey! Blocking id.getmailspring.com isn’t supported - it might work for some accounts but I’m not planning to invest time in fixing it if it doesn’t. It definitely won’t work with Gmail accounts linked via three-legged OAUTH (the standard flow) because the Mailspring server provides the third leg of the oauth flow using our Gmail client secret.

 #90 will be fixed soon which may improve stability on Linux and Windows.

**Comment by Modelmat** [comment]
Is there any way to avoid this? I thought this was supposed to connect directly to the mail servers - or was I wrong?
