### ISSUE TITLE
Avast Antivirus detects threat after latest update!

### ISSUE THREAD

**Issue by RasheedAZ** [Foundry376/Mailspring#1663]
"We've blocked mailsync.exe because it was infected with IDP>Generic"

![avast-mailspring-screenshot](https://user-images.githubusercontent.com/16827461/66785875-00f9f180-ef3b-11e9-9884-05dcaa0a8be2.PNG)

On Windows 10 just updated to latest version 1.71-45d4260b a few minutes ago

Please tell me what to do! Thanks.

##### Are there any related issues?

...

##### What operating system are you using?

...

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by RasheedAZ** [comment]
OK VirusTotal gives 0/69

https://www.virustotal.com/gui/file/960f4a69ea1e1e1beaa7f170e2263ee378e774236ba7ddcf9f74bf362732a517/detection

so is it a false alert?

**Comment by working-name** [comment]
Yes, this is a blunder on Avast/AVG's side. It's a false positive.

By the way, the component issuing this alert is "Behavioral Shield".

**Comment by RasheedAZ** [comment]
OK thanks I'll create an exception

**Comment by bengotow** [comment]
Hey folks! Yeah this is definitely a false alarm... we switched Windows Authenticode certificates in 1.7.0 because Digicert wanted $1,000 to renew our existing certificate (they're supposed to be like $120 / year which is still crazy.) I think that in some antivirus systems, new binaries need to "gain reputation" in some way and it might be that we need a few people to review and whitelist the app.

Sorry for the hassle! I've heard that we can pay significantly more and get a "pre-trusted" Authenticode cert that will be whitelisted out of the gate, but we're not quite big enough for that yet. (Honestly, all this verification stuff does is verify your attacker is willing to spend $1000 to infect your machine...)

Going to leave this open for a bit and we can collect more reports here.

**Comment by bengotow** [comment]
Hey folks! Just double checked, and you should see that mailsync.exe is signed like this on your system after install. If you encounter this error and have `signtool` installed, you can verify but I expect these spurious failures will stop after the antivirus tool has a few days to acclimate to this cert.

```
Verifying: C:\Users\<your username>\AppData\Local\Mailspring\app-1.7.1\resources\app.asar.unpacked\mailsync.exe
Signature Index: 0 (Primary Signature)
Hash of file (sha1): 1B512FBBA9E387DF9E6B329DAD2A6AAA92FEC3FC

Signing Certificate Chain:
    Issued to: AddTrust External CA Root
    Issued by: AddTrust External CA Root
    Expires:   Sat May 30 03:48:38 2020
    SHA1 hash: 02FAF3E291435468607857694DF5E45B68851868

        Issued to: USERTrust RSA Certification Authority
        Issued by: AddTrust External CA Root
        Expires:   Sat May 30 03:48:38 2020
        SHA1 hash: EAB040689A0D805B5D6FD654FC168CFF00B78BE3

            Issued to: Sectigo RSA Code Signing CA
            Issued by: USERTrust RSA Certification Authority
            Expires:   Tue Dec 31 16:59:59 2030
            SHA1 hash: 94C95DA1E850BD85209A4A2AF3E1FB1604F9BB66

                Issued to: Foundry 376, LLC
                Issued by: Sectigo RSA Code Signing CA
                Expires:   Sun Oct 09 16:59:59 2022
                SHA1 hash: 89AB981CB615CD7354CF0D1372E7C88AECE763DE

File is not timestamped.


Successfully verified: C:\Users\IEUser\AppData\Local\Mailspring\app-1.7.1\resources\app.asar.unpacked\mailsync.exe
```
