### ISSUE TITLE
[feature request] Signature below the quoted text

### ISSUE THREAD

**Issue by tvercaut** [Foundry376/Mailspring#1676]
Currently, Mailspring puts the signature below own's reply. It would be good to allow placing the signature below the quoted text (i.e. at the bottom end of the email).

##### Are there any related issues?

I couldn't find any existing related issue.

##### What operating system are you using?

Mac OS X Catalina

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

1.7.1

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Thunderbird allows for such customisations as shown in this screenshot
<img width="425" alt="image" src="https://user-images.githubusercontent.com/1614505/67146494-750dff80-f283-11e9-9f06-b35131966e02.png">

**Comment by bengotow** [comment]
Hey hey! Unfortunately I think this setting was one of the worst things to happen to email formatting 😅 - placing templated content at the bottom of the message (beneath the quoted text) causes lots of problems for recipients because many clients do a bad job identifying the quoted sections when more original content is beneath it. (eg: it looks like you replied inline, when in reality your signature AND the quoted message could be clipped off when the message is displayed). Google actually solved this with machine learning in Gmail because it was so challenging.

I'm afraid you'll have to stick with Thunderbird or the old Outlook for this one!
