### ISSUE TITLE
Unable to open contacts window

### ISSUE THREAD

**Issue by mslourens** [Foundry376/Mailspring#1683]
##### What operating system are you using?
Linux Mint 19.2

##### What version of Mailspring are you using?
1.7.2

**Bug**
Steps to reproduce:

1. Navigate to menu item Window -> Contacts
2. An empty window opens up
3. In the console this error is shown: cannot read property 'find' of null (at ContactDetailWithFocus.getStateForProps (internal_packages/contacts/lib/ContactDetail.tsx:78)

**Bug trace outcome**
If you set the contacts property of the ContactDetails.tsx to an empty array (`(contacts || []).find(c => c.id === focusedId)`), there is an error in the database-store.js on line 332: ```DatabaseStore: Query SELECT `Contact`.`data` FROM `Contact`  WHERE `Contact`.`refs` > 0 AND `Contact`.`hidden` = 0  ORDER BY `Contact`.`id` DESC , [] failed Error: Failed to construct SQL statement (no such column: Contact.hidden).```

**Comment by bengotow** [comment]
Oh wow - this is a pretty interesting one. It looks like the database migrations for the new release didn't run, which I don't think I've seen before. I'm still trying to figure out how that could happen (the database version itself is stored inside the database, so it's pretty hard to "trick" it into thinking the migrations have been run, and it tries to run pending migrations each time you launch the application).

EDIT: Actually, I think this could happen if you installed the update and the system was unable to replace the `mailsync` executable because it was running (maybe?) If the migrations had failed to run, the new version of mailsync would be crashing, but the old version would be working and you'd only notice when you opened Contacts.

I'd recommend you try to quit Mailspring and re-install it on your system. (I believe you could unpack over the existing installation to not remove any of your settings or mail cache.)

Hope that helps—let me know how this turns out, I'm really curious how this could happen!
