### ISSUE TITLE
A single shortcut is mapped to both Change Folder and Change Labels

### ISSUE THREAD

**Issue by nickolasclarke** [Foundry376/Mailspring#169]
##### Are there any related issues?

none that I can find

##### What operating system are you using?
windows 10

##### What version of Mailspring are you using?
1.0.4-e604c991
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
none

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
May be Zoho specific, likely applies to all generic IMAP providers

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Currently if you use the `l` or `v` keyboard shortcut to sort / move a message into a folder only actually works to add a Label. As far as I can tell there is no way to move messages into folder via keyboard shortcut.

**Comment by bengotow** [comment]
Thanks for reporting this! I think the problem is that Nylas Mail used to have a single dropdown for "move to category" and a corresponding `core:change-category` shortcut. I split the category picker into a LabelPicker and a FolderPicker (for "change labels..." and "move to folder..." respectively) and we still need to split the shortcut apart.

I think if you grep through the codebase for `core:change-category`, it's currently implemented in both the FolderPicker and LabelPicker and it's essentially random which one appears. We'd want to rename `core:change-category` to `change-labels` and make the FolderPicker respond to a new one `core:change-folder`.

If you could take a crack at it that'd be awesome! Let me know if you need help getting the dev environment going - I think the postinstall script is working now on Windows, and it'll download a .tar.gz file with the mailsync binaries into your working copy. If you unpack that into the working directory, you should be able to run `npm start` and have it work.

**Comment by aw3stin1** [comment]
I am having the same issue on Linux platform using Office 365. Just wanted to confirm this is not specific to a platform or email provider.
