### ISSUE TITLE
[Feature Request] Ability to Change email fonts

### ISSUE THREAD

**Issue by StewAlexanderACC** [Foundry376/Mailspring#1721]
Maybe I am missing something, but I don't see a place where I can change the font face?

What I refer to is the font that I use to review and send emails - not what is sent (I doubt there is much control over this).

There's plenty of open source font faces out there (https://fonts.google.com/), it would be nice if we had a few to customize the mail experience.

Thanks...

**Comment by boffbowsh** [comment]
Why did you tag me in this?

**Comment by StewAlexanderACC** [comment]
@boffbowsh - sorry, not too familiar with the github etiquette - thought you were a developer, apologies

**Comment by StewAlexanderACC** [comment]
@Foundry376 - can this be considered a to-do, or if not perhaps later?

**Comment by bengotow** [comment]
Hey! You can change the font your email text is written in as you're composing, but we don't allow you to change the default composer / "sending" font because it'd override your recipient's preferred reading font.

The reading / interface font in Mailspring is actually controlled by the theme, but right now all of the themes use the same font. I think you could create your own theme based on https://github.com/Foundry376/Mailspring-Theme-Starter/ and add a file beside `ui-variables.less` called `email-frame.less` with this content (https://github.com/Foundry376/Mailspring/blob/master/app/static/style/email-frame.less) and then modify it to your preferred font.

I think we could add this as an option separate from the theme, but in all honesty we've had a couple hundred thousand downloads this year and this is the first request so I'm afraid it won't be super high on the priority list for Q1! We are planning to make a "theme browser" in the app though and allow themes to be published, which would make it a lot easier to find ones with other fonts I think!

**Comment by StewAlexanderACC** [comment]
@bengotow - Absence of request is not the same as a no one wants it, it could be overlooked. 

Anyway it isn't a big deal, but it would be _nice_ to have easy customization options.

Thank you for the reply, great product otherwise.

**Comment by mattaylor** [comment]
Requests to control and change fonts have been floating around since 2016.

I would strongly suggest that it is far more important for the sender of an email to control the font that is used in their messages than it is for the recipient to decide. Leaving it this option significantly diminishes the utility of email as a medium for  expressive communication. 

Font selection for email is similar to handwriting style, and goes some way help to express and convey the identity of the author. If the receiver really wants to override the font then they should be able to, but i dont believe this should be the default. Email clients can be and should aspire to be more than just a bad chat app.

**Comment by StewAlexanderACC** [comment]
I agree @mattaylor 

My original intent was customization, but it makes more sense for the author of the letter to provide whatever nuance to the communication they may wish to convey to the receiver.

**Comment by ianpan870102** [comment]
> I think you could create your own theme based on https://github.com/Foundry376/Mailspring-Theme-Starter/ and add a file beside ui-variables.less called email-frame.less with this content (https://github.com/Foundry376/Mailspring/blob/master/app/static/style/email-frame.less) and then modify it to your preferred font.

Hi @bengotow ! I tried this approach and Mailspring is not picking up my font changes at all. I inspected element and it seems that my email-frame.less changes don't show up and have no effect in the styling.

**Comment by howdev** [comment]
@bengotow how can an application cannot change font face? You don't need to worry about recipient font. Operating system has font substitution system, if not, then Mailspring itself can allow choose own fonts. Even internet browsers can choose fonts and override fonts, regardless of the website default font.

**Comment by JeffreyUrban** [comment]
Came across this issue because the default Mailspring font does not display Chinese characters. Assuming this may apply to all non-roman Unicode characters, then this would affect most of the world population.

**Comment by wu0lss4j** [comment]
> Came across this issue after finding that the default Mailspring font does not display Chinese characters (they are all shown as rectangles).
> 
> UPDATE: I was able to change the font using a custom theme, but it did not fix the rectangles, even though I would expect font-family 'system-ui' and 'Arial' to support Unicode... so maybe this is a separate issue.
> 
> UPDATE: It started working, so maybe it needed a restart to fix Unicode display, even though the font had appeared to change successfully.

Hi, I'm also trying to change the default font. I just cannot get mailspring to change fonts. After looking thru the code I see they reference an old Nylas font (related to their previous github project nylas mail) and now it references a "Custom" font from the family Fakt Pro Nor. 

If you still remember the steps, can you share the composer.less file and where to place the font files?

Thanks!
