### ISSUE TITLE
The internet connection has been lost

### ISSUE THREAD

**Issue by nZeus** [Foundry376/Mailspring#1732]
##### What operating system are you using?

Deepin 15.11

##### What version of Mailspring are you using?

1.6.x (install via deepin's App Stor) - works OK
1.7.2 (installed via span) - Doesn't work

--

**Bug?**

* Just installed the app (v1.7.2) via the snap
* It shows the Welcome splash screen
* Next > next > next..
* And I get this error O_o:

![DeepinScreenshot_20191210205824](https://user-images.githubusercontent.com/2727326/70564111-d66d9300-1b8f-11ea-95e5-e8074f1ba499.png)

Reverted to v1.6.1-acee, and it works again..

**Comment by dev-kasibhatla** [comment]
I have the same problem with Deepin 15.11 when Mailspring 1.7.8 is installed from Snap Store.

![image](https://user-images.githubusercontent.com/29339397/83513867-2d757480-a4f0-11ea-8e4f-66e11174addd.png)

**Comment by CodeMouse92** [comment]
In December 2020, Mailspring's AWS servers experienced some technical issues that interfered with several features, including Mailspring accounts, link tracking, and open tracking. These issues have since been resolved.

If you experience these issues again, please open a Service Issue report on our new Discourse community: https://community.getmailspring.com/

Thank you!

-The Mailspring Team
