### ISSUE TITLE
Lack of news about updates and / or new features

### ISSUE THREAD

**Issue by CarlosRebolledo** [Foundry376/Mailspring#1751]
When will we have new features and / or updates? Paying for this customer month by month and not having news in 2 months seems to me a contradiction, to say the least.

**Comment by mie** [comment]
Totally agree. Is the project still maintained?

**Comment by CarlosRebolledo** [comment]
No hay respuesta alguna!!!!

And there is no answer!!!

**Comment by CodeMouse92** [comment]
Hi all,

Please understand, Mailspring is an independent software project which is primarily maintained by one person — Ben Gotow — in addition to his full-time job. Mailspring Pro subscriptions mostly go to pay for server, API, and required audits that make Pro features and mail service interoperability possible.

This project has seen many new updates since the above conversation. However, **Mailspring Pro makes no promises about release timeline.** Additionally, the GitHub Issues got so backlogged — mostly with duplicate reports, wishlist feature requests, and unreproductable edge-case bugs — that Ben could not keep on top of it without sacrificing what little development time he has. This is why I joined as the (volunteer) Community Manager, and so far I've been able to audit over half of the 1.1K issues in the backlog.

The latest news about Mailspring is now on our new Discourse community:

https://community.getmailspring.com/t/mailspring-community-transition/38

https://community.getmailspring.com/t/mailspring-1-8-0/119

https://community.getmailspring.com/t/a-free-open-source-future-for-mailspring/484

Please be patient with independent software timelines. The slightest life disruptions for such a project's developers can unavoidably delay releases by months. Mailspring is not backed by a large company, nor could it practically *be* backed by such a company without sacrificing the user privacy we value so highly. We hope that by making Mailsync FOSS, that will help improve our release timeline, but it's impossible to make promises.

Thank you for your understanding.
