### ISSUE TITLE
Participant profile sidebar crashes on adress without display name

### ISSUE THREAD

**Issue by Bouska** [Foundry376/Mailspring#177]
I'm using MailSpring 1.0.5 on a Fedora 26. In the participant profile sidebar I can choose any participant of the thread in the dropdown list. I can choose any participant with a display name but if I choose a participant without a display name, the whole sidebar goes blank (including the dropdown list). I have to open another mail to make it appear again. "Fun fact": if the mail I opened was written by someone without a display name, the participant profile is display without any problem. Nothing appear on the error console, so it looks like an "intended behavior" not a crash.

I'm going to try to fix this bug on my own, but I never touch to react code in my life so it might take me some time to figure it out.

**Comment by bengotow** [comment]
Hey @Bouska — thanks for reporting this! I think I've seen this one as well and I wasn't sure what was going on. It's especially strange because there aren't any errors in the console.

If you're doing some debugging, a good place to start might be opening the Developer Tools once it goes blank and typing:

```
$m.FocusedContactsStore.focusedContact()
```

`$m` is a shorthand for `mailspring-exports`, so you can access lots of stuff that way and poke around to see what's going on.

**Comment by Bouska** [comment]
Ok, I found where the bug comes from (undefined !== "undefined" !), I'll send a patch tomorrow.
