### ISSUE TITLE
Feature Request : Email Client not supporting Table 

### ISSUE THREAD

**Issue by sammish** [Foundry376/Mailspring#1773]
Table copy paste not working in email compose 

![image](https://user-images.githubusercontent.com/12432802/72667842-295d2480-3a31-11ea-9aa7-3fe1d07f6ba1.png)

![Peek 2020-01-18 20-34](https://user-images.githubusercontent.com/12432802/72667920-0f701180-3a32-11ea-9095-8458f83ef8fa.gif)

**Comment by bengotow** [comment]
Hey! It looks like this may be working actually, but Mailspring doesn't add any borders to your table - you'll need to add borders in your spreadsheet and then copy/paste for it to look like a table.

EDIT: Actually, it looks like table borders are lost even if you specify them in Excel. I'll see if I can fix this!

**Comment by sammish** [comment]
@bengotow thanks for your valuable support

**Comment by bengotow** [comment]
Hey @sammish thanks for reporting this one! Mailspring properly pastes borders from Excel now (just checked in version 1.7.6) so this should look better. That said, if you paste a table with no borders specified in Excel, it still looks like your screenshot. I'll see if we can do something about that in the next release, but it's tricky to add borders on the user's behalf because there are other places (like a special signature) where the borders betweee the cells might not be desirable. Cheers!

**Comment by sammish** [comment]
@bengotow 
It's very nice now.  I have checked with the new version (1.7.6 ). Thanks for the support. Cheers!

![image](https://user-images.githubusercontent.com/12432802/80073522-91e80000-8550-11ea-86fd-cecfc40ed9f4.png)

**Comment by iamprakashom** [comment]
Hi, 

I am pasting table from WPS Spreadsheet and it is pasting image of selected table in email body instead of table. I am using Mailspring 1.9.1 on Ubuntu 1.04.

Let me know if you require any further information.

**Comment by CodeMouse92** [comment]
@iamprakashom PRs are not the place to report bugs. Please use https://community.getmailspring.com/.
