### ISSUE TITLE
"Mailspring ID" is garbage

### ISSUE THREAD

**Issue by billsimon** [Foundry376/Mailspring#1778]
Just like every other new e-mail client for Mac, Mailspring requires me to associate myself with their servers, even though I never ever intend to subscribe to any paid features.

Requiring such an association goes against the spirit of FOSS.

**Comment by dweremeichik** [comment]
Duplicate of #33 please close.

**Comment by billsimon** [comment]
#33 as well as more than 850 backlogged issues in the tracker tells me the author does not take this project seriously.

**Comment by dweremeichik** [comment]
Ben is a good dude, trying to live his best life. But yeah, he could probably use a hand triaging.

The problem with email is that there are so many corner cases it's silly. There is a reason Google runs its own API for all of it's email applications instead of relying on IMAP, etc. These corner cases end up burning inordinate amounts of time; which mean developers have to charge more for a product that should be pretty cheap. Take boxy suite for example; all they do is wrap Gmail and they still have to charge $50 a year to make money.

There is no winner takes all emai client because users don't want to have to pay for mail. Also why the post office charges you to send, in the physical world.

Hope you are able to find something that fits your needs; I still haven't.

**Comment by billsimon** [comment]
I acknowledge that e-mail isn't what it used to be, though it's still the Internet's "killer app" in my opinion which is why a solid desktop client seems to be a must. I regret the negative vibes toward the author. Would love to see this project fully opened and developed by the larger community if he decides to move on to something else that can bring in more money than an IMAP client.
