### ISSUE TITLE
Feature Request: Load as plaintext by default, press a button to Show as HTML.

### ISSUE THREAD

**Issue by cryoknight** [Foundry376/Mailspring#1780]
Just like mail clients block images unless you press the Show Images button, can you go one step further for 100% security, and only render emails as plaintext unless someone presses Show As HTML?

That would be awesome.

**Comment by bengotow** [comment]
Hey! This would be pretty cool—I'll see if we can add this in an upcoming release. I think we'd need to support HTML=>plaintext conversion on the fly since not all email sent these days has a plaintext MIME part, but not rendering HTML at all is certainly the safest thing we could do. (And also helps prevent phishing since link text and href are always the same).

**Comment by cryoknight** [comment]
Great! Thanks Ben!

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/load-as-plaintext-by-default-press-a-button-to-show-as-html/836

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@cryoknight: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
