### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by rajibraiyat** [Foundry376/Mailspring#1793]
#1793

Please add quick logout system and add a pin code system in mailspring linux app.
So people can easily lock their mailspring app in linux os.

**Comment by mxschumacher** [comment]
why is it preferable to have a per-app lock, when you can just lock the entire user session with something like xlock?

**Comment by bengotow** [comment]
Hey folks—this has been brought up before but I can provide a bit more feedback! We don't plan to add app-level locking to Mailspring (a PIN screen, etc) because these types of measures are ineffective against someone with physical access to your unlocked computer unless the PIN screen is accompanied by app-level encryption of data at rest. Doing it without proper on-the-fly decryption (what 1Password does, which really is secure) would give users the false impression that their data is protected in ways that it is not.

We can't easily encrypt Mailspring's mail cache / attachments on disk, so adding a PIN screen would not actually deter someone with physical access to your computer and the desire to extract your mail data. (They could just navigate to Mailspring's data folder and open the mail database themselves.)

I'd highly recommend configuring your machine to log you out at the OS level after a brief period of inactivity (5 minutes for example) and turning on full-disk encryption to prevent someone from extracting your mail data from your computer's hard drive without your password. Cheers!

**Comment by rajibraiyat** [comment]
@bengotow 
What if I'm using my office computer? And some other people have access in my office computer.
