### ISSUE TITLE
Message-ID with mailspring string

### ISSUE THREAD

**Issue by MalteKiefer** [Foundry376/Mailspring#1800]
Hello,
I found in my mail headers this here:

    Message-ID: <B5619CE5-XXXX-XXXX-XXXX-22CED1A78C9D@getmailspring.com>

Why contains my Message-ID a mailspring print?
Is it possible to hide/deactivate or remove it?
May as opt-in like in other mail programs?

**Comment by bengotow** [comment]
Hey! We actually do this on purpose so that it's not the hostname of your machine (normally it would be `my-random-string@bens-macbook-pro.local` which seemed like a privacy violation!) 

I'll see if we can change this in the future but it's worth noting that you can identify which email client another person is using pretty accurately if you are familiar with the raw headers - Gmail, Outlook, O365, Yahoo etc all use unique methods of generating the unique IDs and other headers, so there's not much more we're giving away here :-)
