### ISSUE TITLE
Bug: tray icon can't be removed

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [Foundry376/Mailspring#1805]
**Describe the bug**
If i uncheck "Show icon in system tray" option in general preferences icon isn't removed from tray. If i check it again, duplicate icon appears. Icons removed only when closing app.

**To Reproduce**
1. Go to Edit -> Preferences -> General
2. Uncheck "Show icon in system tray"
3. Icon stays in tray
4. Check "Show icon in system tray"
5. Duplicate icon appears in tray

**Expected behavior**
If checkbox "Show icon in system tray" unchecked -- icon should be removed

**Screenshots**
![mailspring_icon_duplicates](https://user-images.githubusercontent.com/3637857/75116319-2ed50c80-5678-11ea-8b78-8049232a8dc2.png)

**Setup: (please complete the following information):**
 - OS: Ubuntu
 - OS Version 18.04
 - Mailspring Version: 1.7.3

**Comment by GrigoriyMikhalkin** [comment]
Seems like it's electron's problem and is already solved in later version: https://github.com/electron/electron/issues/17622

**Comment by bengotow** [comment]
Thanks for pointing to the electron fix! Going to mark this as blocked on an Electron upgrade for us 👍

**Comment by CodeMouse92** [comment]
It appears this bug was resolved, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
