### ISSUE TITLE
Add Functionality to Hide/Postpone Update Notification

### ISSUE THREAD

**Issue by seesemichaelj** [Foundry376/Mailspring#186]
The update card (in Linux .deb 1.0.4) does not have a close/hide/remind me later functionality. We should add this functionality for people that do not want to update immediately since the card is bright orange and annoying after awhile.

Ideally, I believe the Download Now button should be split into two button, one of them says "Remind Me...; upon clicking it brings up a drop down for some time periods (i.e. 1 day, 3 days, 1 week, 1 month) and Never.

**Comment by seesemichaelj** [comment]
What about non Linux?

**Comment by bengotow** [comment]
Oh - I don't think it's an issue on Mac / Win because the updates are already downloaded when the notification appears, so clicking it and installing the updates removes the notification in ~5 seconds. It's way more of a pain on linux because right now it just directs you to the website and you have to install the deb/rpm manually.

**Comment by flaki** [comment]
I'm in Arch Linux where Mailspring is installed from source from the [contributed repositories](https://aur.archlinux.org/packages/mailspring/) and there this is still a huge annoyance.

I would prefer to have a setting in _Preferences_ where I could enable/disable checking for updates (which I could disable since Mailspring would update separately from the package manager).

**Comment by Razer0123** [comment]
Same as above, please add an option

**Comment by teeann** [comment]
please reopen this issue
