### ISSUE TITLE
Bug: E-mail formatted as plaintext in replies

### ISSUE THREAD

**Issue by simonv3** [Foundry376/Mailspring#1894]
**Describe the bug**
When replying to an e-mail, reply formats in plain text. It also sends in plain text.

**To Reproduce**
1. Go to any e-mail
2. Click on the reply or reply all button
3. See reply automatically formatted in plain text.

I don't see a way to disable this, and maybe it's a setting I accidentally toggled, but I can't find anything. 

**Expected behavior**
Don't format the e-mail in plain text. 

**Screenshots**
![screenshot-bug](https://user-images.githubusercontent.com/485583/78801476-9cf83900-7971-11ea-87db-86897610c328.png)

**Setup: (please complete the following information):**
 - OS: Linux Mint
 - OS Version 19.1 Cinnamon (4.0.10)
 - Mailspring Version: ex: 1.7.4.d5(etc)

This is actually happening across two computers with different Mailspring installations.

**Comment by scabecks** [comment]
I have been having the same issue for over a month now - at least since the last update. I am able to reply to exactly one email before the only option to reply becomes plain-text. I can restart Mailspring to again allow formatted replies, but again after the first reply only replying in plain-text becomes the sole option.
OS: Linux Mint 19.3; Cinnamon 4.4.8
Mailspring version: 1.7.4-d54ff730

**Comment by matyhaty** [comment]
Same issue here, its epiccally frustrating

Same as @scabecks 

- reply - sometimes plain, sometimes rich
- compose - sometimes plain, sometimes rich

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this—I agree this is super annoying. It hasn't really been happening for me but I was able to track it down this evening. When I added plaintext composing, I made it so that holding option while creating a new email via any of the shortcuts or buttons would open the composer in plaintext mode. It looks like there are various series of keyboard events / mouse events / etc. that can cause the "is the alt key down?" state to become stuck, and then you get plaintext forever.

I'll fix this or pull it out before the 1.7.5 release goes out tomorrow, I'm sure not many folks are using this plaintext option.

**Comment by matyhaty** [comment]
@bengotow Thanks Ben.  I was one the verge of pulling the plug of Mailsptring due to this bug, which would have been super bad times!!

But super happy to know its been resolved :)

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
