### ISSUE TITLE
Automatic resizing to half the screen doesn't work

### ISSUE THREAD

**Issue by Bouska** [Foundry376/Mailspring#191]
I'm using Mailspring 1.0.5 on Fedora 26. This is sort of a paper cut/feature request, when I drag the Mailspring window on one side of the screen it doesn't automatically resize it to half the screen. Here a screencast of what I mean with Atom:
![screencast](https://user-images.githubusercontent.com/1036656/31680443-99aaf2e4-b374-11e7-82c0-396fde7f3d30.gif)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this is actually surprising... it doesn't work on Mac OS X, but it's because we're replacing the whole title bar with HTML+CSS. 

Can you try and see if you can manually shrink the window to the size of half your screen? I wonder if this isn't working because the requested size is smaller than the minimum size of the window?

Also for a second I didn't realize that was Atom and was trying to figure out what theme you were using. hah. :-)

**Comment by Bouska** [comment]
You were wondering right ! The minimal size is like half of my screen + a few more pixels so logically it can't be resized to less than that.

**Comment by THargreaves** [comment]
This is still an issue on Ubuntu. Are there plans to fix this?

**Comment by paalwilliams** [comment]
This is still an issue on Pop! OS, when it works at all. The window won't resize to half the screen anymore.
