### ISSUE TITLE
scroll using arrows

### ISSUE THREAD

**Issue by schapira** [Foundry376/Mailspring#1932]
Hi I can't use arrows to scroll while reading massage. in gmail shortcuts the arrow used to navigate to other massage, but it other shortcut system or when disabling arrow use in gmail, its still cannot use arrow to scroll within massage for reading. please help. can't use mouse all the time to scroll via scroll bar.

**Comment by bengotow** [comment]
Hey! Ahh that is definitely annoying. In Mailspring you can use Space and Shift-Space or Page Down and Page Up to move up and down in the message / conversation view - I'll see if we can update the shortcuts page to make that more obvious!

**Comment by compleatang** [comment]
Pro user here. Loving Mailspring, but this is a large annoyance. (And FWIW, Gmail's arrow keys don't cycle thru threads when in a reading panel.)

Paging up and down via keyboard is a hack (at best). Is it possible to expose the scroll feature to the keyboard shortcuts somehow? 

Why is there such a deviation from the expected behaviour? Is it due to this bug? https://github.com/Foundry376/Mailspring/issues/950

Sorry to be annoying on github, but am curious about why things are how they are.

**Comment by abarazaltt** [comment]
Using Space to move down, aside from being annoying, is not smooth at all so you lose focus on the line you were reading.

**Comment by schapira** [comment]
@bengotow please reopen this, need to have the option to use arrows.
