### ISSUE TITLE
Where is the mailspring inbox tray icon saved?

### ISSUE THREAD

**Issue by jayceer212** [Foundry376/Mailspring#1958]
I just installed Mailspring.  Great software.  The only thing that bothers me is the large inbox tray icon on Linux Mint 19.3.  It's much bigger than all the others.

What is the name of this icon and where is it saved so I can resize it?  By the way, I added Mailspring to Startup Applications and a custom command: `/snap/bin/mailspring --background`

Thanks a lot.

**Comment by ukrsup** [comment]
/usr/share/icons/hicolor/{16|32|64||128|256}/apps/mailspring.png

By the way, I use the same version of mint and the icon size is OK

![2020-05-02_11-08](https://user-images.githubusercontent.com/64681801/80859227-a79fa880-8c67-11ea-8164-4cf8a3a19197.png)

**Comment by bengotow** [comment]
Hey thanks for reporting this! I think at some point soon we'll have to make a directory of these images for different Linux variants... we've been trying to find a single icon size that works for everyone but it seems pretty much impossible because some launchers don't scale the images they're given at all (and just let them overflow the bar). If you could post the image you end up using here, that'd be awesome! Cheers 👋
