### ISSUE TITLE
Feature Request: Sync settings/themes across multiple devices

### ISSUE THREAD

**Issue by squintgit** [Foundry376/Mailspring#1962]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to sync your app settings across multiple computers (and even cross-platform). When you set up Mailspring just the way you like it, and with a certain theme, and then you install it on another computer, you have to redo all that stuff. With sync, everything would be exactly as you like it no matter what computer you install Mailspring on, once you sign into your account.

**Describe the solution you'd like**
Sync!

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I agree this would be really cool, and will probably be more important once we launch the calendar feature later this summer. I'm going to merge this into #44 and I'll see if we can get it done! In the meantime if you want to upvote that issue it'll help me make sure I'm prioritizing properly.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one already on Discourse:

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team
