### ISSUE TITLE
[Feature request] Delete cache per account

### ISSUE THREAD

**Issue by oserban** [Foundry376/Mailspring#197]
You should be able to delete mail cache per account rather than global. 
This is particularly useful when the mailsync process has errors.

**Comment by bengotow** [comment]
Ideally we'll just fix the bugs that are causing you to need this ;-)

**Comment by bengotow** [comment]
Hey! This is now possible via a new "Rebuild Cache" option in the Preferences > Accounts panel. It's quite slow since it clears large portions of the database rather than deleting it entirely, but should do exactly what you need:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/1037212/35764095-ec88a7fa-086e-11e8-844e-054b60fc3f31.png">
