### ISSUE TITLE
Flatpak or RPM release?

### ISSUE THREAD

**Issue by goosenphil** [Foundry376/Mailspring#20]
On the official website, the RPM download button is greyed out. Is there a Fedora package available?

**Comment by ktw** [comment]
Looks like a Snap is being prepared.
See issue #13 for info.

**Comment by ldartez** [comment]
Check out issue #11 and #14. Fedora binaries should be released soon.

**Comment by bengotow** [comment]
Hey folks—I've gone ahead and put the links on the download page so you can download .deb and .rpm packages for Linux. I was hoping to wait until we had a Snapcraft package because it will enable autoupdates for Linux users. (Currently, you need to come back to the downloads page and get it again when a new version is released.) The Snap is taking more time than I expected to get working, so this will do for now! Gonna go ahead and close this.
