### ISSUE TITLE
Bug: Can't send emails with attach files using IMAP account in Windows 10

### ISSUE THREAD

**Issue by jrmejiaa** [Foundry376/Mailspring#2005]
I am a working with a IMAP account in a Linux computer and a Windows computer. Both allows me to connect a IMAP account using the IMAP port 143 and the SMTP port 25 without security. I can receive emails without a problem and the synchronization works well. However, when I want to send a email with **an attach file** in Windows, the Mailspring sends an error saying that "We are sorry, Malspring can't send this message: Connection error: it can connect with the server/port that you give". I can send attach emails without a problem using Linux, but it takes a while (5 min) until I receive the message in the other account.  

**To Reproduce**
1. IMAP account, which does not have security access (SSL)
2. For my error this account was set with the IMAP port 143 and he SMTP 25
3. Try to send an email with an attach file 

**Expected behavior**

**Setup:**
 - OS: Windows 10
 - OS Version Windows 10 Pro
 - Mailspring Version: 1.7.7-71504f2c

**Comment by andre-idrive** [comment]
I'm having the same issues since the update. My email is a business email with gmail. I also when to go verify my login since it seems to be an authentication error but it's saying that I'm using the wrong password. I tried the same password int eh browser and it works.

Setup:
- Windows 10 Home
- Version 10.0.18362 Build 18362
- Mailspring Version: 1.7.7-71504f2c


![image](https://user-images.githubusercontent.com/53438650/82665098-176ad880-9c01-11ea-9025-cf651c2aac47.png)

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this - going to merge this into #1996. The fix has landed in master and I'll be shipping it soon!
