### ISSUE TITLE
Bug: UI is extremely blurry on Linux/Wayland

### ISSUE THREAD

**Issue by WhyNotHugo** [Foundry376/Mailspring#2013]
**Describe the bug**
Opened the app, and all text is rendered very blurry. I'm using scaling, so there may be something funky in how that's handled.

**To Reproduce**
1. Just open the app on Linux. (Having scaling activated may be relevant here).

**Expected behavior**
Text should render like pretty much anything else.

**Screenshots**
Not sure how much this helps, given the compression:

![2020-05-25T00:11:29,363060772+02:00](https://user-images.githubusercontent.com/730811/82766091-94699e00-9e0b-11ea-8081-c1877b111830.png)

[Edit]: Huh, due to the fact that the image is reduced in size, it actually looks _less_ blurry than it actually doe in reality.

**Setup: (please complete the following information):**
 - OS: [e.g. macOS, Fedora Linux]  ArchLinux
 - OS Version [e.g. 14] `5.6.14-arch1-1` 
 - Mailspring Version: ex: 1.6.2 (found in the app's menu) `1.7.7-71504f2c`

**Additional context** 
Installed via the [Arch User Repositories](https://aur.archlinux.org/packages/mailspring/). Running Wayland/swaywm, with scaling active (since my displays are hi-dpi).

**Comment by WhyNotHugo** [comment]
Oh, mailspring uses electron, I completely missed that on my first pass of the README.
Electron isn't really Linux-ready yet, this is a know issue on their part and happens with all electon apps. Nothing to be done here.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be connected to this:

https://community.getmailspring.com/t/interface-gets-blurry/89

Please consider joining that community and continuing the discussion there. **We need users to confirm the existence of this bug on Mailspring 1.7.8 or later, by commenting on that thread, for us to address this issue properly.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
