### ISSUE TITLE
Bug: Clicking the calendar invites from google doesn't change the calendar event status

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#2028]
**Describe the bug**
A clear and concise description of what the bug is. Does it happen with all email accounts, or only a particular account and/or email message?

I don't know I only have gmail

**To Reproduce**
click the link to accept or decline an invite 
go to the web google calendar the invitation status hasn't changed.
Tried these buttons from the web Gmail UI and they work fine from there.

![Screenshot_20200528_131634](https://user-images.githubusercontent.com/8903888/83129605-b69e3d00-a0e5-11ea-8158-9115a3255782.png)

These are the buttons

**Setup: (please complete the following information):**
 - OS: Ubuntu Linux
 - OS Version: 16.04
 - Mailspring Version: ex: 1.7.7

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/accepting-calendar-invite-should-change-event-status/43/1

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
