### ISSUE TITLE
Bug: When responding to calendar invites in gmail, it returns "undefined"

### ISSUE THREAD

**Issue by buehler** [Foundry376/Mailspring#2128]
**Describe the bug**
When one receives a calendar invite (over gmail) and then responds to this invite via the provided buttons in mailspring, the returning email to google contains `undefined` instead of the correct "Accepted" "Tentatively" "Declined" response.

It is saved in mailspring correctly which the leads to the problem that in mailspring the mail says "accepted" but when I visit the calendar on google itself, the invitation is still open.

**To Reproduce**
1. Invite someone
2. Click on "accept"
3. Review the sent response email

**Expected behavior**
It would be a very nice feature, but the response email to gmail must be correct in order to accept the invitation into the calendar.

**Screenshots**
This is the reply-mail:
![image](https://user-images.githubusercontent.com/1067213/91012077-c4c90000-e5e5-11ea-9540-3895e3fdd290.png)

**Setup: (please complete the following information):**
 - OS: Win10
 - Mailspring Version: 1.7.8

Regards

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/accepting-calendar-invite-should-change-event-status/43/3

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
