### ISSUE TITLE
Bug: Requires Mailspring account to use

### ISSUE THREAD

**Issue by ChrysAlice** [Foundry376/Mailspring#2140]
It's absurd that a Mailspring is **required** in order to use Mailspring as an e-mail client.  It's not even possible to see the UI in order to determine if the app is worthwhile before creating said account.

There are dozens of reasons why a Mailspring account is useful.  There are **zero** reasons why it is **necessary**.  As such, making it necessary before the installer even runs is either a bug or a design flaw, and it should be fixed.

**Comment by cdesewell** [comment]
Agreed, you shouldn't nee a mailspring account to use the client.

**Comment by CodeMouse92** [comment]
Great news! [Mailsync is now open source, and Mailspring ID is being made optional.](https://community.getmailspring.com/t/a-free-open-source-future-for-mailspring/484). Making the ID optional is a very involved change which will take some time to implement, but it is right at the top of our roadmap.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38). We're closing and locking the issue here as part of this migration.

We hope to see you on Discourse soon!

-The Mailspring Team
