### ISSUE TITLE
Feature Request: Android Version?

### ISSUE THREAD

**Issue by famewolf** [Foundry376/Mailspring#2176]
Android seems (and I suppose ios) seem to be the only platform's left out.  I'm not sure how transferrable the ui is but I'd love to use mailspring on my phone instead of aquamail or the gmail app.  (aquamail does function basically like mailspring but the author wants $20 for the app which is excessive.

**Comment by CodeMouse92** [comment]
While this would be marvelous (I also have an Android), Mailspring is built on Electron. Until they support Android, we won't be able to either.

By the way, please join our new Discourse community, which is the new home for bug reports, feature requests, and Mailspring discussion: https://community.getmailspring.com/

**Comment by CodeMouse92** [comment]
Duplicate of #1100

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/ios-or-android-mobile-support/94

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
