### ISSUE TITLE
Mailspring can open any arbitrary web page.

### ISSUE THREAD

**Issue by RonBis** [Foundry376/Mailspring#2204]
I was quite shocked when I clicked an email link and thought that the link would open in external web browser, but it didn't happened. I was just checking my github emails.There was a link to a github page and link opened right in a new mailspring window. From there window I was able to open Youtube and even jumped into google search page and rest is history.

**Steps to reproduce the behavior:**
1. Go to any email in external links in that.
2. Click on that link.
3. It opens in a new mailspring window

**Expected behavior**
Link should open in external web browser

**Screenshots**
![mailspring_vulnerability-1](https://user-images.githubusercontent.com/66785801/99391577-610e5480-2900-11eb-88cc-d830b4683f20.png)
-----------
![mailspring_vulnerability-2](https://user-images.githubusercontent.com/66785801/99391632-72576100-2900-11eb-87eb-be37cfb3f96a.png)
-----------
![mailspring_vulnerability-3](https://user-images.githubusercontent.com/66785801/99391658-7b483280-2900-11eb-9885-7099e22c9733.png)

**Setup: (please complete the following information):**
 - OS: Ubuntu LTS 20.04
 -OS version: 5.4.0-53-generic
 - Mailspring Version: 1.7.8-13635bcf (found in the app's menu)

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-can-open-any-arbitrary-web-page/366

Please consider joining that community and continuing the discussion there!

**@RonBis: Please see that conversation. We need some additional information to diagnose.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
