### ISSUE TITLE
Sync Engine Source: It's a security issue.

### ISSUE THREAD

**Issue by AsteriskDelta** [Foundry376/Mailspring#2214]
I'd love to switch over to Mailspring, but my work mandates some pretty strict guidelines about what can be installed-- namely, it has to be audited by notable organization or be entirely open source.

This has been asked before, but I hope the sync engine can be open-sourced, perhaps as a separate repository laden with warnings and disclaimers to average users, without documentation and without instructions. It's basically zero effort to do so, and could go far to allay security concerns.

**Comment by crash83k** [comment]
I'm in the same boat. The closed source sync engine is the only thing holding me back.

**Comment by CodeMouse92** [comment]
The topic of open sourcing MailSync *is* under internal discussion right now.

We're closing and locking the issue here as part of the [Mailspring Community Migration](https://community.getmailspring.com/t/mailspring-community-transition/38). Rest assured, this doesn't mean the issue is being discarded or ignored.

**Comment by CodeMouse92** [comment]
Great news everyone! **Mailsync is now open source!** 🎉 🎉 🎉

Read more here: https://community.getmailspring.com/t/a-free-open-source-future-for-mailspring/484
