### ISSUE TITLE
Signature Image Missing

### ISSUE THREAD

**Issue by vdisp** [Foundry376/Mailspring#2230]
As of today, all email signatures, whether from Old messages or Newly created messages are missing the image in my signature.

This image was uploaded to the Mailspring server which seems to be unavailable at the moment.

The image was stored in this folder:
https://user-generated.getmailspring.com/asset/

Please advise.

**Comment by matthew-hollick** [comment]
Confirmed from here too.
Looks like historic tracking data is still available for the moment.

The end of the Mailspring pro service?
A real shame.
Very reluctantly canceling my pro subscription as I do not have faith that this will be resolved.

**Comment by matthew-hollick** [comment]
:sob: 
Manage billing, Account details and View License no longer function..

**Comment by valentt** [comment]
Check my bug: https://github.com/Foundry376/Mailspring/issues/2231

This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

**Comment by artsgirl** [comment]
I have been using Mailbird for some of my other email accounts for a couple years, I think I may be switching everything to them. The one feature they didn't have for a long time was read tracking but they do have that now (still no link tracking as far as I know, though).

**Comment by CodeMouse92** [comment]
@artsgirl Unfortunately, @valentt spoke out of turn. The project and product are NOT dead. The maintainer responded to his issue. There was a server issue.

Mailspring is alive and well!

**Comment by artsgirl** [comment]
Really? Because I sure can't log into my account on the Mailspring website this morning, link tracking seems broken still (or again) today, and it's about 50/50 whether my signature images are able to be retrieved from the Mailspring server when I compose a new email.

Not to mention that on several of the other threads here from the past few days, many people have accurately pointed out that Mailspring support has *always* been slow to respond for a paid product. I have requests from over a year ago that have just been ignored completely. Really makes me wonder what I'm paying for.

**Comment by CodeMouse92** [comment]
@artsgirl He's one person working solo. He has his full explanation on #2231, if you scroll up and look for @bengotow's comments. He explains what happened over the past few months. 2020 has been a bear for us all.

**Comment by artsgirl** [comment]
Yes, and I did read that. And I'm still paying for this product and there's an expectation that goes with a paid, annual subscription product. And as I (and many others) have stated, many of the communication problems pre-date covid. This is ongoing. If this is going to continue to be a paid product, maybe one person isn't enough. And please don't come back at me with "well hiring people is expensive". I run three small businesses and have for over a decade, I know *exactly* what is involved in the balance between keeping commitments, being profitable, charging a reasonable price, and hiring an appropriate number of people. It's called running a business. If the one-man-show of Mailspring can't balance than, then he needs to sell or discontinue the product, because continuing to take people's money for premium support and then just flat out not providing support in anything even remotely resembling a timely manner is simply not okay.

**Comment by CodeMouse92** [comment]
@artsgirl I don't know the details of the situation, but from what I've seen, this is probably relevant: https://dev.to/codemouse92/why-is-it-taking-so-long--29j7

But you're entitled to your opinion. I just understand the nature of this sort of situation a bit better than most, I suspect.

**Comment by artsgirl** [comment]
I'm not quite sure why you appear to be making assumptions about *my* knowledge of the situation, but I've been a programmer since 1999 and a business owner since 2009. At the end of the day... I'm not here to make donations to someone in the hopes that he will maybe, someday, respond to support queries. I've said this before but it doesn't appear to have gotten through so I'll say it again: I'm actually referring much more to *pre-covid* support issues. I have support requests I've submitted through both github and the support form on the MailSpring site from mid-2019 that have not even been *responded to*, let alone addressed or resolved. I'm not expecting *anyone* to respond "right away" and I'm not sure why you're so insistent that I am. I am saying that this is clearly an ongoing problem, and maybe covid has made it worse, but it was a problem long before that time.

As a consumer, I have every right to say to someone I've bought a service from, "Hey, this service is not working as promised and you regularly have not responded to my requests," and give him one final chance to fix his business model before I take my business elsewhere. I'm not sure how that qualifies as "complaining about someone else's work." I'm simply going through established support channels to try to get support, and being blindsided in the process by some Mailspring fanboy who assumed he knows more about everything than me.

I no longer need to explain or defend my actions to you. You clearly will only hear what you want to no matter what I say. This is my final word (to you) on the subject.

if the *actual business owner* cares to respond to any of my as-yet-unresolved support requests, my Mailspring account renews in about six weeks and I've been monitoring carefully for the past year to determine if I will renew.

**Comment by CodeMouse92** [comment]
> ...being blindsided in the process by some Mailspring fanboy who assumed he knows more about everything than me.

Well, if you choose to distort my statements into that hilarious caricature, go right ahead. I'm merely sick of the entitled vitriol independent software developers have to put up with. I kindly notified you that the project was not "abandoned" as the other person rather divisively claimed, and you responded in quite a hostile manner.

> You clearly will only hear what you want to no matter what I say.

I believe this is called "projection".

Anyway, as you said, you don't intend to respond to me further. That's just as well for everyone. I respond for the sake of teachable people reading.

To anyone reading: **Demanding indie developers jump right on responding to bug reports on projects they run on their own time is not appropriate behavior. Ever. Just because you pay a few bucks for premium to support that indie side-project doesn't change that reality.**

Spend a few months drowning in backlog in addition to your full time job, and you'll understand.

**Comment by CodeMouse92** [comment]
In December 2020, Mailspring's AWS servers experienced some technical issues that interfered with several features, including Mailspring accounts, link tracking, and open tracking. These issues have since been resolved.

If you experience these issues again, please open a Service Issue report on our new Discourse community: https://community.getmailspring.com/

Thank you!

-The Mailspring Team
