### ISSUE TITLE
Feature Requests (disappointeed from paid version)

### ISSUE THREAD

**Issue by berti92** [Foundry376/Mailspring#2232]
Hello dear developers,

thank you very much for your work.

I'm a paid user and I'm a bit disappointed, because
I think the features are not really thought out.

Here are a few thoughts:

- I don't find any option to set a subject for a template. I always must manually create a subject for a inserted template.
- If I go through the template fields via tab and do not replace them than it is not possible to reach the fields via tab if I don't click in the body of the mail.
- The highlighting of the template fields (if you select them via tab) is hard to see if you use the dark theme.
- Maybe its better to get a stepable form or popup to replace the fields.
- For me the calendar is very important and this feature should be prioritized high and it should be possible to use any calendar.
- A mobile app would be nice, because than it's possible to snooze mails and use templates on mobile, too.

I know this is not really a issue or ticket, but I think it's not bad to list it here to get maybe more feedback from other users.

**Comment by valentt** [comment]
> I'm a paid user and I'm a bit disappointed, because

We are in the same situation, but I'm afraid that we should search for a better option because Mailspring is abandoned unfortunately. https://github.com/Foundry376/Mailspring/issues/2231

If you find a really good alternative please let us all know.

**Comment by berti92** [comment]
@valentt Oh, I didnt know that thank you for  your answer. Sadly I do not know any alternatives, EMClient looked promising, but it doesn't have a linux version which is crucial for me.

**Comment by CodeMouse92** [comment]
@berti92 Unfortunately, @valentt spoke very hasily. Mailspring is NOT abandoned! The main developer is around, but 2020 has messed with him like it did us all.

@valentt Stop trolling. You, sir, are out of line. The developer already responded to your issue. Please go back and delete all your "this project is abandoned" comments. They are harmful to the project.

**Comment by berti92** [comment]
@CodeMouse92 Thank you, I already saw it and responded to this issue. :)

**Comment by CodeMouse92** [comment]
I think it's also worth pointing out, this is a one-man side project. The premium model just helps him dedicate more time than he otherwise could, and features take a lot of time to develop.

Maybe if some of us were to help clear some of the bugs and planned features, it would help.

P.S. I only discovered this project recently, but I've encountered more of these sorts of situations than I can count. I'm not picking on anyone here.

**Comment by CodeMouse92** [comment]
@berti92 As you may have seen, I'm now the Volunteer Community Manager for Mailspring, and I'm happy to report that Mailspring's development is moving forward now.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Because there are multiple feature requests here, would you be willing to open a separate Feature Idea thread on Discourse for each/ That way, each individual idea you had can get the attention it deserves.

In many cases, we're looking to encourage features to be added via pluins, rather than the core Mailspring app, but there are still areas where the core application can be improved. It's best to be able to consider this situation on a case-by-case basis.

I look forward to seeing you on the Mailspring Discourse community!
