### ISSUE TITLE
Bug: links in emails and signature corrupting

### ISSUE THREAD

**Issue by jrm2021** [Foundry376/Mailspring#2233]
when sending out emails with correct links in - these are not loading and redirecting to get mailspring

eg 

https://link.getmailspring.com/link/A141B615-FD2A-4FC3-8D96-FFA0210943A3@getmailspring.com/0?redirect=https%3A%2F%2F

this is happening with all links including in signature 

also read receipts are not working again

- please resolve asap - I am also a paying user

**Comment by artsgirl** [comment]
+1, images in signatures are not loading, and links are being corrupted as stated by jrm2021. I too am a paid user going on three years now, need resolution.

**Comment by CodeMouse92** [comment]
I'm not a developer, but thinking it through, this seems to be connected with the AWS service interruptions and problems Ben (project owner) described over the past couple days.

Turn off Link Tracking, and see if the problem persists. https://foundry376.zendesk.com/hc/en-us/articles/115001875431--Enable-read-receipts-link-tracking-and-notifications

**Comment by CodeMouse92** [comment]
In December 2020, Mailspring's AWS servers experienced some technical issues that interfered with several features, including Mailspring accounts, link tracking, and open tracking. These issues have since been resolved.

The problems described in this issue are consistent with the link tracking feature and the Mailspring server outage.

If you experience these issues again, please open a Service Issue report on our new Discourse community: https://community.getmailspring.com/

Thank you!

-The Mailspring Team
