### ISSUE TITLE
Bug: 504 on windows download

### ISSUE THREAD

**Issue by gareins** [Foundry376/Mailspring#2234]
**Describe the bug**
When downloading windows version I get 504 gateway time-out

**To Reproduce**
1. Be in Slovenia? (I don't know if this is a local problem)
2. Google "mailspring"
3. Download for Windows

**Expected behavior**
Download the app, no need to go to github releases to download it

**Screenshots**
![image](https://user-images.githubusercontent.com/3583035/102612580-431b5600-4131-11eb-8b5b-e8ada80a4a0d.png)

**Setup: (please complete the following information):**
 - OS: up-to-date Win10
 - up-to-date Firefox

**Comment by Phylu** [comment]
@gareins There was a server issue last month. Can you check if this is resolved already?

**Comment by CodeMouse92** [comment]
In December 2020, Mailspring's AWS servers experienced some technical issues that interfered with several features, including Mailspring accounts, link tracking, and open tracking. These issues have since been resolved.

If you experience these issues again, please open a Service Issue report on our new Discourse community: https://community.getmailspring.com/

Thank you!

-The Mailspring Team
