### ISSUE TITLE
Bug: Can not change or cancel my pro subscription I receive an error 500

### ISSUE THREAD

**Issue by berti92** [Foundry376/Mailspring#2241]
**Describe the bug**
I can not change or cancel my pro subscription I receive an error 500

**To Reproduce**
German locale
* Open Mailspring  settings 
* Abonnemeent
* Bezahlung verwalten
* Firefox opened
* "Ändern Sie Ihr Mailspring-Abonnement"
* "Halten Sie Mailspring pro"
* Now I receive an 500 error

**Comment by CodeMouse92** [comment]
In December 2020, Mailspring's AWS servers experienced some technical issues that interfered with several features, including Mailspring accounts, link tracking, and open tracking. These issues have since been resolved.

If you experience these issues again, please open a Service Issue report on our new Discourse community: https://community.getmailspring.com/

Thank you!

-The Mailspring Team
