### ISSUE TITLE
[Feature Request] Allow read pane to be infinitely wide and use all space

### ISSUE THREAD

**Issue by MrHamel** [Foundry376/Mailspring#228]
What operating system are you using? Windows 10

What version of Mailspring are you using? 1.06

**Bug?**

Cannot disable the contact side bar and unable to make the read pane take the full available space between the list of emails all the way to the right of the display.

**Comment by bengotow** [comment]
Hey! This isn't documented anywhere I don't think, but if you click this button above the contact sidebar it'll toggle it off. Definitely better for narrow displays 👍 Will get this added to the knowledgebase!

![image](https://user-images.githubusercontent.com/1037212/31856291-20848d52-b672-11e7-8375-d15a03474122.png)

**Comment by techhelper1** [comment]
Thanks for that tidbit.

Now If its possible, I would like the read pane to take the full space between the list of emails and right side where the contact sidebar was. The center aligned read pane with gaps drives me up a wall because it constricts the size of HTML emails, which makes them smaller compared to other clients.

**Comment by bengotow** [comment]
Ahh gotcha—this sort of thing? (Screenshot below.) There's no way to change that yet. Right now it does that on purpose because text-based emails get hard to read at long line lengths but we should definitely make it an option in the future.

![image](https://user-images.githubusercontent.com/1037212/31856323-e735b89a-b672-11e7-945b-6cd97f74c50d.png)

**Comment by techhelper1** [comment]
Yes, that is exactly it.

**Comment by h4d3z** [comment]
This is still not fixed yet?
