### ISSUE TITLE
Intezer Protect reports Coinminer?

### ISSUE THREAD

**Issue by Strykar** [Foundry376/Mailspring#2365]
Hi, I use the paid version and noticed this in the security logs, please advise:

![Screenshot from 2022-02-14 05-10-56](https://user-images.githubusercontent.com/2946372/153780688-3ca9b0ff-7823-4afe-92fd-f582869f9bd5.png)

![Screenshot from 2022-02-14 05-11-00](https://user-images.githubusercontent.com/2946372/153780691-883c64b7-e7a6-41f3-a209-1b0e5217a0a5.png)

**Comment by Phylu** [comment]
Hi @Strykar 

of course, there should be no crypto miner running with Mailspring. What the client actually does is to use the current mail sync engine as a binary. Maybe this is flagged by the scanning system.

Can you please verify that the binary in question is really malicious by checking it using a virus engine such as https://www.virustotal.com

If it flags the file as malicious, please provide information how you downloaded Mailspring, so that we can ensure that there is nothing malicious in the official download channels.

**Comment by Strykar** [comment]
Looks clean: https://www.virustotal.com/gui/file/830e78b8840e821854992c3f0a0e7d248b38f929e5da1d99b228881e501a22ea?nocache=1
![Screenshot from 2022-02-16 07-33-07](https://user-images.githubusercontent.com/2946372/154182363-cbbaab7e-f995-45e7-a0a8-f5c466d54320.png)
The package is from Arch's AUR and appears to repackage your supplied .deb: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mailspring

Perhaps this is a false +ve and I should whitelist that binary?

**Comment by Phylu** [comment]
Thanks a lot for checking. This seems to be a false positive. It would be great if you can report it as such to the anti virus engine supplier.

I am therefore closing this issue here.
