### ISSUE TITLE
[Feature request] Ctrl/Cmd + Enter to send email

### ISSUE THREAD

**Issue by prajapati-parth** [Foundry376/Mailspring#280]
##### What operating system are you using?
... Ubuntu 16.04 LTS

##### What version of Mailspring are you using?
... 1.0.6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
... None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
... no

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
... Yes. When using Gmail in browser

Having the ability to send the email, when focus is inside the email composer, on pressing Ctrl/Cmd + enter would be a great feature. It would come handy as using just the keyboard would reduce mouse/touchpad interaction.

Thanks.

**Comment by bengotow** [comment]
Hey! This works if you select the `Gmail` keyboard shortcut set in Preferences > Keymaps. You can check what the keyboard shortcut is (or change it to something else by clicking it) in the Composer section:

I wonder if it's not working for you because it's bound to command and not control maybe?

![image](https://user-images.githubusercontent.com/1037212/32237865-56ac599c-be23-11e7-8796-e286d818234b.png)

**Comment by prajapati-parth** [comment]
Sure. I'll give it a try and let you know. 👍
