### ISSUE TITLE
Mail sent from Mailspring ends up in spambox from certain providers

### ISSUE THREAD

**Issue by knireis** [Foundry376/Mailspring#284]
When i sent a mail with Mailspring to a @ziggo.nl mailaddress (which is a large internet provider in the Netherlands), the mail ends up in the spambox.

Sending the same mail from the same acount using webmail, there is no problem. So i suspect Mailspring to be the cause of this. Maybe the read confirmation technique causes some providers to see the mail as spam? Are there any other reports like this?

**Comment by bengotow** [comment]
Hey!  I haven't heard of this in the past, but let's definitely leave this open and see if anyone else has seen similar behavior. Could you try sending me an email at ben@foundry376.com both from Mailspring and from your webmail? I'm interested to see if your webmail is adding any other headers Mailspring is missing. It could be that your ziggo.nl mail provider does not apply the same trust to any third-party clients as they do to their own webmail.

**Comment by oserban** [comment]
@knireis have you tried disabling the open tracking and link tracking options? 
In my case, that was the issue with certain providers.

**Comment by knireis** [comment]
Today i received this headsup from a customer:

When i send a mail with mailspring to a mailaddress hosted at siteground, this mail is defined as a potential threat- phishing. Because of that the receiver of the mail is not able to reply to this mail.

These issues might be related

**Comment by knireis** [comment]
@oserban how can i disable the tracking? don't see it in the options

**Comment by knireis** [comment]
@bengotow I have send you the requested mails

**Comment by knireis** [comment]
I can confirm that switching off the open tracking and link tracking options solves the issue

**Comment by bengotow** [comment]
Hey! Thanks for digging in to this folks—do you mind if I add your screenshot to the knowledge base @oserban? Thanks for making that.

I think the mail provider must be seeing the 1px tracking pixel used to implement read receipts and saying "oh this must be a marketing email." I haven't seen that before, but we'll definitely need to inform folks about this better. I'm working on a new version of onboarding and I'm going to try to make it easier to opt-out of these features early on as well.

**Comment by oserban** [comment]
@bengotow sure, please use it.

**Comment by WasimOfNazareth** [comment]
Hello! I'm having a very similar issue. Ever since beginning to use Mailspring in January, my gmails have been increasingly ending up in recipient's spam folders. I've been on Google One support several times to figure it out and they suggested it might be HTML signatures, but got rid of those and still doing it weeks later. A friend recently sent me screenshots and message header text of my emails in their quarantined spam box and reason for quarantine, and the Message ID does show an @getmailspring address and wondering if that's getting flagged by Gmail as spam (screenshots attached - mine are the two circled in red)?

 I don't know much about all this technical stuff, I just know that I've increasingly missed out on jobs and bids aren't going through in some cases, even to contacts that are in my address book and vice versa, as well as when I just simply reply to an email string that's been alive for days, randomly some of the replies will just end up in their SPAM folder.

I've stopped using Mailspring for now and trying another client to see if it changes things or until I can figure out why it's been doing it since I've started using Mailspring. I like Mailspring, but not enough to lose out on potential work. I'll keep an eye on this thread and others and hope for a fix/solution/reason/etc. 

![mailspring-spam-gmail-issue-1](https://user-images.githubusercontent.com/53359166/61988874-4cf06680-afdc-11e9-870f-603325d422e4.jpg)
![mailspring-spam-gmail-issue-2](https://user-images.githubusercontent.com/53359166/61988875-4cf06680-afdc-11e9-8d03-c80de65f3315.jpg)

**Comment by fireedo** [comment]
> Hello! I'm having a very similar issue. Ever since beginning to use Mailspring in January, my gmails have been increasingly ending up in recipient's spam folders. I've been on Google One support several times to figure it out and they suggested it might be HTML signatures, but got rid of those and still doing it weeks later. A friend recently sent me screenshots and message header text of my emails in their quarantined spam box and reason for quarantine, and the Message ID does show an @getmailspring address and wondering if that's getting flagged by Gmail as spam (screenshots attached - mine are the two circled in red)?
> 
> I don't know much about all this technical stuff, I just know that I've increasingly missed out on jobs and bids aren't going through in some cases, even to contacts that are in my address book and vice versa, as well as when I just simply reply to an email string that's been alive for days, randomly some of the replies will just end up in their SPAM folder.
> 
> I've stopped using Mailspring for now and trying another client to see if it changes things or until I can figure out why it's been doing it since I've started using Mailspring. I like Mailspring, but not enough to lose out on potential work. I'll keep an eye on this thread and others and hope for a fix/solution/reason/etc.
> 
> ![mailspring-spam-gmail-issue-1](https://user-images.githubusercontent.com/53359166/61988874-4cf06680-afdc-11e9-870f-603325d422e4.jpg)
> ![mailspring-spam-gmail-issue-2](https://user-images.githubusercontent.com/53359166/61988875-4cf06680-afdc-11e9-8d03-c80de65f3315.jpg)
> 
> @bengotow

happend to me too, need to fix this annoying spam email
for now I'm not using mailspring until this fixed

**Comment by WasimOfNazareth** [comment]
> > Hello! I'm having a very similar issue. Ever since beginning to use Mailspring in January, my gmails have been increasingly ending up in recipient's spam folders. I've been on Google One support several times to figure it out and they suggested it might be HTML signatures, but got rid of those and still doing it weeks later. A friend recently sent me screenshots and message header text of my emails in their quarantined spam box and reason for quarantine, and the Message ID does show an @getmailspring address and wondering if that's getting flagged by Gmail as spam (screenshots attached - mine are the two circled in red)?
> > I don't know much about all this technical stuff, I just know that I've increasingly missed out on jobs and bids aren't going through in some cases, even to contacts that are in my address book and vice versa, as well as when I just simply reply to an email string that's been alive for days, randomly some of the replies will just end up in their SPAM folder.
> > I've stopped using Mailspring for now and trying another client to see if it changes things or until I can figure out why it's been doing it since I've started using Mailspring. I like Mailspring, but not enough to lose out on potential work. I'll keep an eye on this thread and others and hope for a fix/solution/reason/etc.
> > ![mailspring-spam-gmail-issue-1](https://user-images.githubusercontent.com/53359166/61988874-4cf06680-afdc-11e9-870f-603325d422e4.jpg)
> > ![mailspring-spam-gmail-issue-2](https://user-images.githubusercontent.com/53359166/61988875-4cf06680-afdc-11e9-8d03-c80de65f3315.jpg)
> > @bengotow
> 
> happend to me too, need to fix this annoying spam email
> for now I'm not using mailspring until this fixed

Oh yeah, I gave up on their nonsense. Been using emClient since and have had no problems. Done with Mailspring.

**Comment by CodeMouse92** [comment]
Based on everything in this thread, this is based on link tracking and read receipts being on. If you're experiencing this problem, turn those off.
