### ISSUE TITLE
Empty Inbox and use of virtual folders

### ISSUE THREAD

**Issue by bynicolas** [Foundry376/Mailspring#309]
##### What operating system are you using?
macOS

##### What version of Mailspring are you using?
v1.0.7-664203d8

--

**Bug?**
##### Mail doesn't show up in Mailspring's inbox.  
I believe the issue is related to the use of virtual folders within Dovecot and the way Mailspring treats messages.

I'm not 100% sure, but it looks like Mailspring will remove message from the inbox if it finds the message within another (virtual) folder.

This is annoying and renders Mailspring unusable since I never get notification of new emails as Mailspring relocates them out of the inbox.

Also, I'm not sure if this is related, while it should look like it is, but I don't see the unread email count for each folders, even though there is unread mail in the folder.

**Comment by jGleitz** [comment]
@bynicolas I have filed a very similar​ issue (#304). Can you check whether you get comparable sync log lines (about unlinking the messages)? We could then merge the issues.

Regarding unread counters, have you seen that there is a setting for that, which is deactivated by default? So unless you activate it, disabled unread counters for other folder seems to be the expected behaviour.

**Comment by bynicolas** [comment]
Yep, I guess this is the same issue,

I have a few 

`[background] [info] Sync loop deleting unlinked messages with phase 2.` and `[background] [info] Sync loop deleting unlinked messages with phase 1.` in the logs and then a bunch of `[info] -- Removing "MESSAGE SUBJECT"`

As for unread count, I wasn't aware of the setting, I guess it was changed in between versions as it was showing count on the first version of Mailspring.

I'll be closing this issue as #304 seems to be the same problem
