### ISSUE TITLE
[Feature Request] Google Apps IMAP Disabled

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#31]
Using Latest version, for any OS, Gmail Apps account with no admin access

I use Google Apps for Work. My admin has IMAP disabled. As such, I must either use Gmail client (which sucks) or [GSSMO](https://support.google.com/a/users/answer/153871?hl=en) with Outlook (and outlook is power-intensive).

Is it possible to implement a GSSMO-like solution that accesses email without using IMAP?

**Comment by bengotow** [comment]
Hey @Modelmat! Unfortunately there's not much we can do if your Google admin disables third party apps using IMAP. There's a Gmail API that is separate from IMAP, but Mailspring would need to be completely re-written to use that instead. Sorry for the hassle!

**Comment by Modelmat** [comment]
@bengotow That's irritating. Would this be possible via an extension?

**Comment by Modelmat** [comment]
@bengotow Hello?

**Comment by bengotow** [comment]
Oh hey—I thought about this a bit more, and I think 1) connecting to Gmail without IMAP involves using the Gmail API which would be extremely time consuming to implement, since it's basically a re-write of the sync engine against a new protocol. We could use that same amount of time to support Exchange, which would apply to many more people, and 2) your admin clearly intends to block third party clients. Working around that limitation might make Mailspring work, but they likely wouldn't be happy with you. I bet if they could block the Gmail API they'd do that too ;-)

**Comment by Modelmat** [comment]
I think it might be more of a safety thing. There are thousands of users, and many people don't have the safest passwords. IMAP would open up the pathways to hacking, especially considering how our emails are `firstname.lastname@server.com`
