### ISSUE TITLE
Custom themes can't be compiled from 1.0.8

### ISSUE THREAD

**Issue by davidsharp** [Foundry376/Mailspring#326]
Since updating to 1.0.8, my custom themes fail to compile, as the base colour variables are missing (`variable @gray is undefined`). While this is a problem that could be fixed in my theme by setting those variables myself, this will also affect everyone using the `nylas-mail-theme-starter`, which is still the canonical basis for themes.

![screen shot 2017-11-10 at 12 34 30](https://user-images.githubusercontent.com/5731838/32658790-996f230c-c613-11e7-9893-afb371b64fd8.png)

Because it causes a JS error, it also means I can't get far enough to be able to change the theme through the UI.

**Comment by AvexiMatt** [comment]
A quick work around to get it working on a different theme,
Load the config.json file
C:\Users\<Username>\AppData\Roaming\Mailspring

and change 
 the Theme to something like this
      "theme": "ui-light"

**Comment by bengotow** [comment]
Hey! Sorry for the hassle—didn't realize there were custom themes floating around already!

To fix the theme, you probably just need to add this line to the top of the `mailsprung/ui-variables.less` file. We changed a few things and it no longer assumes you want to use the base variables file!

```
@import 'base/ui-variables';

```

**Comment by davidsharp** [comment]
Cool, that's fixed it. I definitely think it makes more sense for the import to be explicit, but I wasn't initially sure where those variables were coming from. :+1:

**Comment by opes** [comment]
@bengotow I'm working on porting over the [Material](https://github.com/opes/mailspring-material) theme that was available for Nylas and ran into this issue. When I import the `base/ui-variables`, it fixes the aforementioned errors, but the colors are completely different than what I have specified. Are there more complexities that need to be addressed aside from what's stated here and in the [migration guide](https://foundry376.zendesk.com/hc/en-us/articles/115001918391-How-do-I-update-an-N1-Nylas-Mail-theme-for-Mailspring-)?

Love the work you're doing on Mailspring, by the way. Looking forward to contributing to the project!

**Comment by bengotow** [comment]
Hey @opes - hmm interesting, thanks for letting me know it didn't work right off the bat. Basically what we're doing is 1) making it so that LESS files have to include `ui-variables` to reference / use them and 2) requiring that themes that want to modify `ui-variables` define their own version of the file that overrides values from the base theme (`base/ui-variables`). 

Sorry it's kind of a messy migration... before, we were including all the base variables, followed by all your theme LESS, followed by the LESS we wanted to compile for every file, which was crazy slow and meant that sometimes weird things could happen because things were in your LESS scope you didn't explicitly ask for.

Let me know if you got Material working!

**Comment by edipox** [comment]
Hi everyone! 
[Ido](https://github.com/edipox/n1-ido) is working on Mailspring `1.1.4` now 😄
