### ISSUE TITLE
Sending mail with photos

### ISSUE THREAD

**Issue by orcunbaslak** [Foundry376/Mailspring#338]
Hello,

When I send email from the Mailsprng, inline images does not show at other clients. How can I fix it ?

Br,

![email](https://user-images.githubusercontent.com/12577988/32778981-13ae73fc-c94d-11e7-9ba8-97c953d66c2a.JPG)

**Comment by bengotow** [comment]
Hey! Thanks for filing this - this has been fixed by 69c7a7aea74357153c3181ac1a0e014f7e180d70 and will be in the 1.0.9 release early next week. Stay tuned!

**Comment by AndreaBarghigiani** [comment]
I @bengotow sorry to bother you but I would like to know when will be shipped the 1.0.9 version because I have a similar problem but when I try to read (instead of send) the email that contain inline images.

![schermata 2017-11-29 alle 10 33 14](https://user-images.githubusercontent.com/190159/33368080-f02e4632-d4f0-11e7-8d45-b3171952e6ce.jpg)

The images are available at the bottom of the email but in this way is not useful especially when someone sends many images like in the screenshot above.

Anyway I am running Mailspring on macOS 10.13.1.

I understand that you're busy and keep up an open source project is really difficult so please don't read this request with some kind of pressure. I'm here just to understand how the project is evolving.

**Comment by bengotow** [comment]
Hey folks—the issue with sending inline images was fixed and `1.0.10` shipped yesterday.

The problem you're seeing when reading your mail may not be related. Can you grab the update and see if that still happens for you?

**Comment by SKOx0** [comment]
I'm using 1.0.10
![23](https://user-images.githubusercontent.com/5200285/33951862-4c4e29f6-e017-11e7-8431-c2424c4e895a.jpg)

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a lot of other small improvements. You can grab the latest version from https://getmailspring.com/download.
