### ISSUE TITLE
"Edit > Install Theme" does nothing

### ISSUE THREAD

**Issue by ReekyMarko** [Foundry376/Mailspring#36]
First of all, thanks for the whole team for your great work on Mailspring! I've never been as hyped about an email client before 😄 

So far, the only problem for me, besides the SSL errors on IMAP/SMTP accounts, is that I can't install themes. The "Install Theme" button simply does nothing. With my limited knowledge, I'm unable to find any sort of trace why is this happening. I opened up Mailspring from the CLI and it doesn't spit out any errors there when clicking the button. I'm running KDE on Arch Linux.

**Comment by bengotow** [comment]
Hey! This will be fixed in the next release—actually just pushed 1a9364d229d0d5fa0b318e9fcb60d5a53150a47a which should do it. The only caveat is that some Nylas themes might have to be adjusted a bit, because the new package manager doesn't dig for files as much. There's a short migration guide here: https://foundry376.zendesk.com/hc/en-us/articles/115001918391. We might need to submit PRs to a few of the themes.

**Comment by bengotow** [comment]
Version 1.0.2 just shipped - have fun making themes / plugins! I'm working to build a theme / plugin browser in an update later this year, so the installation process should be getting much better soon.
