### ISSUE TITLE
[Feature Request] Global directory for Mailspring plugins

### ISSUE THREAD

**Issue by ruslansin** [Foundry376/Mailspring#363]
##### Are there any related issues?
There are no any related issues

##### What operating system are you using?
Arch Linux

##### What version of Mailspring are you using?
1.0.8.5a837d0e

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No plugins

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, it concerns installation of Mailspring plugins, not email accounts.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
It would be great to have ability to install plugins for all users on your system. 
It could be used for plugins installation as optional dependencies for the Mailspring package.

**Comment by H0tmilk** [comment]
Same here (Ubuntu 16.04, Gmail account, no plugins)

**Comment by TeNNoX** [comment]
*bump* :cry:

**Comment by CodeMouse92** [comment]
While we do have plans of adding a formal Plugins UI in Mailspring itself at some point in the future, we have meantime created a central place in our new Discourse community for sharing plugins: https://community.getmailspring.com/c/plugins/8

Please join there, and encourage your favorite plugin developers to post! (As you can see, it's a bit quiet there right now, but only because we've just started.)
