### ISSUE TITLE
The Word files that I attach in an email arrive at the recipient, but when I open them there is nothing in those documents. They leave blank, without anything written

### ISSUE THREAD

**Issue by CarlosRebolledo** [Foundry376/Mailspring#425]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
La última versión (1.0.10)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Redbooth y MixMax

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail de Google Suite

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Hasta el momento no he visto nada más que lo relatado

--

**Feature Request?**
Conectarse con Google Drive Teams
##### Does this feature exist in another mail client or tool you use?
Sólo Gmail, hasta el momento

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - It looks like this is probably the same issue that was reported in #370 and #419. I was able to track that down this evening and it'll be fixed in the next release (1.0.11). Stay tuned!

--- machine translation ---

¡Oye! Gracias por informar esto: parece que este es probablemente el mismo problema que se informó en los números 370 y 419. Pude rastrear eso esta noche y se solucionará en la próxima versión (1.0.11). ¡Manténganse al tanto!

**Comment by bengotow** [comment]
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Enjoy!
