### ISSUE TITLE
[Feature Request] POP3 Support

### ISSUE THREAD

**Issue by waliarubal** [Foundry376/Mailspring#45]
Hey good to see such a great re-write of Nylis. The problem I had with Nylis was that it didn't had support for POP3. Do you guys have it? I would like POP3 support added as I have accounts which only use POP3.

**Comment by bengotow** [comment]
Hey @waliarubal! Thanks for reaching out—POP3 support has been fairly low on the priority list because most modern mail services offer IMAP as well. (If you can, I'd strongly recommend you switch to a mail provider that uses IMAP and supports modern encryption features like STARTTLS.)

The Mailcore2 library that Mailspring relies on for IMAP support does support POP3, but client behaviors are pretty different for IMAP because emails are removed from the mail server when you download them. We'd likely need to do a lot of testing of existing features to make sure they worked with POP3.

**Comment by waliarubal** [comment]
Thanks @bengotow for answering my query. The point being email provider I am using does support IMAP but these guys are reluctant to give IMAP details as per their policies. I am currently stuck with emClient and looking to switch to MailSpring as soon as it supports POP3. I like the UI of MailSpring too much as it resembles Apple mail. 👍 Do let me know when is it on your road map to support POP3 officially so that I can make the switch.

**Comment by bg15407** [comment]
Any due date ??
Pls provide my work mail does not have IMAP
Thanks

**Comment by PoacherBro** [comment]
me too, as work email not support IMAP.

**Comment by dayfuaim** [comment]
So for me, my corp mail server does only POP3.

**Comment by rbbernardino** [comment]
I was checking some issues here and found this.
I have a suggestion for you guys: just create (or use your) gmail account and sync your POP3-only address to this gmail account. Then you just add it to Mailspring! I have all my "side-accounts" synced to one main gmail account with labels auto-set when necessary.

**Comment by rabbee** [comment]
me too, as work email not support IMAP.

**Comment by swbrains** [comment]
I would also like to see POP3 support

**Comment by bengotow** [comment]
Hey folks! Thanks for chiming in over the years—as of 2020 I can say we will definitely never support POP3 in the Mailspring project. It's becoming less and less common for mail providers not to support IMAP, and I'm planning to invest developer time in things that will have more longevity like calendar sync and Exchange. Thanks 🙏
