### ISSUE TITLE
Is 32-bit possible?

### ISSUE THREAD

**Issue by tukoz** [Foundry376/Mailspring#467]
Hi, looking for alternative mail client that's easy-to-use and resource friendly for low-pro devices. Precisely:

- 32-bit Debian and Ubuntu LTS based OSes is what works best with the 2 GB max Intel Atom **netbook** I presently use while on the move.
- a majority of the computers we refurbish at the local DIY/fablab are powered by 32-bit GNU/linux OSes (Debian, Ubuntu LTS, Raspbian Pixel and Mageia) with 1-2 GB RAM --and believe me they run well ;)

Atm we ship all the afforementionned systems with Thunderbird.

Does the package allows to be compiled on a i686 GNU/Linux OS?
I couldn't find an indication about this on <http://support.getmailspring.com/hc/en-us/>

**Comment by bengotow** [comment]
Hey! I believe Electron is available for 32-bit Linux so we should be able to package a 32-bit build. That said, Mailspring uses about 2x as much RAM as Thunderbird (mostly because the UI is built on Chromium - it's roughly equivalent to Chrome with two tabs open). The experience would be /alright/ on a machine with 1-2GB of RAM, but I imagine something older like Thunderbird or Evolution would offer a better overall experience on a small machine.

That said, they're improving Chrome's memory use in almost every release these days, might be more reasonable sometime soon!
