### ISSUE TITLE
Email signature links having injected urls (Potential Privacy Risk)

### ISSUE THREAD

**Issue by estebansanti** [Foundry376/Mailspring#480]
When editing the Email Signature html, we see mailto and normal urls. But on sent emails, the person gets these links:

https://link.getmailspring.com/link/local-334cc142-62a9@xxxxxxx/0?redirect=mailto%3Axxxxxxx%40xxxxxxxxxx.xxx&recipient=me%40xxxxxxxxxxx.xxx

(info omitted with 'x')

Why are we using this instead of a traditional 'mailto:' and 'uri path'.

What's the reasoning?

**Comment by bengotow** [comment]
Hey! This happens when you have `link tracking` enabled in the composer (https://foundry376.zendesk.com/hc/en-us/articles/115001875431--Enable-read-receipts-link-tracking-and-notifications). I think there's another issue open about the inclusion of the `recipient` field, and we'll probably change that in an upcoming release. (Right now the recipient field allows Mailspring to tell you which recipients have opened your emails or clicked your links when the email is addressed to multiple people.)

**Comment by estebansanti** [comment]
Look at me raising flags because of a feature, not a bug. 

@bengotow Thanks.
