### ISSUE TITLE
Version 1.0.12 for mac bug.

### ISSUE THREAD

**Issue by ok1ok1** [Foundry376/Mailspring#487]
Version 1.0.12 for mac is broken. Constant "Encountered an error while syncing" message. Behavior started immediately after update.

**Comment by bengotow** [comment]
Hey! Can you open Mailspring, go to Developer > Show Mailsync Logs and then post the last hundred lines or so of `mailsync-***.log`? You can also send them to support@getmailspring.com. Thanks—

**Comment by bengotow** [comment]
Turns out this happens because `Inbox` is a label within `All Mail`. When you move the message to the `Trash`, Mailspring optimistically decrements the `All Mail` unread count and increments the `Trash` count, but doesn't modify the `Inbox` count (because the Inbox label actually stays on the message while it's in the trash so that "Remove from Trash" puts it back where it was.) I've fixed the logic and confirmed that it's working now. Will ship in the next release!

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and lots more. You can grab the latest version from https://getmailspring.com/download.
