### ISSUE TITLE
Ugly menu and file picker in linux Snapcraft release

### ISSUE THREAD

**Issue by luski** [Foundry376/Mailspring#495]
##### Are there any related issues?

No

##### What operating system are you using?
Ubuntu 17.10, Ubuntu 16.04

##### What version of Mailspring are you using?
1.0.12

--

**Improvement**

Current file picker in linux systems is the ugliest dialog window I've seen since Windows 95:
https://preview.ibb.co/n0CErb/Screenshot_from_2017_12_30_10_46_36.png
It is displayed when we try to save an attachment.

My improvement proposal is to use the gtk3 file picker which is provided by the electron (as far as I see, Mailspring is implemented with electron?).

**Comment by bengotow** [comment]
Haha wow that is /hella/ ugly. This is currently because Mailspring uses Snapcraft on Linux, and snapcraft doesn't inherit from the system theme correctly. Electron is in the process of switching to GTK3 (I think the 1.8 or 1.9 release will ship GTK3 - we'll be able to move to 1.8 when they release 1.8.2-beta4) and that might make it better, but I'm not sure offhand. I think the issue to follow on the Snapcraft side is https://forum.snapcraft.io/t/use-the-system-gtk-theme/496/36. Bug them there and let's see if we can get it pushed forward!

**Comment by ferlanero** [comment]
The Electron integration with GTK3 sounds really great as Mailspring snap looks really ugly in GTK3 environments. My question is: Will Mailspring Snap supports GTK3 automatically through Sanp automatic updates?

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.
