### ISSUE TITLE
[Feature request] Add snooze setting to surface unsnoozed emails

### ISSUE THREAD

**Issue by bemky** [Foundry376/Mailspring#54]
**This was one of my favorite features of Mailbox**
When mailbox brought an email tread out of snooze, it would mark it unread and bring it to the top of the inbox. This made it really nice for managing your inbox and bring things back to your attention later. Even just marking as unread would help.

Currently, snooze brings items back into your inbox, but unless you're running a perfect inbox zero (meaning you actually make it to zero often) email threads that I want to bring to my attention later are hidden in my inbox.

Expected behavior for this may vary depending on user. With Mailbox it came naturally for me, but I understand opinions may vary. Maybe it should be a setting.

![spark-1 4-for-ios-snooze-options-001](https://user-images.githubusercontent.com/841033/31281999-d4277606-aa76-11e7-8751-fd7f9dbff3af.png)

![9021-464-140421-mailbox-l](https://user-images.githubusercontent.com/841033/31282002-d6c9d28c-aa76-11e7-8b45-24c99a8a2521.png)

**Comment by bengotow** [comment]
Hey! Thanks for posting this - we actually already have code to re-surface emails at the top of the inbox for "Send Reminders" (which alert you if nobody has replied after X days). We should definitely be able to add this!

**Comment by bengotow** [comment]
@casuallancelot's changes in #267 make snoozed emails become unread again when they unsnooze, so I think we're close to having this addressed! I'm going to see if we can also add an option for a full-blown "alert" that would bring it to the top of the inbox rather than just putting it back and making it unread. There's some code for Reminders that needs to be cleaned up, and I think we may be able to re-use it. Regardless, should be fixed in the next release!
