### ISSUE TITLE
[Bug] 'Select All' menu item does nothing

### ISSUE THREAD

**Issue by Andrewsudarikov** [Foundry376/Mailspring#550]
##### What operating system are you using?
Elementary OS 0.4.1

##### What version of Mailspring are you using?
1.0.12

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The issue is the following - when clicking on 'Select all' menu item nothing seems to happen. Doesn't matter if a specific folder or the whole inbox is selected. Neither does it work when a message in the folder is manually selected. '*+a' shortcut (both with Ctrl or Cmd) also does nothing.

**Comment by bengotow** [comment]
Thanks for reporting this—can you try pressing `*` and then `a` one after another (rather than at the same time?) If you have the Gmail keyboard shortcuts enabled that should work. Going to merge this in to #316

**Comment by grg2rsr** [comment]
suffering from the same, confirm that `*` and `a` indeed selects everything in Mailspring 1.1.2

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/select-all-messages/171

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team
