### ISSUE TITLE
Replying to some threads isn't working in 1.1.0

### ISSUE THREAD

**Issue by axfelix** [Foundry376/Mailspring#575]
I never experienced this in prior releases, so there's a chance it's not a new bug as I can only reproduce it on one thread.

Trying to reply to some threads just isn't working -- hitting the keyboard shortcuts `a` or `r` brings up a "Syncing your mailbox" in the bottom-left of client but it's dismissed automatically after a moment, and picking reply or reply-all from the drop-down just does nothing.

**Comment by axfelix** [comment]
It looks like sometimes, after this happens, when I return to the thread (e.g. after having sent a response from another client, and receiving a reply in my inbox again), there is a draft with the body text "null" stored inline in Mailspring.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this @axfelix — this is really interesting. I switched out the entire composer text editor in 1.1.0 and this issue is probably caused by the composer being unable to process the quoted text / body of the message you're replying to.

If you find a thread that exhibits this problem that isn't too sensitive, could you use your webmail to forward it to me at ben@foundry376.com? That'll make it much easier to fix! I receive automated error reports from the app as well, and I'll see if any of those match up with this.

**Comment by bengotow** [comment]
I think this is a dup of #589 — will see if that fix resolves this issue.

**Comment by axfelix** [comment]
Haven't encountered this in a while, closing (in the hopes it encourages you to fix https://github.com/Foundry376/Mailspring/issues/558 :) )
