### ISSUE TITLE
Messages from deleted accounts appear in search

### ISSUE THREAD

**Issue by paulocoghi** [Foundry376/Mailspring#576]
##### Description
When I do a search in Mailspring, messages from deleted accounts also appear in the results. In this particular case, messages from a Google account that I had added and deleted some time later.

##### Are there any related issues?

Apparently no.

##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
I identified this error since 1.0.12, and it remains in the latest version 1.1.0

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No third-party plugins installed.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
In my case, this occurred with a Gmail account.

**Comment by bengotow** [comment]
Hey! Yep this checks out now that I think about it - when you remove an account, Mailspring doesn't purge the search index of messages from that account because it's difficult to index into the search index by account. I'll see if I can fix this in the next release - I just added the ability to re-sync mail data for a specific account and I think the logic for this should be similar.

**Comment by paulocoghi** [comment]
I believe this can be closed now, with the release of 1.1.5!
