### ISSUE TITLE
[Feature Request ] Select and Filter all the mails based on specific sender

### ISSUE THREAD

**Issue by sathisz** [Foundry376/Mailspring#604]
##### What operating system are you using?
Linux Mint 18.3

##### What version of Mailspring are you using?
1.1.2-8ae17eae

**Feature Request**
Select all the emails from specific sender from all the email accounts and do actions like (mark_as_read, delete)

**Comment by bengotow** [comment]
You can use search to do this - merging this in to #83 and we'll see if we can add "Search for..." as an option in the dropdown menu when that ticket is addressed.

**Comment by CodeMouse92** [comment]
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/create-new-rule-from-address-in-the-context-menu/385/3

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team
