### ISSUE TITLE
Mail rules are not always applied

### ISSUE THREAD

**Issue by raqua** [Foundry376/Mailspring#605]
##### What operating system are you using?
Linux Mint 18.3

##### What version of Mailspring are you using?
1.1.2

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly Davmail + Exchange.

![screenshot from 2018-01-31 16-12-22](https://user-images.githubusercontent.com/1541886/35630926-e82f4c18-06a2-11e8-94ee-4e1430627f48.png)

I have mail rule set up as seen on the attached screenshot. 
It seems to be applied very inconsistently. Some emails fitting the rules are moved automatically, some are not. I have no idea how is this decided.

**Comment by Pinchanzee** [comment]
This also happens to me on Ubuntu 16.04.  The rules are valid because the messages are filtered when I "Process entire inbox".
I'm using 1.1.3 with no additional plugins.

**Comment by Tamriel** [comment]
Same for me on Manjaro. The rules are valid because the messages are filtered when I "Process entire inbox". 
I'm using 1.1.4 with no additional plugins.
My hoster is `mail.ru`.

**Comment by Pinchanzee** [comment]
I think it might just be the 'Move Messages' action that's not working.  When I have rules with both 'Move Messages' and 'Mark as Read', it does the 'Mark as Read' action automatically, just not the move.

**Comment by domenico-ruggiano** [comment]
Same for me, with an IMAP standard account

**Comment by jo-chemla** [comment]
Same for me, on an IMAP account, Mailspring 1.1.4 on Windows.

**Comment by Pinchanzee** [comment]
Is this some sort of obscure feature?  I see the text "One message in this thread is hidden because it was moved to trash or spam" which could potentially explain why it's still in my inbox.. But why would I want something I'm explicitly marking trash or junk in my inbox at all?  If I check my Trash, it is in there, and it has been read, so the mail rule has been applied, but there's still that copy in my inbox which I obviously don't want.

Again, it's removed when I "Process entire inbox".

**Comment by giedriusStan** [comment]
+1 for this issue, currently this is the only thing preventing me from replacing thunderbird with mailspring

**Comment by adolson** [comment]
I get the same thing, but it's not consistent. Sometimes mail is moved properly, other times it just fills my inbox.

Is there any way to set a keyboard shortcut to process the inbox? That would make this problem slightly less annoying.

**Comment by EniasCailliau** [comment]
+1 for this issue, Same here, I am using 1.2.1 on Ubuntu 17.10.

**Comment by Tera3yte** [comment]
+1 for this issue, installed via snapd on Linux Mint 18.3

**Comment by giovazz89** [comment]
+1 for this issue: on my ubuntu 16.04 it seems to move messages only when the main application panel is open; if it runs in background or has been closed, messages wont be moved automatically

**Comment by nikolayanchev** [comment]
+1 for this issue
+ another issue when the client runs in the background and not open/minimized, the blue dot for new messages on the tray icon doesn't appear when the client is running in the background.It appears only when the client is open or minimized.
this is on ubuntu 16.04

**Comment by PrimarchAlpharius** [comment]
+1 for this issue, on ubuntu 18.04, tried installing both via snap and .deb, v1.4.2

**Comment by brandonp2412** [comment]
+1 for this issue, on Linux Mint 19.0 Cinnamon.

**Comment by Jens0512** [comment]
+1 for this issue, on Linux 4.18.7-arch1-1-ARCH x86_64 GNU/Linux

**Comment by intrazik** [comment]
Same here, mint 18 on Cinnamon +1 for the shortCut

**Comment by jotaf98** [comment]
Any idea at all what could be causing this?

**Comment by soxat** [comment]
+1 for this issue, on Fedora 29

**Comment by ElementalWarrior** [comment]
@bengotow anyway to tag this as a bug, mark as a linux issue, and have it prioritized for a fix?

**Comment by oddjobz** [comment]
+1 for this issue on Ubuntu 18.04

**Comment by johanneskoester** [comment]
Same here. Switching to back Thunderbird.

**Comment by Jens0512** [comment]
Also switched to Thunderbird because of this

**Comment by MohamedKhelifi** [comment]
+1 for this issue on Ubuntu 18.04

**Comment by bengotow** [comment]
Hey folks! Sorry for the delay on this one - I believe this will be fixed in the next release, just testing the patch now. A while back, some code was added to ensure that mail rules would only run once when the message was synced and not repeatedly when it was viewed, marked as read, etc.

This code checked a version bit and made sure that the "version" of the object in the local database was `1`. Higher than 1? Must have already run mail rules.

This used to be a valid assumption. (It was always a hack, but it was a very small efficient hack we all agreed was best at some point.. 🤷‍♂️) However, the new C++ sync engine now pulls down messages and their bodies separately for a better user experience, and it debounces updates sent to the JavaScript application so that the UI doesn't get flooded with changes as the mail is synced. This means that 1) mail rules that require the message body don't always work, since it might not be there yet and 2) in some cases, the message is created and updated with it's body so fast that version 1 of the message object is never handed to the JavaScript app - it goes straight to version 2 and mail rules are not run.

In the next release, the C++ sync engine will explicitly emit an event to the JS application indicating it's finished fetching the message AND it's body and then mail rules will run on that message. This does mean that in some cases mail rules will be delayed by a second or two more (since we're waiting for the message bodies rather than running the rules as soon as the message hits the inbox.) I think this is a worthwhile tradeoff though - a lot of future mail rules we could implement (like attachment / custom header tests, message language tests, etc.) that would be super cool would require the full message.

Stay tuned!

**Comment by quixoticraindrp** [comment]
What operating system are you using?

macOS 10.14.4

What version of Mailspring are you using?

1.6.1

Bug?

Yes.

Do you have any third-party plugins installed? If so, which ones?

No.

Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I currently only have mail rules defined for iCloud.

1.6.1 does not fix this issue for me.
They will not run on messages as they are downloaded. They only run when manually triggered from the Preferences view.

**Comment by phcorp** [comment]
same here

What operating system are you using?

deepin 15.9.3 desktop

What version of Mailspring are you using?

1.6.1-aceed8e5

Bug?

Yes.

Do you have any third-party plugins installed? If so, which ones?

No.

Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I currently use only an Office365 account

1.6.1 does not fix this issue for me.
They will **not always** run on messages as they are downloaded. Running them manually through the Preferences view **always** works though.

**Comment by Notim** [comment]
To the same error appears

**What operating system are you using?**
Windows 10 Education Build 18362.535

**What version of Mailspring are you using?**
1.7.2

**Bug?**
Yes.

**Do you have any third-party plugins installed? If so, which ones?**
No.

**Is the issue related to a specific email provider (Gmail, Exchange, etc.)?**

I currently use an Yahoo.mail account

Obs: Email rules work when my inbox has too few emails, but when there are too many emails the system processes but doesn't change anything on the server, currently my inbox contains 2500 emails.
I have a rule with 14 sender emails throwing to a specific folder

**Comment by bengotow** [comment]
Closing after inactivity

**Comment by regnerisch** [comment]
But is it fixed?

**Comment by jizongFox** [comment]
I observed this for now.

**Comment by working-name** [comment]
It's not fixed, @bengotow it still happens with 1.7.8 and it's also a move rule. If I hit process inbox it does what it's supposed to do but does not act on incoming email.

**Comment by CyRamos** [comment]
Hey fellas :)
Currently I'm with 1.8.0-8983dca2 release (just updated  rodude123 version from 1.7.8--13635bcf)
Reference : https://community.getmailspring.com/t/for-those-installing-on-an-arch-based-distribution/125

OS : Manjaro
I also have troubles with the rules (upgrade version because the issue however it doesn't fix it, badly I didn't find any higher release version for Arch Based Distros).
Hopefully you could find me some solution as well because I got 3th party automation I built based on that rules and it's kind of urgent for me..
Thanks :)
