### ISSUE TITLE
3 questions about Mailspring

### ISSUE THREAD

**Issue by owner** [Foundry376/Mailspring#630]
Hello.

I started using Your program recently. But I already liked it. I want to help you.

1. Russian - i dont know how to translate your APP. Maybe you have translation center?
2. Forever Subscription - maybe $100 or $50? Best app and fastly for me and my PC.
3. Vkontakte Link in Signature?

Thank you :)

**Comment by bengotow** [comment]
Hey! Thanks @owner I appreciate it! Translation is going to be a pretty involved process because the original version of the app wasn't designed for it, but we're getting things organized over in #226.

We've debated doing a "forever subscription" but haven't decided what to do yet—the money from the monthly subscriptions allows me to keep maintaining the app, so if everyone pays for forever subscriptions and stops paying monthly, 12-16 months later I might be in trouble.

I'll see if we can add a `VK` link to the signature too next time we revisit the signatures panel.

Thanks!
