### ISSUE TITLE
High CPU Load - A Crypto Miner ?

### ISSUE THREAD

**Issue by edrcq** [Foundry376/Mailspring#643]
Hello World !

I just install Mailspring, from the official website, and what happens ? The CPU usage of Mailspring was 25% everytime. I restarted my computer, with mailspring start at boot. It was a 25% directly, without GUI, without receiving mails...

On the "System Monitor" I saw 2 threads (I've a 4 core, 8 threads i7 CPU) a 100% and threads load change every 10 seconds. It was a good multi-sinusoidal graphic of the CPU load.

Now I've desinstalled, I wonder why....

Crypto Miner ?
Infinite Loop ?

**Comment by bengotow** [comment]
Hey! Haha no crypto mining (though maybe I'll add that to the list of alternative business models.) Can you try downloading the latest release (v1.1.3) and see if it resolves this for you? It's normal to see Mailspring using significant CPU after you link a large account.

**Comment by cwells** [comment]
Frankly, I'd personally be okay with cryptomining as an alternative payment method, so long as 

1) It's off by default and can be controlled by the user.
2) Mining hours can be scheduled (e.g. at night).
3) It doesn't run so hot that it kills my laptop ;-)

As a legitimate payment method, it makes a lot of economic sense for the end user. Your computer is worth $96 dollars more per year than it otherwise would have been.
