### ISSUE TITLE
Unable to add IMAP/SMTP account (Yandex.ru and Mail.ru)

### ISSUE THREAD

**Issue by egoistonly** [Foundry376/Mailspring#71]
##### What operating system are you using?
Deepin 15.4.1

##### What version of Mailspring are you using?
1.0.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Same Yandex.ru & Mail.ru

Error after some minutes of Adding account...
![deepinscreenshot_20171007132755-2017-10-07-13-31-33-2](https://user-images.githubusercontent.com/10616956/31307030-acebae92-ab64-11e7-8fc0-2de7686ac64a.png)

Waiting for Account JSON:

Waiting for Identity JSON:

 ***
 *** A segmentation fault occurred during program execution.
 *** This typically happens when you try to dereference a pointer
 *** that is NULL or invalid.
 ***
10879 [2017-10-07 21:40:48.637] [main] [critical]  *** Stack trace (line numbers are approximate):
 *** ??:?                     AccumulatorLogger::log(void*, mailcore::ConnectionLogType, mailcore::Data*)
 *** mailstream_low.c:244     mailstream_low_read
 *** mailstream.c:306         mailstream_feed_read_buffer
 *** mailstream_helper.c:102  mailstream_read_line_append
 *** mailstream_helper.c:116  mailstream_read_line_remove_eol
 *** mailsmtp.c:189           mailsmtp_connect
 *** ??:?                     mailcore::SMTPSession::connect(mailcore::ErrorCode*)
 *** ??:?                     runTestAuth(shared_ptr)
 *** ??:?                     main
 ***

/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4: 10879 Segmentation fault      LD_LIBRARY_PATH=". ${LD_LIBRARY_PATH}" "$(dirname $0)/mailsync.bin" "$@"

**Comment by bengotow** [comment]
Whoa! That's a crazy error - thanks for reporting it here. I don't think I've ever seen this one before.

I'll try getting a mail.ru account to reproduce. Just out of curiosity, does this happen consistently if you try again?

**Comment by egoistonly** [comment]
Yes. Again and again. I tried 4 times for different accounts

**Comment by kc9jud** [comment]
Can confirm on Kubuntu 17.04. Similar segfault with email hosted by arvixe.com: 
![mailspring_segfault-blanked](https://user-images.githubusercontent.com/4133644/31350891-d864ef8c-acf6-11e7-9e90-d61d2c1a82f9.png)

**Comment by kc9jud** [comment]
Update: I was able to connect by using SSL/TLS instead of STARTTLS on the SMTP server.

**Comment by egoistonly** [comment]
@bengotow  Fantastic! Version 1.0.3 works like a charm! Thank you Ben! May close this issue

**Comment by bengotow** [comment]
Great! Thanks guys—

**Comment by tylerjackoliver** [comment]
Hi, sorry to piggyback on this issue, but I'm getting the above problem also, but on 1.0.5-2a95f8f7. Full stuff:

**What operating system are you using?**

Ubuntu 16.04LTS

**What version of Mailspring are you using?**

1.0.5-2a95f8f7

--

Bug?
**Do you have any third-party plugins installed? If so, which ones?**

No

**Is the issue related to a specific email provider (Gmail, Exchange, etc.)?**

IMAP - webmail.1and1.co.uk.

The error message reads:

Waiting for Account JSON:

Waiting for Identity JSON:

 ***
 *** A segmentation fault occurred during program execution.
 *** This typically happens when you try to dereference a pointer
 *** that is NULL or invalid.
 ***
12621 [2017-10-19 14:38:32.132] [main] [critical]  *** Stack trace (line numbers are approximate):
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4: 12621 Segmentation fault      SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"

And a screencap of the settings, minus my email address:

![image](https://user-images.githubusercontent.com/14252874/31773702-6e7e747a-b4db-11e7-8fe9-2d68fc54e2ec.png)

and the output:

![image](https://user-images.githubusercontent.com/14252874/31773729-84d34642-b4db-11e7-86a1-59b5906c5259.png)


Thanks!
