### ISSUE TITLE
Signature Gone After Updating MailSpring Version

### ISSUE THREAD

**Issue by andrewrphillips** [Foundry376/Mailspring#75]
##### What operating system are you using?
Mac OS 10.13

##### What version of Mailspring are you using?
Version 1.0.2 

--

**Bug?**
When I upgraded to the newest version of Mailspring, my saved signatures disappeared.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I've only got an exchange account in Mailspring, but I suspect it is not provider specific.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—sorry for the hassle. Mailspring 1.0.0 shipped with a few old `nylas.*` config properties and signatures was one of them. We fixed them in 1.0.2 in preparation for a brand new signatures editor, and I was hoping nobody would notice since it was only a few days after release. It shouldn't happen again!
