### ISSUE TITLE
Display hangs, parts disappear and refreshes constantly  

### ISSUE THREAD

**Issue by akomarovsky** [Foundry376/Mailspring#751]
##### What operating system are you using?
Linux Ubuntu 17.10

##### What version of Mailspring are you using?
Version 1.1.5-5834c99f

**Bug?**
When using mainspring the display constantly blinks and parts disappear. It's like the electron engine trying to repaint the UI every second.
I use VS code which runs also with electron with no issues.

##### Do you have any third-party plugins installed? If so, which ones?
No, fresh install

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![screenshot from 2018-03-09 10-22-49](https://user-images.githubusercontent.com/20887752/37197986-68edf260-2385-11e8-86f5-3269a4453482.png)

**Comment by andrew-s** [comment]
So, I have the same issue on one of my PC's (and only sometimes on my laptop).

I don't see other Electron apps do this, running Ubuntu 16.04.4 with an AMD GPU - I don't have the official drivers because they don't work on that kernel version.  Saying that, this happens *sometimes* on my Dell XPS with the official nivida drivers also.

As a side note, this happens on all Mailspring UI's *except* from the pop-out email preview (double clicking on an email item), that window doesn't suffer the same problem).
