### ISSUE TITLE
Windows 10, attachment smtp problem.

### ISSUE THREAD

**Issue by Wilq1977** [Foundry376/Mailspring#757]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10 pro

##### What version of Mailspring are you using?
1.1.4-22d9f20d and older has the same issue

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
when I attach a file (doc, pdf, whatever) by drag'n'drop or by clicking icon
I can not send a message!. I got an error:
"
We encountered an SMTP error that prevented this message from being delivered:

Connection Error - Unable to connect to the server / port you provided.
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
"
but this same e-mail after deleting attachment runs smooth :)

I tried a 2 different accounts (from this same provider) ant antoher PC.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![image](https://user-images.githubusercontent.com/36410225/37299494-c26b510c-2623-11e8-9201-af74a87a19b0.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by silviapmores** [comment]
I have the same problem. 

I have Windows 10 and the same Mailspring version. (If I try to update it says there was an error checking updates)

- I had problems with an account with my own domain name. Gmail is fine. 
- I sent the e-mail via webmail and it worked
- I changed the port to 25 and 578 and didn't work
- I checked the "Allow insecure SSL" and didn't work
- I tried to send a single picture and it didn't work

**Comment by Wilq1977** [comment]
So more, I overinstalled newest version 1.1.5-5834c99f
and there is this same problem :(

but....

I uninstall mailspring and delete folders:
c:\users\me\appdata\local\mailspring
and
c:\users\me\appdata\roaming\mailspring

and do clean install newest version and BUM! works for this moment like swiss car :)

**Comment by silviapmores** [comment]
I did the same but nothing changed...

**Comment by Wilq1977** [comment]
HI!.
Did You deleting folders that i list below:?
c:\users\me\appdata\local\mailspring
and
c:\users\me\appdata\roaming\mailspring

instead of "me" use your user name,
i suspect drive "C:" is your operating system folder.

**Comment by olaflarry** [comment]
same issue here. Running two windows 10 pc`s with same mailspring versions, with same mailspring account, with same mailbox. On one PC everything is ok, on other PC, when I attach a fil, I got SMTP error. EVERY setting is exacly the same. I unistaled mailspring with deleting folders in appdata - nothing changed...

**Comment by silviapmores** [comment]
I did everything you said and nothing changed, I can't even send a photo...

**Comment by Wilq1977** [comment]
Hi again!
I have 1.2.2 and i really do not know why mailspring do not send attachment right. Usally send them without problems but sometimes not. 
I previous verision works tip what i wrote before. 
In 1.2.2 i tried everyfing, reinstalling, clean install and registry clean (auto and by finger), and i have to said: I do not see a pernament solution for this problem. I think it is a problem in develper/programmers level and we as user cannot solve this :(

**Comment by Fregaa** [comment]
Same problem here, no attachment works just fine, with attachment I got the same error here, I will try to reinstall as sugested above.

**Comment by Fregaa** [comment]
forgot to say, Im using version 1.7.2-4522b259, (latestest version, 08 november 2019)

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sending-e-mail-with-attachments-generates-error-sorry-mailspring-was-unable-to-deliver-this-message-connection-error-unable-to-connect-to-the-server-port-you-provided/673

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team
