### ISSUE TITLE
[Bug] Cannot read property 'snooze' of undefined 

### ISSUE THREAD

**Issue by natronq** [Foundry376/Mailspring#775]
##### Are there any related issues?

No

##### What operating system are you using?
macOS 10.13.3

##### What version of Mailspring are you using?
1.1.5

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
FastMail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

When trying to snooze a message the following message appears:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/6431099/37654438-5a697e60-2c42-11e8-97ca-b21190f5461d.png">

Log output:
[mailspring.log](https://github.com/Foundry376/Mailspring/files/1829258/mailspring.log)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this–it looks like Mailspring was unable to load your Mailspring identity. We had some issues earlier this week where the Mailspring web service was going down intermittently due to scaling issues, and I think a bad response from the server could have caused this. I've taken care of that, so I'm going to go ahead and close this and we'll reopen it if the problem pops up again.
