### ISSUE TITLE
Odd Cmd-A behavior in composer

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#803]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS 10.13.3

##### What version of Mailspring are you using?
1.2.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
- In a *new* composer window (i.e. starting a thread) Cmd-A doesn't do anything. Expected behavior is that it would copy everything but your signature.
- In a *reply* composer window (i.e. continuing a thread), Cmd-A copies literally everything, including signatures and all past text. I would expect that it would only copy everything above your signature, but actually not sure what is normal here.

**Comment by bengotow** [comment]
Hey! Ahh man this one is interesting... I think this is actually a bug in the version of the Slate text editor library Mailspring uses. When the last element in the document is a signature - one of those blocks that you remove as a single unit rather than as text - it seems like Slate is unable to "select to the end". I think they've fixed this - will see if we can upgrade to the new version of the library soon.

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
