### ISSUE TITLE
No menu bars when running under KDE

### ISSUE THREAD

**Issue by kirbyfan64** [Foundry376/Mailspring#81]
##### Are there any related issues?

This is from https://github.com/nylas/nylas-mail/issues/2687.

##### What operating system are you using?

Kubuntu 17.04.

##### What version of Mailspring are you using?

1.0.2-4eab3f85.

Basically, the menu bar doesn't appear under Plasma; you have to hit Alt for it to appear. With the original Nylas, it took me ages to figure this out, and I'm hoping this will be fixed with Mailspring!

**Comment by bengotow** [comment]
Hey! Would love if someone with more Linux knowledge could take a look at this one - it might be an easy thing to fix (maybe there's a flag we can pass to Electron BrowserWindow?)

**Comment by b0o** [comment]
Just wanted to note that I experience this as well and have to hit alt to show the menu bar. I always thought that was the intended behavior, though.

**Comment by kirbyfan64** [comment]
I mean, IMO the core options (e.g. preferences) should at least be easier to access...

**Comment by Thalexander** [comment]
The menu bar is set to auto hide in app/src/browser/mailspring-window.coffee on line 56. Changing that to false corrects the behaviour under KDE, however I am not sure how that would affect the behavior on other platforms.

**Comment by b0o** [comment]
You can set a keyboard shortcut to open preferences. I'd like to retain the option to keep the menubar hidden as I think it makes the interface look a lot cleaner, perhaps this could be a toggle-able option?

**Comment by stakoov** [comment]
I think this problem is form KDE 5.9 APIs. In this version ( i think) they introduce option to change global and local(window) menus. I will install KDE and check it. @kirbyfan64 which version of KDE, kububtu runs?

**Comment by skylite21** [comment]
This could be related to this thread, or at least to what it's coming from. I am runnig KDE and mailspring menu is inside the window instead of the top menu.  Is there any way to move it to the top menu?
![Screenshot_20210409_224554](https://user-images.githubusercontent.com/7330136/114239662-a2be9b00-9986-11eb-90eb-cbe87946b476.png)

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@skylite21: Can you please create a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address what you're seeing, but it's best addressed as a new bug, especially as we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team
