### ISSUE TITLE
Sometimes emails are sent with a blank body

### ISSUE THREAD

**Issue by emadow** [Foundry376/Mailspring#858]
This happens quite often. Sometimes emails are sent with no body—it's just blank.

MacOS 10.13.4
Mailspring 1.2.1

**Comment by patelom** [comment]
Same happened to me once. I typed the email (I was replying to the email) and sent. The email went blank. Not able to reproduce, but this bug has potential to create a huge problem for the user.

**Comment by emadow** [comment]
@bengotow this continues to be a hard block for me using the app. any update? thanks!

**Comment by vertoforce** [comment]
^ Agreed, critical problem here.

**Comment by chipkellam** [comment]
I can confirm I have seen this issue several times in the past few days. Never had a problem until recently. Running OS X 10.3.6 and Mailspring 1.3.0

**Comment by vertoforce** [comment]
Bump on this?  It's been happening more and more often, I'm about to cancel my subscription.

**Comment by bengotow** [comment]
Hey folks - thanks for filing this. I'm sorry this issue has languished for so long, it proved to be really difficult to narrow down. I'm going to merge this forward into #948 and post an update there. It turns out this happens reliably (hooray! much easier to fix that way...) if you are composing an email which contains a /ton/ of quoted text and you have "undo send" turned off. In this situation, a race condition can occur where the draft is still saving when it's sent. Will post more in #948. This will be fixed in the next release!
