### ISSUE TITLE
[Feature Request] Address book

### ISSUE THREAD

**Issue by axllent** [Foundry376/Mailspring#86]
Are there plans to add an address book, or to be more precise, read & edit access to the Gmail address book?

**Comment by rhaces** [comment]
Unfortunately, without this feature, mailspring is simply unusable....

**Comment by jpbaril** [comment]
I'm maybe dreaming in Technicolor, but would there be any way to just connect to the default OS defined address book app instead of recreating the wheel?

**Comment by ohynek96** [comment]
Sync with Google Contacts would be also great.

**Comment by lazylionca** [comment]
This [article](https://foundry376.zendesk.com/hc/en-us/articles/115001875711-Can-I-create-or-modify-contacts-through-Mailspring-) on Zendesk says that Mailspring scans the headers of emails to build a list of addresses.

Unfortunately it somehow missed the one email address i send to most: a group email that is over 30 chars long forcing me to type it every time. 

But it did manage to find two email addresses that were mistyped once a year ago and add them, with no way to remove or hide them. It is getting aggravating.

**Comment by lazylionca** [comment]
So I got flustered with this contacts issue, did some digging around and found [this](https://medium.com/cameron-nokes/how-to-store-user-data-in-electron-3ba6bf66bc1e).

Mailspring is an Electron app so where they store contacts isn't too hard to find. 
For your edification: 

**Windows:**
`C:\Users\User\AppData\Roaming\Mailspring\edgehill.db`

note: The AppData folder is hidden. You can access it by just typing "appdata" in the filename box.


**OSx:**
`~/Library/Application Support/Mailspring/edgehill.db`

note: On OSx the Library folder is hidden so it can be a pain to get to. To make it easier create a shortcut to by opening the Terminal and use LN:
`ln -s  ~/Library ~/lib`
So now you'll be looking for ~/lib/Application Support/Mailspring/edgehill.db 

!!!!!Before you go any further, MAKE COPY OF edgehill.db AS A BACKUP!!!!
!!!!I am not responsible if you mess things up!!!!!! 


To see whats in there, and (if you are brave enough) make changes, use this handy [SQLite DB Browser](https://github.com/sqlitebrowser/sqlitebrowser/releases).




The SQLite DB Browser has four buttons in the top row. Click "Open Database" and navigate to one of the above. When you are done, click Write Changes. If you think you messed something up, click Revert Changes or just quit without saving. 

!!!!! Again, MAKE a BACKUP !!!!!!!


Once in, click on the "Browse Data" tab. There are two tables that we are concerned with:

Contact and ContactSearch
  
Contact is a list of Contacts.
  
ContactSearch is a list of Search terms related to that Contact. This is what shows up when you start typing in the To, CC, or BCC fields. 
  
**You have to edit entries in both tables.**
  
Widen the columns so you can see the contents and use the filter boxes to find that email you mistyped once four years ago. For example, when I start typing "kyles mom" I don't want "kylie minogue" showing up. But because I typo'd and entered "kyles minogue" once in my gmail fifteen years ago, Mailspring has unhelpfully decided that's what I'm looking for.
  
If you understand databases:
  
The "id Column" in "Table Contact" and the "content_id Column" in "Table ContactSearch" are "related"
Each table should only have ONE entry for "BigGayAl@hotmail.org", but there may also be an entry for "BigGayAl@hotmale.org" which is not the same thing, but probably has the same search terms.
  
You can also find your buddies old university email address and delete it since he graduated 12 years ago and only uses his work email now. You can also delete all those email addresses that you got spam from, as well as anything like "no-reply@company.com". (unless of course you're into that sort of thing)

Go ahead and delete your ex's email too cause it's been years and you should really stop drunk emailing her.
  
Mailspring is trying to helpful, but sometimes you have to be smarter than the computer.

Once you have eliminated the annoying redundancies and expired email addresses and are certain you don't have duplicate ID entries, click "Write Changes".

Make sure you made a backup first!!!


Hope this helps as a temporary solution until someone takes up the challenge of creating a contacts editor.


Good Luck.

Some guy on the internet.

**Comment by pitwegner** [comment]
Well, they said "soon" 11 months ago.. I need this feature!
[https://foundry376.zendesk.com/hc/en-us/articles/115001875711-Can-I-create-or-modify-contacts-through-Mailspring-](https://foundry376.zendesk.com/hc/en-us/articles/115001875711-Can-I-create-or-modify-contacts-through-Mailspring-)

**Comment by knireis** [comment]
I would like to see support for contacts as well. 
Mailspring is very unpredictable in which emailaddresses are stored.

**Comment by phanky5** [comment]
@bengotow can you give an ETA for this feature?

**Comment by maxime-des** [comment]
Looking forward to this feature too. @bengotow [seems to say](https://github.com/Foundry376/Mailspring/issues/1333#issuecomment-460515892) it will be released this year :) !

**Comment by bengotow** [comment]
Hey folks! I'm happy to announce that Mailspring 1.7.0 shipped earlier today, which includes a full address book accessible from **Window > Contacts** in the menu. In addition to being able to see your address book synced from your mail provider and manage contacts and contact groups, this release also allows you to disable the "Found in Mail" autocompletions on a per-account basis, or delete individual "Found in Mail" suggestions you find annoying.

One small caveat is that Google address books are read only, pending Google's approval of our "read/write contacts" OAuth scope.

When composing emails, people from your address book always appear above our "Found in Mail" suggestions and this update also allows you to type the name of a contact group and press Enter to quickly add everyone in the group to the recipients list.

Enjoy! If you run in to bugs or other problems, please open new issues.
