### ISSUE TITLE
MALWARE WARNING: Mailspring secretly installs hidden User Agent to your system, runs even if you delete Mailspring

### ISSUE THREAD

**Issue by SeAlgoAsoma** [Foundry376/Mailspring#899]
I opened Mailspring on my system the other day and decided I don't want to use it because I don't believe I should have to surrender my private email address to a third party in order to use an email client on my machine. I only opened it the one time and then closed it, for good, when it asked me to set up a "Mailspring ID". 

Well, imagine my surprise when I was poking around the next day with LaunchControl and discovered that Mailspring had secretly installed a User Agent which was running on my machine, even though I opted not to use the app or even sign up for the account they claim is "required" to use it. 

A User Agent is a startup item that runs silently in the background of your computer. It doesn't even appear in the startup items GUI of your user account, you need to use a special utility, poke around in your Library subfolders, or use terminal commands to find out that it's even there. Mailspring does not ask permission or alert you in any way that it is installing this hidden software, and deleting the Mailspring app from your hard drive will not remove it. In my hood, we call that "malware".

The only way to remove the hidden User Agent is, after deleting the Mailspring app from your hard drive, to drop into terminal and type:

   rm ~/Library/LaunchAgents/com.mailspring.plist

Then reboot your machine. 

I did comment about this in another thread but that was an old, buried thread I felt the issue was worth publicizing to anyone who might be considering downloading this. 

Caveat emptor. Secretly installing hidden User Agents, forcing you to sign up for a weird third party "ID" accounts that no email client should ever need just to open the app and look at it, calling it "open source" when it still includes closed-source code... it's all too much. If I had known about all the sketchiness I wouldn't have touched this project with a 10 foot pole, myself.

**Comment by tbertels** [comment]
On Windows, there's an Update.exe file run at startup that lingers after uninstall in C:\Users\[username]\AppData\Local\Mailspring along with a ".dead" file.
This may be the equivalent to that LaunchAgent.

**Comment by bengotow** [comment]
Hey! Mailspring maintainer here—I know this stuff often seems sketchy-by-default, but the plist file you referenced (`~/Library/LaunchAgents/com.mailspring.plist`) specifies that Mailspring should be started when your computer launches. I think there's an option to enable/disable this during onboarding, but it might be initialized to true and then you have to uncheck the box when you reach that step of the welcome flow. (I'll check and see - we can probably avoid creating the item until you reach that step. You probably didn't reach this step if you quit at the Mailspring ID screen!)

I think Mailspring also adds itself to your Dock with a similar entry elsewhere.

If you remove the Mailspring app from your Applications folder, these references won't do anything—that plist file just says "hey macOS, open mailspring". There's no code in there or secret functionality, background processes, etc. Other apps do sometimes use background processes to do meaningful things (see: Dropbox kernel extension), but Mailspring isn't one of them. Just a typical standalone desktop app.

Unfortunately, there's no standard protocol for writing uninstallers on macOS, so we can't really have Mailspring clean up this stuff on it's own, but typically removing the app from the Applications folder is all you need to do to remove the code since these other configuration files just reference the app.
