### ISSUE TITLE
Emails sent from Mailspring are marked as "fradulent" by recipients

### ISSUE THREAD

**Issue by aaronplanell** [Foundry376/Mailspring#908]
Hello, 

I'm using version 1.2.1 and when I send an email this is marked as **fraudulent** to the people who receive it. And if they open the detail they see information about mailspring. This is very weird... 

Best regards.

**Comment by aaronplanell** [comment]
Hello. What about that? It's very suspicious and I think I will stop of using Mailspring...

**Comment by bengotow** [comment]
Hey @aaronplanell thanks for reaching out—depending on the email provider you use, they may not want you to send HTML email, or it may be that the recipient has email scanning software that picks up on the open and link tracking. There are also a few providers (like yandex.com) that require that you verify your phone number before using third-party email clients, so that might do it too! If you could let me know what email provider you're using, I can probably help more!

**Comment by aaronplanell** [comment]
Hello @bengotow . It's a corporative exchange server...

**Comment by CodeMouse92** [comment]
This is answered here: https://community.getmailspring.com/t/my-emails-are-going-to-spam/390
