### ISSUE TITLE
Connection Error - Unable to connect to the server / port you provided.

### ISSUE THREAD

**Issue by Ads20000** [Foundry376/Mailspring#918]
Not able to send messages (receiving messages is fine) via Outlook.com / Hotmail at university. I get the following error:

```
We encountered an SMTP error that prevented this message from being delivered:

Connection Error - Unable to connect to the server / port you provided.
```

##### Are there any related issues?

Not as far as I'm aware.

##### What operating system are you using?
```
$ snap version
snap    2.33~rc1
snapd   2.33~rc1
series  16
ubuntu  18.04
kernel  4.15.0-22-generic
$ snap info core
tracking:     beta
refresh-date: 11 days ago, at 15:49 BST
installed:   16-2.33~rc1                (4734) 91MB core
```

##### What version of Mailspring are you using?
```
$ snap info mailspring
tracking:     edge
refresh-date: 5 days ago, at 22:52 BST
installed:   1.2.3 (217) 164MB -
```

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No plugins installed.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Outlook.com

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Not as far as I'm aware.

**Comment by dania-ru** [comment]
Experience the same error.


snap    2.32.8+18.04
snapd   2.32.8+18.04
series  16
ubuntu  18.04
kernel  4.15.0-22-generic

tracking:  stable
refreshed: 2018-05-24T22:12:17+03:00
installed:   1.2.2 (216) 164MB -
channels:                
  stable:    1.2.2 (216) 164MB -
  candidate: 1.2.2 (216) 164MB -
  beta:      1.2.2 (216) 164MB -
  edge:      1.2.3 (217) 164MB -

**Comment by fabpin** [comment]
THe Same error with debian 8 on Deepin OS of 64 bits

**Comment by mariofelesdossantosjunior** [comment]
The same error with Deepin, the server problem is Outlook.com

**Comment by dimmuboy** [comment]
The same problem with Antergos on private mail server.

**Comment by hankblip** [comment]
@bengotow this issue persists - and I have no responses to my support requests on getmailspring.com - has anyone found a fix yet?

One minute I can send emails and the next I cannot. Very frustrating.

**Comment by tosinafolabi** [comment]
I have the same issue, sometimes with my Gmail account. I use Mailspring on MacOS (10.13.6).

I've noticed that when this happens, I'm connected to my main ISP and I'm able to temporarily bypass the issue by switching to a different internet connection.

My guess – could it have something to do with the Mailspring server refusing connections (temporarily, perhaps) from certain IP addresses?

**Comment by kirkbeard** [comment]
I've had the same error for weeks now running macOS 10.13.6 with MailSpring 1.4.2, using Fastmail.com as my email provider.

It's a pretty frustrating, and completely random error.

**Comment by onlydole** [comment]
Seeing this issue as well with my Gmail account 

![screen shot 2018-09-18 at 9 54 50 am](https://user-images.githubusercontent.com/117500/45703363-f519e100-bb28-11e8-8e43-068a22fa3d6c.png)

**Comment by AGraphicDesigner** [comment]
I'm using Windows 10 and I've been getting this error almost every time I try to send an email from my private email host. The only thing that works is quitting Mailspring entirely, waiting around 10 seconds, then reopening Mailspring and sending the email again. I can't begin to explain how frustrating this is.

**Comment by Ancillas** [comment]
Bump.

Still happens periodically on MacOS 10.14.2 (Mojave), running Mailspring 1.5.5 against Office 365 Exchange.

I cannot reliably reproduce the error, but it does happen 5-10 times a day after sending an email.

**Comment by hankblip** [comment]
I have bailed on mailspring purely because of this error. It literally drove me nuts. No more. Paid the money and bought Postbox which is not as good but at least it works.

**Comment by mdhedelund** [comment]
This bug is killing mailspring for me. It happens on Arch Linux (Antergos) and Windows 10. It doesn't seem to be OS specific.

**Comment by vlad-tuznichenko** [comment]
Hi! I have the same problem. Does we have news?

**Comment by mjssln** [comment]
I have the same today with GMAIL / OFFICE / OUTLOOK.
Ubuntu 18.10, mailspring 1.5.7 ...

**Comment by ThomasVandenabeele** [comment]
Here also the same error since a couple of days..
Ubuntu 18.10 and Mailspring 1.5.7.
I already tried uninstalling Mailspring.

**Comment by asparc** [comment]
Same error for me on Mailspring 1.5.7 and on Mailspring 1.6.0 (Ubuntu 16.04).
`Connection Error - Unable to connect to the server / port you provided. (SMTP)`
The incoming mail works fine, but outgoing mail fails.

**Comment by jarredwitt** [comment]
Happening almost every time that I try to send a message on v1.6.0. Have to retry several times before it will go through.

**Comment by sixdenip** [comment]
Same problem, Mailspring 1.6.1 on Ubuntu 18.10 with Outlook.

**Comment by anandkumar89** [comment]
I've have the same connecting mailspring on windows 10. However I'm able to connect other mail service through imap.
Please provide some solution to this. default mail sucks on windows 10 !

**Comment by saxrussell** [comment]
Same issue. Incoming mail is fine, just cannot send using Gmail.
```
> snap version
snap    2.39
snapd   2.39
series  16
ubuntu  19.04
kernel  5.0.0-15-generic

> snap info mailspring
channels:
  stable:    1.6.1 2019-04-05 (346) 202MB -
  candidate: 1.6.1 2019-04-05 (346) 202MB -
  beta:      1.6.1 2019-04-05 (346) 202MB -
  edge:      1.6.2 2019-04-05 (347) 202MB -
installed:   1.6.1            (346) 202MB -
```

**Comment by igorbarkowsky** [comment]
Same error today (about IMAP) on ubuntu 19.04, Mailspring version 1.6.1 from deb-package.
But i have problems with Gmail auth in Geary too (with app passwords), maybe the reason is Gmail, not Mailspring.

**Comment by dominicoder** [comment]
I came on this thread from Googling the issue. After reading this thread for ideas, I tried **disabling my VPN** and tried again and it worked. So if you've got a VPN up when trying to use MailSpring, double check and see if it's your culprit.

**Comment by kburudi** [comment]
Am having the same issue with mailspring on mac.
I just purchased a domain recently and am trying to connect to my account and I keep getting the error: 
`Connection Error - Unable to connect to the server / port you provided. (SMTP)`
I've specified port `465` for outgoing mails which is what was required from my domain service provider.
I've tried with my vpn on and off and it's pretty much the same

```
----------IMAP----------
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
1 LOGIN "name@mail.com" "*********"
1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY NAMESPACE LITERAL+ NOTIFY SPECIAL-USE COMPRESS=DEFLATE QUOTA] Logged in
2 COMPRESS DEFLATE
2 OK Begin compression (0.001 + 0.000 secs).
3 ENABLE QRESYNC
* ENABLED QRESYNC
3 OK Enabled (0.001 + 0.000 secs).
4 NAMESPACE
* NAMESPACE (("INBOX." ".")) NIL NIL
4 OK Namespace completed (0.001 + 0.000 secs).
5 LIST "INBOX." "*"
* LIST (\HasNoChildren \UnMarked \Archive) "." INBOX.Archive
* LIST (\HasChildren \UnMarked) "." INBOX.Mailspring
* LIST (\HasNoChildren \UnMarked) "." INBOX.Mailspring.Snoozed
* LIST (\HasNoChildren \UnMarked) "." INBOX.Junk
* LIST (\HasNoChildren \UnMarked \Trash) "." INBOX.Trash
* LIST (\HasNoChildren \UnMarked \Sent) "." INBOX.Sent
* LIST (\HasNoChildren \UnMarked \Drafts) "." INBOX.Drafts
* LIST (\HasNoChildren \UnMarked \Junk) "." INBOX.spam
5 OK List completed (0.002 + 0.000 + 0.001 secs).
6 LIST "" "INBOX"
* LIST (\HasChildren) "." INBOX
6 OK List completed (0.001 + 0.000 secs).


----------SMTP----------

SMTP Last Response Code: 0

SMTP Last Response: 

mailsmtp Last Error Code: MAILSMTP_ERROR_STREAM

mailsmtp Last Error Location: 1

mailsmtp Last Auth Type: 0
```

When however switch to port: 587 it worked though I am only able to receive and not send notifications with this configuration

**Comment by maciejzasuwa** [comment]
The same issue here. The first reports are more than one year old and no solution, no statement from developers. It is sad because this app has potential to be one of the best mail apps, but this bug makes it useless. Even Windows 10 Mail is better because it works.

**Comment by AlpSha** [comment]
Same here. It seems that no fix is coming.

**Comment by EtorArza** [comment]
I am also encountering this error for a gmail account, using the wifi at my workplace. However, I changed to the personal hotspot of my iphone, and it worked right away. I think it has to do with the internet configuration. Perhaps someone is able to reproduce the bug by setting up an VPN and see if it is working as suggested by @dominicoder .


I am using Ubuntu 18.04.3 LTS, mailspring version 1.7.1-45d4260b , using the precompiled .deb package.

I hope the issue can be fixed, because it is quite annoying, and it seems it has been going on for over a year now.

**Comment by Luckey-Elijah** [comment]
I am unable to send messages on certain networks. particularly my work network (and all of it's remote locations). I get this error whenever I try to send emails.

![image](https://user-images.githubusercontent.com/38171761/68045365-b228b780-fcaf-11e9-806d-bb981d26e05e.png)

I can receive emails. I also receive the _Activity tracking_ information. The only issue is sending emails. And this occurs across all my account in Mailspring on sent email on said networks. Otherwise, Mailspring works on most networks. 

Note: I am not on a VPN. The firewall rules for the DOS'ed network allow standard email ports (other email clients operate fine).

**Comment by soylisK** [comment]
I have the same problem using Ubuntu 18.04 LTS and mailspring 1.7.2 at first it wasn't syncing the income mails or syncing an internity without a result. I removed my account and try to add it again but always the same message 

> "Connection Error - Unable to connect to the server/port you provided. (IMAP) "

I tried to use the outlook /office365/(IMAP/SMTP) option but nothing happens. My account is an outlook account which is a type of Exchange server in other email clients programs.

**Comment by haythamfood4lifeae** [comment]
My issue is that my macOS hostname had a single quote, which was failing the SMTP HELO command ... by simply doing a sudo hostname "newcomputer namehere" it worked.

**Comment by haythamelkhoja** [comment]
My issue is that my macOS hostname had a single quote, which was failing the SMTP HELO command ... by simply doing a sudo hostname "newcomputer namehere" it worked.

**Comment by AnthonyEmmanuelO** [comment]
i am uninstalling this right away. simple

**Comment by HaoZeke** [comment]
Still an issue.

**Comment by wifiuk** [comment]
the same issue with me, using gmail kubuntu

**Comment by alecspuch** [comment]
i have the same issue linux mint 20, 
it is working good with a gmail account but once i manualy ad an imap account the problem gets present

**Comment by CodeMouse92** [comment]
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

**This is a difficult bug to diagnose because there appear to actually be *three* (or more) separate issues:**

* @wifiuk (or anyone else), can you please confirm that you're still having this problem with **Gmail** on **Mailspring 1.8.0**. If so, please [open a new Sync Issue on our Discourse](https://community.getmailspring.com/c/sync/22). You're welcome to include a link back to this topic. (Additionally, please note whether disabling your VPN resolves the problem, as that'll be important for diagnosis.)

* If you're having trouble connecting to an Office 365 account, see: https://community.getmailspring.com/t/institutional-office365-not-working/48

* @alecspuch (or anyone else), please confirm you're still having a problem with an **IMAP account** (not Google or Outlook) in **Mailspring 1.8.0**. If so, please [open a new Sync Issue on our Discourse](https://community.getmailspring.com/c/sync/22). You're welcome to include a link back to this topic. (Additionally, please note whether disabling your VPN resolves the problem, as that'll be important for diagnosis.)

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
