### ISSUE TITLE
How do search just inbox?

### ISSUE THREAD

**Issue by rykr** [Foundry376/Mailspring#925]
Everytime I type a search term it shows me stuff form trash and everything else.  Are there keywords that support just searching certain folders or just inbox?

**Comment by bengotow** [comment]
Hey! This will be fixed in the next release - I'm overhauling the search bar to include an autocomplete dropdown that offers contextual search filters, including the `in:inbox` filter. Stay tuned!

<img width="480" alt="image" src="https://user-images.githubusercontent.com/1037212/42728213-3cb32cd0-876a-11e8-80f5-9f1eb369021d.png">

**Comment by bengotow** [comment]
Hey folks—this shipped in version 1.3.0. The app should have auto-updated by now, but if not you can download the latest release from https://www.getmailspring.com/download. Enjoy!
