### ISSUE TITLE
sending empty e-mail instead of what I wrote

### ISSUE THREAD

**Issue by kpalczewski** [Foundry376/Mailspring#948]
Operating system:
Linux 17.10 [EDIT - Ubuntu 17.10]

MailSpring version:
1.2.2-96fb3a99

--

I have got a response on my gmail account.
I tap reply.
I enter some text (signature was automatically added)
I tap sent
The e-mail sent is empty (only with signature), even though I entered some text.

**Comment by emadow** [comment]
+1 also been having this issue for a while now
https://github.com/Foundry376/Mailspring/issues/858

**Comment by heliostatic** [comment]
Yeah, I've had this a couple of times. Can't find a pattern.

**Comment by vertoforce** [comment]
Same issue here...

**Comment by jyboudreau** [comment]
Same here. This issue has unfortunately made me switch clients. 

I was willing to cope with some of the crashes and some other issues because I love the client, but when I look dumb to my customers I can't keep using it.

**Comment by emadow** [comment]
Yeah, I really loved mailspring but it was _humiliating_ sending repeat blank emails to important contacts.

Since I was a paying pro customer, this was not something I could continue to do. Really hope this gets properly maintained one day!

**Comment by alexpgates** [comment]
Note this is still happening on Version 1.3.0. I can't find a pattern, either, but it happens consistently with at least one contact (that I've noticed, anyway).

I went ahead and downgraded back to the free plan. I can't afford to write emails that vanish and instead deliver blank emails to clients. 
I'm hoping this one gets fixed soon - I'll happily resubscribe if it does.

**Comment by GroomedGorilla** [comment]
Same issue here. Seems to have subsided for a while but it's back to being an issue. I've written long important emails only to have them wiped completely, and to have the email send out blank.

I've started copying the contents of the message before hitting send but it's still an inconvenient position to be in.

**Comment by actan** [comment]
Same here and i am on 1.4.2 on Deepin linux.It happened about 5 times in past 2 weeks and I can't figure out how it just happened. I was hitting reply and entered something, but finally only my signature was sent. 
Mailspring is really good except this critical bug.

**Comment by bengotow** [comment]
Hey folks—thanks for the reports and follow-up, sorry it's taken so long to get to the bottom of this one. I was talking to some folks on Twitter about this today and they mentioned this bug happens more reliably with emails with significant quoted text. I created a 200,000 character email, replied to it, and was able to consistently get a blank reply instead of mine.

Mailspring saves your draft and then sends it, but it turns out we were only waiting for the final "save" task to /start/ and not for it to /finish/ before starting the send process. If you have a slow filesystem, a huge mail database or a huge draft, it could take a non-trivial amount of time for SQLite to complete the save transaction, and Mailspring may have initiated the send by the time it finished saving. This would result in the app sending whatever the draft's previous state was - empty, signature only, or sometimes just a body you'd written earlier.

I'm really glad we've finally tracked this down and I appreciate your patience. Thanks for all the feedback and details that helped track it down. I'm putting together a release this week will ship this fix ASAP. 🙏

**Comment by vertoforce** [comment]
Thanks so much and great work tracking this down, this is huge I can't wait for the fix!!

**Comment by emadow** [comment]
Thank you @bengotow! So glad the root cause was identified.

**Comment by sikand** [comment]
Can't wait for the new release :+1:
