### ISSUE TITLE
Chocolatey package is missing

### ISSUE THREAD

**Issue by machinekoder** [Foundry376/Mailspring#965]
There is no mailspring package for [Chocolatey](https://chocolatey.org/) yet. Would be useful to have.

##### Are there any related issues?
No

##### What operating system are you using?
Windows 10

##### Does this feature exist in another mail client or tool you use?
Most applications I use have a Chocolatey package makes it really convenient to install.

**Comment by bengotow** [comment]
Ahh this looks cool! Hadn't heard of Chocolatey. It looks like we can set it up to pull from the official download server, so I'll see if I can publish a package.

**Comment by bengotow** [comment]
Hey! Just a quick update—someone actually submitted Mailspring to Chocolatey (https://chocolatey.org/packages/mailspring) but it was rejected because they weren't a maintainer of the project (which is definitely a good thing - they also uploaded an exe rather than just having it use the Mailspring download server, which is sketchy.) I have a nupkg ready to go to replace that one—I actually just cloned Slack's since it's also an Electron app. Hopefully the Chocolatey folks will get back to my support request quickly and we can swap it in!

**Comment by machinekoder** [comment]
@bengotow Awesome, thank you.

**Comment by bengotow** [comment]
Just a quick update on this—I'm not the maintainer of https://chocolatey.org/packages/mailspring and I've submitted the new version for review. Looks like we should be good to go as soon as one of their moderators takes a look!

**Comment by bengotow** [comment]
Package has been approved. All done here!
