### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by agurz** [Foundry376/Mailspring#97]
Hi @bengotow, just to track this out, there are some deprecated dependencies. I don't know how updating those will impact on the app but it seems that some of them are important updates:

npm WARN deprecated coffee-react-transform@2.4.1: some edge cases fail to transform
npm WARN deprecated ignore@2.2.19: **several bugs fixed in v3.2.1**
npm WARN deprecated minimatch@2.0.10: **Please update to minimatch 3.0.2 or higher to avoida RegExp DoS issue**
npm WARN deprecated safe-to-string-x@2.0.3: Moved to https://github.com/Xotic750/to-string-symbols-supported-x
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoida RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. **Please update to graceful-fs@^4.0.0 as soon as possible**. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by bengotow** [comment]
Hey thanks for filing this—if you do an `npm list` you can see which of Mailspring's dependencies are using these node modules (they're not used directly, they're like... dependencies of dependencies of dependencies...) In order to get this fixed, we'd need to get those folks to upgrade their packages. 

A bunch of these are related to Grunt I think, and should only be in the main `package.json` file with the build dependencies, and aren't in the `app/package.json` file of packages that are shipped in the app.

**Comment by bengotow** [comment]
Hey folks—now that we've moved away from Coffeescript, the deprecated dependencies are just in use by the build tools (the node modules in the top level folder and not in the `app` folder.) Gonna close this!
