### ISSUE TITLE
Everymails are marked like "important"

### ISSUE THREAD

**Issue by rplanchuelo** [Foundry376/Mailspring#971]
##### Are there any related issues?

...

##### What operating system are you using?
Antergos (Arch Linux)
Kernel 4.17.4-1-ARCC
KDE Plasma: 5.13.2
KDE Frameworks: 5.47.0
Qt: 5.11.1
OS 64 bits

...

##### What version of Mailspring are you using?
1.2.2.96fb3a99 (from snap)
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail and Outlook
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No, always
...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No. I use Thunderbird too and it works ok
...

**Comment by bengotow** [comment]
Hey—Mailspring delegates to Gmail for the important labels shown on your mail. If you don't really use Gmail's important feature it may not be trained very well on your mail data. Removing the flag from lots of unimportant email will prevent those kinds of emails from being marked as important in the future.

(Closing this because there's really no "which mails are important" logic / decision making in Mailspring)
