### ISSUE TITLE
Feature Request: Option to choose which folders to sync

### ISSUE THREAD

**Issue by Fivelfivel** [Foundry376/Mailspring#978]
**Feature Request?**
It would be great to be able to choose which folders to sync locally. Using an IMAP account that is more than 10gb, the vast majority of it archived, I don't need all of that sync'd locally. 

##### Does this feature exist in another mail client or tool you use?
Not sure if it exists as an option in a desktop client, though Canary (the OS X mail app) seems to do it automatically — meaning, doesn't appear to sync the full folder if I'm not accessing it. Most mail apps on mobile phones include this option, however — including options to sync "Full Folder," "None," or something time-dependent, such as "Last Week" or "Last Month". 

Thanks for the work so far!

**Comment by bengotow** [comment]
Merging this into #888 - thanks!

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/per-account-per-folder-sync-scan-cache-settings/474

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Fivelfivel: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
